// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: openmarket/api/v1/auth_service.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated enum Openmarket_Api_V1_DevicePlatform: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case ios // = 1
  case android // = 2
  case web // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .ios
    case 2: self = .android
    case 3: self = .web
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .ios: return 1
    case .android: return 2
    case .web: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Openmarket_Api_V1_DevicePlatform] = [
    .unspecified,
    .ios,
    .android,
    .web,
  ]

}

/// StartPhoneVerification asks the SMS provider to deliver a code. It is
/// unauthenticated and it costs money on every call — see docs/backend.md §5 for
/// what guards it, and for why almost all of that is the provider's job rather
/// than ours.
public nonisolated struct Openmarket_Api_V1_StartPhoneVerificationRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// E.164, including the leading "+". The client is expected to have composed
  /// this from a country picker rather than free text.
  public var phoneNumber: String = String()

  public var devicePlatform: Openmarket_Api_V1_DevicePlatform = .unspecified

  /// The same install_id VerifyPhoneRequest carries, sent one call earlier.
  ///
  /// Forwarded to the verification provider as an anti-fraud signal and nothing
  /// else: no account exists yet, so there is nothing to store it against. A
  /// provider that scores requests can tell a real install asking about one
  /// number from a script walking a range; the phone number alone cannot.
  ///
  /// Optional, unlike on VerifyPhoneRequest — a missing signal costs some
  /// scoring accuracy, and refusing to send a code over it would be worse.
  public var installID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Openmarket_Api_V1_StartPhoneVerificationResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// How long to count down before offering "Resend".
  ///
  /// A server-owned hint rather than an enforced limit: the provider's own
  /// per-number limit is what actually stops a runaway client, and keeping the
  /// number here means tuning the pacing doesn't need an app release.
  public var resendAvailableInSeconds: Int32 = 0

  /// Digits expected in the code, so the entry field can size itself rather than
  /// hardcoding a number the provider owns.
  public var codeLength: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// VerifyPhone exchanges a delivered code for a session. This is the only way an
/// account comes into existence: a first successful verification creates the
/// user, so there is no separate signup call.
public nonisolated struct Openmarket_Api_V1_VerifyPhoneRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var phoneNumber: String = String()

  public var code: String = String()

  public var devicePlatform: Openmarket_Api_V1_DevicePlatform = .unspecified

  /// Device-reported IANA/TZDB zone, e.g. "America/Los_Angeles".
  public var timeZone: String {
    get {_timeZone ?? String()}
    set {_timeZone = newValue}
  }
  /// Returns true if `timeZone` has been explicitly set.
  public var hasTimeZone: Bool {self._timeZone != nil}
  /// Clears the value of `timeZone`. Subsequent reads from it will return its default value.
  public mutating func clearTimeZone() {self._timeZone = nil}

  /// Client-generated, stable for the life of this install, and the only call
  /// that needs it — the session records which device it belongs to, and every
  /// later RPC derives the device from the session.
  ///
  /// Opaque to the server: it is a correlation key for install-scoped state, not
  /// an identifier that has to mean anything. See the `user_devices` migration.
  public var installID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _timeZone: String? = nil
}

public nonisolated struct Openmarket_Api_V1_VerifyPhoneResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var accessToken: String = String()

  public var refreshToken: String = String()

  /// Lifetime of access_token. Reported rather than left for the client to read
  /// out of the JWT: the token's internals are the server's business, and a
  /// client that parses them is a client that breaks when the claims change.
  public var accessTokenExpiresInSeconds: Int32 = 0

  public var viewer: Openmarket_Api_V1_Viewer {
    get {_viewer ?? Openmarket_Api_V1_Viewer()}
    set {_viewer = newValue}
  }
  /// Returns true if `viewer` has been explicitly set.
  public var hasViewer: Bool {self._viewer != nil}
  /// Clears the value of `viewer`. Subsequent reads from it will return its default value.
  public mutating func clearViewer() {self._viewer = nil}

  /// True only on the call that created the account. The client uses it to
  /// decide whether to run onboarding, rather than inferring it from an empty
  /// profile.
  public var isNewUser: Bool = false

  /// This install. Returned at login so the app knows immediately whether
  /// Facebook is connected *here* — which, on a phone the user has just switched
  /// to, is false however long they have had the account.
  public var device: Openmarket_Api_V1_Device {
    get {_device ?? Openmarket_Api_V1_Device()}
    set {_device = newValue}
  }
  /// Returns true if `device` has been explicitly set.
  public var hasDevice: Bool {self._device != nil}
  /// Clears the value of `device`. Subsequent reads from it will return its default value.
  public mutating func clearDevice() {self._device = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _viewer: Openmarket_Api_V1_Viewer? = nil
  fileprivate var _device: Openmarket_Api_V1_Device? = nil
}

public nonisolated struct Openmarket_Api_V1_RefreshTokenRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var refreshToken: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Openmarket_Api_V1_RefreshTokenResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var accessToken: String = String()

  /// Refresh tokens rotate on every use; the old one is dead the moment this
  /// returns.
  public var refreshToken: String = String()

  public var accessTokenExpiresInSeconds: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Openmarket_Api_V1_LogoutRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Openmarket_Api_V1_LogoutResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "openmarket.api.v1"

nonisolated extension Openmarket_Api_V1_DevicePlatform: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0DEVICE_PLATFORM_UNSPECIFIED\0\u{1}DEVICE_PLATFORM_IOS\0\u{1}DEVICE_PLATFORM_ANDROID\0\u{1}DEVICE_PLATFORM_WEB\0")
}

nonisolated extension Openmarket_Api_V1_StartPhoneVerificationRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StartPhoneVerificationRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}phone_number\0\u{3}device_platform\0\u{3}install_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.phoneNumber) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.devicePlatform) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.installID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.phoneNumber.isEmpty {
      try visitor.visitSingularStringField(value: self.phoneNumber, fieldNumber: 1)
    }
    if self.devicePlatform != .unspecified {
      try visitor.visitSingularEnumField(value: self.devicePlatform, fieldNumber: 2)
    }
    if !self.installID.isEmpty {
      try visitor.visitSingularStringField(value: self.installID, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Openmarket_Api_V1_StartPhoneVerificationRequest, rhs: Openmarket_Api_V1_StartPhoneVerificationRequest) -> Bool {
    if lhs.phoneNumber != rhs.phoneNumber {return false}
    if lhs.devicePlatform != rhs.devicePlatform {return false}
    if lhs.installID != rhs.installID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Openmarket_Api_V1_StartPhoneVerificationResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StartPhoneVerificationResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}resend_available_in_seconds\0\u{3}code_length\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.resendAvailableInSeconds) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.codeLength) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.resendAvailableInSeconds != 0 {
      try visitor.visitSingularInt32Field(value: self.resendAvailableInSeconds, fieldNumber: 1)
    }
    if self.codeLength != 0 {
      try visitor.visitSingularInt32Field(value: self.codeLength, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Openmarket_Api_V1_StartPhoneVerificationResponse, rhs: Openmarket_Api_V1_StartPhoneVerificationResponse) -> Bool {
    if lhs.resendAvailableInSeconds != rhs.resendAvailableInSeconds {return false}
    if lhs.codeLength != rhs.codeLength {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Openmarket_Api_V1_VerifyPhoneRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".VerifyPhoneRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}phone_number\0\u{1}code\0\u{3}device_platform\0\u{3}time_zone\0\u{3}install_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.phoneNumber) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.code) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.devicePlatform) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._timeZone) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.installID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.phoneNumber.isEmpty {
      try visitor.visitSingularStringField(value: self.phoneNumber, fieldNumber: 1)
    }
    if !self.code.isEmpty {
      try visitor.visitSingularStringField(value: self.code, fieldNumber: 2)
    }
    if self.devicePlatform != .unspecified {
      try visitor.visitSingularEnumField(value: self.devicePlatform, fieldNumber: 3)
    }
    try { if let v = self._timeZone {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    if !self.installID.isEmpty {
      try visitor.visitSingularStringField(value: self.installID, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Openmarket_Api_V1_VerifyPhoneRequest, rhs: Openmarket_Api_V1_VerifyPhoneRequest) -> Bool {
    if lhs.phoneNumber != rhs.phoneNumber {return false}
    if lhs.code != rhs.code {return false}
    if lhs.devicePlatform != rhs.devicePlatform {return false}
    if lhs._timeZone != rhs._timeZone {return false}
    if lhs.installID != rhs.installID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Openmarket_Api_V1_VerifyPhoneResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".VerifyPhoneResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}access_token\0\u{3}refresh_token\0\u{1}viewer\0\u{3}is_new_user\0\u{3}access_token_expires_in_seconds\0\u{1}device\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.accessToken) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.refreshToken) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._viewer) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.isNewUser) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self.accessTokenExpiresInSeconds) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._device) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.accessToken.isEmpty {
      try visitor.visitSingularStringField(value: self.accessToken, fieldNumber: 1)
    }
    if !self.refreshToken.isEmpty {
      try visitor.visitSingularStringField(value: self.refreshToken, fieldNumber: 2)
    }
    try { if let v = self._viewer {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if self.isNewUser != false {
      try visitor.visitSingularBoolField(value: self.isNewUser, fieldNumber: 4)
    }
    if self.accessTokenExpiresInSeconds != 0 {
      try visitor.visitSingularInt32Field(value: self.accessTokenExpiresInSeconds, fieldNumber: 5)
    }
    try { if let v = self._device {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Openmarket_Api_V1_VerifyPhoneResponse, rhs: Openmarket_Api_V1_VerifyPhoneResponse) -> Bool {
    if lhs.accessToken != rhs.accessToken {return false}
    if lhs.refreshToken != rhs.refreshToken {return false}
    if lhs.accessTokenExpiresInSeconds != rhs.accessTokenExpiresInSeconds {return false}
    if lhs._viewer != rhs._viewer {return false}
    if lhs.isNewUser != rhs.isNewUser {return false}
    if lhs._device != rhs._device {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Openmarket_Api_V1_RefreshTokenRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RefreshTokenRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}refresh_token\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.refreshToken) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.refreshToken.isEmpty {
      try visitor.visitSingularStringField(value: self.refreshToken, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Openmarket_Api_V1_RefreshTokenRequest, rhs: Openmarket_Api_V1_RefreshTokenRequest) -> Bool {
    if lhs.refreshToken != rhs.refreshToken {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Openmarket_Api_V1_RefreshTokenResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RefreshTokenResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}access_token\0\u{3}refresh_token\0\u{3}access_token_expires_in_seconds\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.accessToken) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.refreshToken) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.accessTokenExpiresInSeconds) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.accessToken.isEmpty {
      try visitor.visitSingularStringField(value: self.accessToken, fieldNumber: 1)
    }
    if !self.refreshToken.isEmpty {
      try visitor.visitSingularStringField(value: self.refreshToken, fieldNumber: 2)
    }
    if self.accessTokenExpiresInSeconds != 0 {
      try visitor.visitSingularInt32Field(value: self.accessTokenExpiresInSeconds, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Openmarket_Api_V1_RefreshTokenResponse, rhs: Openmarket_Api_V1_RefreshTokenResponse) -> Bool {
    if lhs.accessToken != rhs.accessToken {return false}
    if lhs.refreshToken != rhs.refreshToken {return false}
    if lhs.accessTokenExpiresInSeconds != rhs.accessTokenExpiresInSeconds {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Openmarket_Api_V1_LogoutRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".LogoutRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Openmarket_Api_V1_LogoutRequest, rhs: Openmarket_Api_V1_LogoutRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Openmarket_Api_V1_LogoutResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".LogoutResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Openmarket_Api_V1_LogoutResponse, rhs: Openmarket_Api_V1_LogoutResponse) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
