// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: openmarket/api/v1/listing.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated enum Openmarket_Api_V1_FacebookMarketplaceBrowserVariant: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case desktop // = 1
  case mobile // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .desktop
    case 2: self = .mobile
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .desktop: return 1
    case .mobile: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Openmarket_Api_V1_FacebookMarketplaceBrowserVariant] = [
    .unspecified,
    .desktop,
    .mobile,
  ]

}

public nonisolated enum Openmarket_Api_V1_FacebookMarketplacePageRoute: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case search // = 1
  case discover // = 2
  case item // = 3
  case sellerProfile // = 4
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .search
    case 2: self = .discover
    case 3: self = .item
    case 4: self = .sellerProfile
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .search: return 1
    case .discover: return 2
    case .item: return 3
    case .sellerProfile: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Openmarket_Api_V1_FacebookMarketplacePageRoute] = [
    .unspecified,
    .search,
    .discover,
    .item,
    .sellerProfile,
  ]

}

public nonisolated enum Openmarket_Api_V1_FacebookMarketplaceExtractionMethod: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0

  /// Structured MarketplaceSearch data embedded in the first desktop page.
  case embeddedGraphql // = 1

  /// Rendered text, attributes, links, and images in the page DOM.
  case renderedDom // = 2

  /// One observation combined fields from both structured data and the DOM.
  /// Current item-detail extraction does this.
  case hybrid // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .embeddedGraphql
    case 2: self = .renderedDom
    case 3: self = .hybrid
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .embeddedGraphql: return 1
    case .renderedDom: return 2
    case .hybrid: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Openmarket_Api_V1_FacebookMarketplaceExtractionMethod] = [
    .unspecified,
    .embeddedGraphql,
    .renderedDom,
    .hybrid,
  ]

}

public nonisolated enum Openmarket_Api_V1_FacebookAuthenticationState: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case signedOut // = 1
  case signedIn // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .signedOut
    case 2: self = .signedIn
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .signedOut: return 1
    case .signedIn: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Openmarket_Api_V1_FacebookAuthenticationState] = [
    .unspecified,
    .signedOut,
    .signedIn,
  ]

}

public nonisolated enum Openmarket_Api_V1_FacebookMarketplaceSellerSectionStatus: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0

  /// The capture context cannot expose seller identity (currently signed-out
  /// desktop item pages). This is unknown, not evidence that no seller exists.
  case unavailable // = 1

  /// The page was capable of exposing the section but extraction did not
  /// observe it. Keep this distinct from an observed section with empty fields.
  case notObserved // = 2
  case observed // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .unavailable
    case 2: self = .notObserved
    case 3: self = .observed
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .unavailable: return 1
    case .notObserved: return 2
    case .observed: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Openmarket_Api_V1_FacebookMarketplaceSellerSectionStatus] = [
    .unspecified,
    .unavailable,
    .notObserved,
    .observed,
  ]

}

public nonisolated struct Openmarket_Api_V1_FacebookMarketplaceObservationContext: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The Facebook browser variant that was parsed, not the observer's hardware.
  /// A phone requesting the desktop site records DESKTOP here.
  public var browserVariant: Openmarket_Api_V1_FacebookMarketplaceBrowserVariant = .unspecified

  public var pageRoute: Openmarket_Api_V1_FacebookMarketplacePageRoute = .unspecified

  public var extractionMethod: Openmarket_Api_V1_FacebookMarketplaceExtractionMethod = .unspecified

  public var facebookAuthenticationState: Openmarket_Api_V1_FacebookAuthenticationState = .unspecified

  public var observedAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {_observedAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_observedAt = newValue}
  }
  /// Returns true if `observedAt` has been explicitly set.
  public var hasObservedAt: Bool {self._observedAt != nil}
  /// Clears the value of `observedAt`. Subsequent reads from it will return its default value.
  public mutating func clearObservedAt() {self._observedAt = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _observedAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
}

/// At least one Facebook key must be present. Desktop cards expose listing_id;
/// mobile cards may only expose the cover-photo filename FBID until opened.
public nonisolated struct Openmarket_Api_V1_FacebookListingKey: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var facebookListingID: String {
    get {_facebookListingID ?? String()}
    set {_facebookListingID = newValue}
  }
  /// Returns true if `facebookListingID` has been explicitly set.
  public var hasFacebookListingID: Bool {self._facebookListingID != nil}
  /// Clears the value of `facebookListingID`. Subsequent reads from it will return its default value.
  public mutating func clearFacebookListingID() {self._facebookListingID = nil}

  /// The durable numeric segment parsed from the fbcdn filename. This is not
  /// primary_listing_photo.id; measured values differ.
  public var coverPhotoFbid: String {
    get {_coverPhotoFbid ?? String()}
    set {_coverPhotoFbid = newValue}
  }
  /// Returns true if `coverPhotoFbid` has been explicitly set.
  public var hasCoverPhotoFbid: Bool {self._coverPhotoFbid != nil}
  /// Clears the value of `coverPhotoFbid`. Subsequent reads from it will return its default value.
  public mutating func clearCoverPhotoFbid() {self._coverPhotoFbid = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _facebookListingID: String? = nil
  fileprivate var _coverPhotoFbid: String? = nil
}

public nonisolated struct Openmarket_Api_V1_FacebookMarketplacePriceObservation: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Facebook's decimal string, in major units (for example "40.00"). Keep the
  /// source value: converting to minor units requires knowing the currency's
  /// exponent, which a rendered card does not always reveal.
  public var amountDecimal: String {
    get {_amountDecimal ?? String()}
    set {_amountDecimal = newValue}
  }
  /// Returns true if `amountDecimal` has been explicitly set.
  public var hasAmountDecimal: Bool {self._amountDecimal != nil}
  /// Clears the value of `amountDecimal`. Subsequent reads from it will return its default value.
  public mutating func clearAmountDecimal() {self._amountDecimal = nil}

  public var formattedAmount: String {
    get {_formattedAmount ?? String()}
    set {_formattedAmount = newValue}
  }
  /// Returns true if `formattedAmount` has been explicitly set.
  public var hasFormattedAmount: Bool {self._formattedAmount != nil}
  /// Clears the value of `formattedAmount`. Subsequent reads from it will return its default value.
  public mutating func clearFormattedAmount() {self._formattedAmount = nil}

  public var previousAmountDecimal: String {
    get {_previousAmountDecimal ?? String()}
    set {_previousAmountDecimal = newValue}
  }
  /// Returns true if `previousAmountDecimal` has been explicitly set.
  public var hasPreviousAmountDecimal: Bool {self._previousAmountDecimal != nil}
  /// Clears the value of `previousAmountDecimal`. Subsequent reads from it will return its default value.
  public mutating func clearPreviousAmountDecimal() {self._previousAmountDecimal = nil}

  public var previousFormattedAmount: String {
    get {_previousFormattedAmount ?? String()}
    set {_previousFormattedAmount = newValue}
  }
  /// Returns true if `previousFormattedAmount` has been explicitly set.
  public var hasPreviousFormattedAmount: Bool {self._previousFormattedAmount != nil}
  /// Clears the value of `previousFormattedAmount`. Subsequent reads from it will return its default value.
  public mutating func clearPreviousFormattedAmount() {self._previousFormattedAmount = nil}

  public var currencyCode: String {
    get {_currencyCode ?? String()}
    set {_currencyCode = newValue}
  }
  /// Returns true if `currencyCode` has been explicitly set.
  public var hasCurrencyCode: Bool {self._currencyCode != nil}
  /// Clears the value of `currencyCode`. Subsequent reads from it will return its default value.
  public mutating func clearCurrencyCode() {self._currencyCode = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _amountDecimal: String? = nil
  fileprivate var _formattedAmount: String? = nil
  fileprivate var _previousAmountDecimal: String? = nil
  fileprivate var _previousFormattedAmount: String? = nil
  fileprivate var _currencyCode: String? = nil
}

public nonisolated struct Openmarket_Api_V1_FacebookMarketplacePlaceObservation: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var displayText: String {
    get {_displayText ?? String()}
    set {_displayText = newValue}
  }
  /// Returns true if `displayText` has been explicitly set.
  public var hasDisplayText: Bool {self._displayText != nil}
  /// Clears the value of `displayText`. Subsequent reads from it will return its default value.
  public mutating func clearDisplayText() {self._displayText = nil}

  public var city: String {
    get {_city ?? String()}
    set {_city = newValue}
  }
  /// Returns true if `city` has been explicitly set.
  public var hasCity: Bool {self._city != nil}
  /// Clears the value of `city`. Subsequent reads from it will return its default value.
  public mutating func clearCity() {self._city = nil}

  public var region: String {
    get {_region ?? String()}
    set {_region = newValue}
  }
  /// Returns true if `region` has been explicitly set.
  public var hasRegion: Bool {self._region != nil}
  /// Clears the value of `region`. Subsequent reads from it will return its default value.
  public mutating func clearRegion() {self._region = nil}

  public var country: String {
    get {_country ?? String()}
    set {_country = newValue}
  }
  /// Returns true if `country` has been explicitly set.
  public var hasCountry: Bool {self._country != nil}
  /// Clears the value of `country`. Subsequent reads from it will return its default value.
  public mutating func clearCountry() {self._country = nil}

  public var facebookPlaceID: String {
    get {_facebookPlaceID ?? String()}
    set {_facebookPlaceID = newValue}
  }
  /// Returns true if `facebookPlaceID` has been explicitly set.
  public var hasFacebookPlaceID: Bool {self._facebookPlaceID != nil}
  /// Clears the value of `facebookPlaceID`. Subsequent reads from it will return its default value.
  public mutating func clearFacebookPlaceID() {self._facebookPlaceID = nil}

  /// Facebook's published, approximate listing point. Never reinterpret this as
  /// the seller's home or business location.
  public var latitude: Double {
    get {_latitude ?? 0}
    set {_latitude = newValue}
  }
  /// Returns true if `latitude` has been explicitly set.
  public var hasLatitude: Bool {self._latitude != nil}
  /// Clears the value of `latitude`. Subsequent reads from it will return its default value.
  public mutating func clearLatitude() {self._latitude = nil}

  public var longitude: Double {
    get {_longitude ?? 0}
    set {_longitude = newValue}
  }
  /// Returns true if `longitude` has been explicitly set.
  public var hasLongitude: Bool {self._longitude != nil}
  /// Clears the value of `longitude`. Subsequent reads from it will return its default value.
  public mutating func clearLongitude() {self._longitude = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _displayText: String? = nil
  fileprivate var _city: String? = nil
  fileprivate var _region: String? = nil
  fileprivate var _country: String? = nil
  fileprivate var _facebookPlaceID: String? = nil
  fileprivate var _latitude: Double? = nil
  fileprivate var _longitude: Double? = nil
}

public nonisolated struct Openmarket_Api_V1_FacebookMarketplaceMediaObservation: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var facebookPhotoID: String {
    get {_facebookPhotoID ?? String()}
    set {_facebookPhotoID = newValue}
  }
  /// Returns true if `facebookPhotoID` has been explicitly set.
  public var hasFacebookPhotoID: Bool {self._facebookPhotoID != nil}
  /// Clears the value of `facebookPhotoID`. Subsequent reads from it will return its default value.
  public mutating func clearFacebookPhotoID() {self._facebookPhotoID = nil}

  public var url: String {
    get {_url ?? String()}
    set {_url = newValue}
  }
  /// Returns true if `url` has been explicitly set.
  public var hasURL: Bool {self._url != nil}
  /// Clears the value of `url`. Subsequent reads from it will return its default value.
  public mutating func clearURL() {self._url = nil}

  public var position: Int32 {
    get {_position ?? 0}
    set {_position = newValue}
  }
  /// Returns true if `position` has been explicitly set.
  public var hasPosition: Bool {self._position != nil}
  /// Clears the value of `position`. Subsequent reads from it will return its default value.
  public mutating func clearPosition() {self._position = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _facebookPhotoID: String? = nil
  fileprivate var _url: String? = nil
  fileprivate var _position: Int32? = nil
}

public nonisolated struct Openmarket_Api_V1_FacebookMarketplaceSellerObservation: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var sectionStatus: Openmarket_Api_V1_FacebookMarketplaceSellerSectionStatus = .unspecified

  /// Numeric id from /marketplace/profile/<id>. Stable on signed-in desktop item
  /// pages and preferable to clustering on name plus listing coordinates.
  public var facebookProfileID: String {
    get {_facebookProfileID ?? String()}
    set {_facebookProfileID = newValue}
  }
  /// Returns true if `facebookProfileID` has been explicitly set.
  public var hasFacebookProfileID: Bool {self._facebookProfileID != nil}
  /// Clears the value of `facebookProfileID`. Subsequent reads from it will return its default value.
  public mutating func clearFacebookProfileID() {self._facebookProfileID = nil}

  public var displayName: String {
    get {_displayName ?? String()}
    set {_displayName = newValue}
  }
  /// Returns true if `displayName` has been explicitly set.
  public var hasDisplayName: Bool {self._displayName != nil}
  /// Clears the value of `displayName`. Subsequent reads from it will return its default value.
  public mutating func clearDisplayName() {self._displayName = nil}

  public var joinedText: String {
    get {_joinedText ?? String()}
    set {_joinedText = newValue}
  }
  /// Returns true if `joinedText` has been explicitly set.
  public var hasJoinedText: Bool {self._joinedText != nil}
  /// Clears the value of `joinedText`. Subsequent reads from it will return its default value.
  public mutating func clearJoinedText() {self._joinedText = nil}

  public var joinedYear: Int32 {
    get {_joinedYear ?? 0}
    set {_joinedYear = newValue}
  }
  /// Returns true if `joinedYear` has been explicitly set.
  public var hasJoinedYear: Bool {self._joinedYear != nil}
  /// Clears the value of `joinedYear`. Subsequent reads from it will return its default value.
  public mutating func clearJoinedYear() {self._joinedYear = nil}

  public var rating: Double {
    get {_rating ?? 0}
    set {_rating = newValue}
  }
  /// Returns true if `rating` has been explicitly set.
  public var hasRating: Bool {self._rating != nil}
  /// Clears the value of `rating`. Subsequent reads from it will return its default value.
  public mutating func clearRating() {self._rating = nil}

  public var ratingCount: Int32 {
    get {_ratingCount ?? 0}
    set {_ratingCount = newValue}
  }
  /// Returns true if `ratingCount` has been explicitly set.
  public var hasRatingCount: Bool {self._ratingCount != nil}
  /// Clears the value of `ratingCount`. Subsequent reads from it will return its default value.
  public mutating func clearRatingCount() {self._ratingCount = nil}

  /// Facebook's rendered "Highly rated on Marketplace" designation. This is
  /// observed from Facebook, not derived from rating and rating_count. The
  /// threshold behind Facebook's designation is not published.
  public var highlyRated: Bool {
    get {_highlyRated ?? false}
    set {_highlyRated = newValue}
  }
  /// Returns true if `highlyRated` has been explicitly set.
  public var hasHighlyRated: Bool {self._highlyRated != nil}
  /// Clears the value of `highlyRated`. Subsequent reads from it will return its default value.
  public mutating func clearHighlyRated() {self._highlyRated = nil}

  /// Populate only from text explicitly associated with the seller or from the
  /// seller profile page. The item's listing_location is not seller_location.
  public var sellerLocation: Openmarket_Api_V1_FacebookMarketplacePlaceObservation {
    get {_sellerLocation ?? Openmarket_Api_V1_FacebookMarketplacePlaceObservation()}
    set {_sellerLocation = newValue}
  }
  /// Returns true if `sellerLocation` has been explicitly set.
  public var hasSellerLocation: Bool {self._sellerLocation != nil}
  /// Clears the value of `sellerLocation`. Subsequent reads from it will return its default value.
  public mutating func clearSellerLocation() {self._sellerLocation = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _facebookProfileID: String? = nil
  fileprivate var _displayName: String? = nil
  fileprivate var _joinedText: String? = nil
  fileprivate var _joinedYear: Int32? = nil
  fileprivate var _rating: Double? = nil
  fileprivate var _ratingCount: Int32? = nil
  fileprivate var _highlyRated: Bool? = nil
  fileprivate var _sellerLocation: Openmarket_Api_V1_FacebookMarketplacePlaceObservation? = nil
}

/// Facebook publishes these as three independent booleans. Keep the source
/// facts together and derive one canonical availability value on the server;
/// is_live is not that value because it has been observed true on sold cards.
public nonisolated struct Openmarket_Api_V1_FacebookMarketplaceAvailabilityObservation: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var sold: Bool {
    get {_sold ?? false}
    set {_sold = newValue}
  }
  /// Returns true if `sold` has been explicitly set.
  public var hasSold: Bool {self._sold != nil}
  /// Clears the value of `sold`. Subsequent reads from it will return its default value.
  public mutating func clearSold() {self._sold = nil}

  public var live: Bool {
    get {_live ?? false}
    set {_live = newValue}
  }
  /// Returns true if `live` has been explicitly set.
  public var hasLive: Bool {self._live != nil}
  /// Clears the value of `live`. Subsequent reads from it will return its default value.
  public mutating func clearLive() {self._live = nil}

  public var pending: Bool {
    get {_pending ?? false}
    set {_pending = newValue}
  }
  /// Returns true if `pending` has been explicitly set.
  public var hasPending: Bool {self._pending != nil}
  /// Clears the value of `pending`. Subsequent reads from it will return its default value.
  public mutating func clearPending() {self._pending = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _sold: Bool? = nil
  fileprivate var _live: Bool? = nil
  fileprivate var _pending: Bool? = nil
}

/// One listing as a search/discover surface observed it. The first desktop
/// search page normally uses EMBEDDED_GRAPHQL and can carry listed_at; cards
/// inserted by infinite scroll use RENDERED_DOM and cannot.
public nonisolated struct Openmarket_Api_V1_FacebookMarketplaceSearchListingObservation: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var context: Openmarket_Api_V1_FacebookMarketplaceObservationContext {
    get {_storage._context ?? Openmarket_Api_V1_FacebookMarketplaceObservationContext()}
    set {_uniqueStorage()._context = newValue}
  }
  /// Returns true if `context` has been explicitly set.
  public var hasContext: Bool {_storage._context != nil}
  /// Clears the value of `context`. Subsequent reads from it will return its default value.
  public mutating func clearContext() {_uniqueStorage()._context = nil}

  public var key: Openmarket_Api_V1_FacebookListingKey {
    get {_storage._key ?? Openmarket_Api_V1_FacebookListingKey()}
    set {_uniqueStorage()._key = newValue}
  }
  /// Returns true if `key` has been explicitly set.
  public var hasKey: Bool {_storage._key != nil}
  /// Clears the value of `key`. Subsequent reads from it will return its default value.
  public mutating func clearKey() {_uniqueStorage()._key = nil}

  public var title: String {
    get {_storage._title ?? String()}
    set {_uniqueStorage()._title = newValue}
  }
  /// Returns true if `title` has been explicitly set.
  public var hasTitle: Bool {_storage._title != nil}
  /// Clears the value of `title`. Subsequent reads from it will return its default value.
  public mutating func clearTitle() {_uniqueStorage()._title = nil}

  public var price: Openmarket_Api_V1_FacebookMarketplacePriceObservation {
    get {_storage._price ?? Openmarket_Api_V1_FacebookMarketplacePriceObservation()}
    set {_uniqueStorage()._price = newValue}
  }
  /// Returns true if `price` has been explicitly set.
  public var hasPrice: Bool {_storage._price != nil}
  /// Clears the value of `price`. Subsequent reads from it will return its default value.
  public mutating func clearPrice() {_uniqueStorage()._price = nil}

  public var listingLocation: Openmarket_Api_V1_FacebookMarketplacePlaceObservation {
    get {_storage._listingLocation ?? Openmarket_Api_V1_FacebookMarketplacePlaceObservation()}
    set {_uniqueStorage()._listingLocation = newValue}
  }
  /// Returns true if `listingLocation` has been explicitly set.
  public var hasListingLocation: Bool {_storage._listingLocation != nil}
  /// Clears the value of `listingLocation`. Subsequent reads from it will return its default value.
  public mutating func clearListingLocation() {_uniqueStorage()._listingLocation = nil}

  public var condition: String {
    get {_storage._condition ?? String()}
    set {_uniqueStorage()._condition = newValue}
  }
  /// Returns true if `condition` has been explicitly set.
  public var hasCondition: Bool {_storage._condition != nil}
  /// Clears the value of `condition`. Subsequent reads from it will return its default value.
  public mutating func clearCondition() {_uniqueStorage()._condition = nil}

  public var primaryPhoto: Openmarket_Api_V1_FacebookMarketplaceMediaObservation {
    get {_storage._primaryPhoto ?? Openmarket_Api_V1_FacebookMarketplaceMediaObservation()}
    set {_uniqueStorage()._primaryPhoto = newValue}
  }
  /// Returns true if `primaryPhoto` has been explicitly set.
  public var hasPrimaryPhoto: Bool {_storage._primaryPhoto != nil}
  /// Clears the value of `primaryPhoto`. Subsequent reads from it will return its default value.
  public mutating func clearPrimaryPhoto() {_uniqueStorage()._primaryPhoto = nil}

  /// Exact Facebook creation_time, named for its domain meaning rather than the
  /// source JSON spelling. Database row creation remains created_at.
  public var listedAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {_storage._listedAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._listedAt = newValue}
  }
  /// Returns true if `listedAt` has been explicitly set.
  public var hasListedAt: Bool {_storage._listedAt != nil}
  /// Clears the value of `listedAt`. Subsequent reads from it will return its default value.
  public mutating func clearListedAt() {_uniqueStorage()._listedAt = nil}

  public var deliveryTypes: [String] {
    get {_storage._deliveryTypes}
    set {_uniqueStorage()._deliveryTypes = newValue}
  }

  public var availability: Openmarket_Api_V1_FacebookMarketplaceAvailabilityObservation {
    get {_storage._availability ?? Openmarket_Api_V1_FacebookMarketplaceAvailabilityObservation()}
    set {_uniqueStorage()._availability = newValue}
  }
  /// Returns true if `availability` has been explicitly set.
  public var hasAvailability: Bool {_storage._availability != nil}
  /// Clears the value of `availability`. Subsequent reads from it will return its default value.
  public mutating func clearAvailability() {_uniqueStorage()._availability = nil}

  public var facebookCategoryID: String {
    get {_storage._facebookCategoryID ?? String()}
    set {_uniqueStorage()._facebookCategoryID = newValue}
  }
  /// Returns true if `facebookCategoryID` has been explicitly set.
  public var hasFacebookCategoryID: Bool {_storage._facebookCategoryID != nil}
  /// Clears the value of `facebookCategoryID`. Subsequent reads from it will return its default value.
  public mutating func clearFacebookCategoryID() {_uniqueStorage()._facebookCategoryID = nil}

  public var createdWithSellerApp: Bool {
    get {_storage._createdWithSellerApp ?? false}
    set {_uniqueStorage()._createdWithSellerApp = newValue}
  }
  /// Returns true if `createdWithSellerApp` has been explicitly set.
  public var hasCreatedWithSellerApp: Bool {_storage._createdWithSellerApp != nil}
  /// Clears the value of `createdWithSellerApp`. Subsequent reads from it will return its default value.
  public mutating func clearCreatedWithSellerApp() {_uniqueStorage()._createdWithSellerApp = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// One listing as its item page observed it. Seller presence is interpreted
/// together with context.facebook_authentication_state and
/// seller.section_status.
public nonisolated struct Openmarket_Api_V1_FacebookMarketplaceListingDetailObservation: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var context: Openmarket_Api_V1_FacebookMarketplaceObservationContext {
    get {_storage._context ?? Openmarket_Api_V1_FacebookMarketplaceObservationContext()}
    set {_uniqueStorage()._context = newValue}
  }
  /// Returns true if `context` has been explicitly set.
  public var hasContext: Bool {_storage._context != nil}
  /// Clears the value of `context`. Subsequent reads from it will return its default value.
  public mutating func clearContext() {_uniqueStorage()._context = nil}

  public var key: Openmarket_Api_V1_FacebookListingKey {
    get {_storage._key ?? Openmarket_Api_V1_FacebookListingKey()}
    set {_uniqueStorage()._key = newValue}
  }
  /// Returns true if `key` has been explicitly set.
  public var hasKey: Bool {_storage._key != nil}
  /// Clears the value of `key`. Subsequent reads from it will return its default value.
  public mutating func clearKey() {_uniqueStorage()._key = nil}

  public var title: String {
    get {_storage._title ?? String()}
    set {_uniqueStorage()._title = newValue}
  }
  /// Returns true if `title` has been explicitly set.
  public var hasTitle: Bool {_storage._title != nil}
  /// Clears the value of `title`. Subsequent reads from it will return its default value.
  public mutating func clearTitle() {_uniqueStorage()._title = nil}

  public var description_p: String {
    get {_storage._description_p ?? String()}
    set {_uniqueStorage()._description_p = newValue}
  }
  /// Returns true if `description_p` has been explicitly set.
  public var hasDescription_p: Bool {_storage._description_p != nil}
  /// Clears the value of `description_p`. Subsequent reads from it will return its default value.
  public mutating func clearDescription_p() {_uniqueStorage()._description_p = nil}

  public var price: Openmarket_Api_V1_FacebookMarketplacePriceObservation {
    get {_storage._price ?? Openmarket_Api_V1_FacebookMarketplacePriceObservation()}
    set {_uniqueStorage()._price = newValue}
  }
  /// Returns true if `price` has been explicitly set.
  public var hasPrice: Bool {_storage._price != nil}
  /// Clears the value of `price`. Subsequent reads from it will return its default value.
  public mutating func clearPrice() {_uniqueStorage()._price = nil}

  public var listingLocation: Openmarket_Api_V1_FacebookMarketplacePlaceObservation {
    get {_storage._listingLocation ?? Openmarket_Api_V1_FacebookMarketplacePlaceObservation()}
    set {_uniqueStorage()._listingLocation = newValue}
  }
  /// Returns true if `listingLocation` has been explicitly set.
  public var hasListingLocation: Bool {_storage._listingLocation != nil}
  /// Clears the value of `listingLocation`. Subsequent reads from it will return its default value.
  public mutating func clearListingLocation() {_uniqueStorage()._listingLocation = nil}

  public var condition: String {
    get {_storage._condition ?? String()}
    set {_uniqueStorage()._condition = newValue}
  }
  /// Returns true if `condition` has been explicitly set.
  public var hasCondition: Bool {_storage._condition != nil}
  /// Clears the value of `condition`. Subsequent reads from it will return its default value.
  public mutating func clearCondition() {_uniqueStorage()._condition = nil}

  public var media: [Openmarket_Api_V1_FacebookMarketplaceMediaObservation] {
    get {_storage._media}
    set {_uniqueStorage()._media = newValue}
  }

  /// Coarse rendered value such as "Listed 3 weeks ago". Do not convert this to
  /// an exact instant without also storing the derivation precision.
  public var listedAtText: String {
    get {_storage._listedAtText ?? String()}
    set {_uniqueStorage()._listedAtText = newValue}
  }
  /// Returns true if `listedAtText` has been explicitly set.
  public var hasListedAtText: Bool {_storage._listedAtText != nil}
  /// Clears the value of `listedAtText`. Subsequent reads from it will return its default value.
  public mutating func clearListedAtText() {_uniqueStorage()._listedAtText = nil}

  public var deliveryTypes: [String] {
    get {_storage._deliveryTypes}
    set {_uniqueStorage()._deliveryTypes = newValue}
  }

  public var availability: Openmarket_Api_V1_FacebookMarketplaceAvailabilityObservation {
    get {_storage._availability ?? Openmarket_Api_V1_FacebookMarketplaceAvailabilityObservation()}
    set {_uniqueStorage()._availability = newValue}
  }
  /// Returns true if `availability` has been explicitly set.
  public var hasAvailability: Bool {_storage._availability != nil}
  /// Clears the value of `availability`. Subsequent reads from it will return its default value.
  public mutating func clearAvailability() {_uniqueStorage()._availability = nil}

  public var seller: Openmarket_Api_V1_FacebookMarketplaceSellerObservation {
    get {_storage._seller ?? Openmarket_Api_V1_FacebookMarketplaceSellerObservation()}
    set {_uniqueStorage()._seller = newValue}
  }
  /// Returns true if `seller` has been explicitly set.
  public var hasSeller: Bool {_storage._seller != nil}
  /// Clears the value of `seller`. Subsequent reads from it will return its default value.
  public mutating func clearSeller() {_uniqueStorage()._seller = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public nonisolated struct Openmarket_Api_V1_FacebookMarketplaceListingObservation: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var observation: Openmarket_Api_V1_FacebookMarketplaceListingObservation.OneOf_Observation? = nil

  public var search: Openmarket_Api_V1_FacebookMarketplaceSearchListingObservation {
    get {
      if case .search(let v)? = observation {return v}
      return Openmarket_Api_V1_FacebookMarketplaceSearchListingObservation()
    }
    set {observation = .search(newValue)}
  }

  public var detail: Openmarket_Api_V1_FacebookMarketplaceListingDetailObservation {
    get {
      if case .detail(let v)? = observation {return v}
      return Openmarket_Api_V1_FacebookMarketplaceListingDetailObservation()
    }
    set {observation = .detail(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum OneOf_Observation: Equatable, Sendable {
    case search(Openmarket_Api_V1_FacebookMarketplaceSearchListingObservation)
    case detail(Openmarket_Api_V1_FacebookMarketplaceListingDetailObservation)

  }

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "openmarket.api.v1"

nonisolated extension Openmarket_Api_V1_FacebookMarketplaceBrowserVariant: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0FACEBOOK_MARKETPLACE_BROWSER_VARIANT_UNSPECIFIED\0\u{1}FACEBOOK_MARKETPLACE_BROWSER_VARIANT_DESKTOP\0\u{1}FACEBOOK_MARKETPLACE_BROWSER_VARIANT_MOBILE\0")
}

nonisolated extension Openmarket_Api_V1_FacebookMarketplacePageRoute: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0FACEBOOK_MARKETPLACE_PAGE_ROUTE_UNSPECIFIED\0\u{1}FACEBOOK_MARKETPLACE_PAGE_ROUTE_SEARCH\0\u{1}FACEBOOK_MARKETPLACE_PAGE_ROUTE_DISCOVER\0\u{1}FACEBOOK_MARKETPLACE_PAGE_ROUTE_ITEM\0\u{1}FACEBOOK_MARKETPLACE_PAGE_ROUTE_SELLER_PROFILE\0")
}

nonisolated extension Openmarket_Api_V1_FacebookMarketplaceExtractionMethod: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0FACEBOOK_MARKETPLACE_EXTRACTION_METHOD_UNSPECIFIED\0\u{1}FACEBOOK_MARKETPLACE_EXTRACTION_METHOD_EMBEDDED_GRAPHQL\0\u{1}FACEBOOK_MARKETPLACE_EXTRACTION_METHOD_RENDERED_DOM\0\u{1}FACEBOOK_MARKETPLACE_EXTRACTION_METHOD_HYBRID\0")
}

nonisolated extension Openmarket_Api_V1_FacebookAuthenticationState: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0FACEBOOK_AUTHENTICATION_STATE_UNSPECIFIED\0\u{1}FACEBOOK_AUTHENTICATION_STATE_SIGNED_OUT\0\u{1}FACEBOOK_AUTHENTICATION_STATE_SIGNED_IN\0")
}

nonisolated extension Openmarket_Api_V1_FacebookMarketplaceSellerSectionStatus: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0FACEBOOK_MARKETPLACE_SELLER_SECTION_STATUS_UNSPECIFIED\0\u{1}FACEBOOK_MARKETPLACE_SELLER_SECTION_STATUS_UNAVAILABLE\0\u{1}FACEBOOK_MARKETPLACE_SELLER_SECTION_STATUS_NOT_OBSERVED\0\u{1}FACEBOOK_MARKETPLACE_SELLER_SECTION_STATUS_OBSERVED\0")
}

nonisolated extension Openmarket_Api_V1_FacebookMarketplaceObservationContext: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FacebookMarketplaceObservationContext"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}browser_variant\0\u{3}page_route\0\u{3}extraction_method\0\u{3}facebook_authentication_state\0\u{3}observed_at\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.browserVariant) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.pageRoute) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.extractionMethod) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self.facebookAuthenticationState) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._observedAt) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.browserVariant != .unspecified {
      try visitor.visitSingularEnumField(value: self.browserVariant, fieldNumber: 1)
    }
    if self.pageRoute != .unspecified {
      try visitor.visitSingularEnumField(value: self.pageRoute, fieldNumber: 2)
    }
    if self.extractionMethod != .unspecified {
      try visitor.visitSingularEnumField(value: self.extractionMethod, fieldNumber: 3)
    }
    if self.facebookAuthenticationState != .unspecified {
      try visitor.visitSingularEnumField(value: self.facebookAuthenticationState, fieldNumber: 4)
    }
    try { if let v = self._observedAt {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Openmarket_Api_V1_FacebookMarketplaceObservationContext, rhs: Openmarket_Api_V1_FacebookMarketplaceObservationContext) -> Bool {
    if lhs.browserVariant != rhs.browserVariant {return false}
    if lhs.pageRoute != rhs.pageRoute {return false}
    if lhs.extractionMethod != rhs.extractionMethod {return false}
    if lhs.facebookAuthenticationState != rhs.facebookAuthenticationState {return false}
    if lhs._observedAt != rhs._observedAt {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Openmarket_Api_V1_FacebookListingKey: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FacebookListingKey"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}facebook_listing_id\0\u{3}cover_photo_fbid\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._facebookListingID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._coverPhotoFbid) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._facebookListingID {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._coverPhotoFbid {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Openmarket_Api_V1_FacebookListingKey, rhs: Openmarket_Api_V1_FacebookListingKey) -> Bool {
    if lhs._facebookListingID != rhs._facebookListingID {return false}
    if lhs._coverPhotoFbid != rhs._coverPhotoFbid {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Openmarket_Api_V1_FacebookMarketplacePriceObservation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FacebookMarketplacePriceObservation"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}amount_decimal\0\u{3}formatted_amount\0\u{3}previous_amount_decimal\0\u{3}previous_formatted_amount\0\u{3}currency_code\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._amountDecimal) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._formattedAmount) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._previousAmountDecimal) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._previousFormattedAmount) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._currencyCode) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._amountDecimal {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._formattedAmount {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._previousAmountDecimal {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._previousFormattedAmount {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._currencyCode {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Openmarket_Api_V1_FacebookMarketplacePriceObservation, rhs: Openmarket_Api_V1_FacebookMarketplacePriceObservation) -> Bool {
    if lhs._amountDecimal != rhs._amountDecimal {return false}
    if lhs._formattedAmount != rhs._formattedAmount {return false}
    if lhs._previousAmountDecimal != rhs._previousAmountDecimal {return false}
    if lhs._previousFormattedAmount != rhs._previousFormattedAmount {return false}
    if lhs._currencyCode != rhs._currencyCode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Openmarket_Api_V1_FacebookMarketplacePlaceObservation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FacebookMarketplacePlaceObservation"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}display_text\0\u{1}city\0\u{1}region\0\u{1}country\0\u{3}facebook_place_id\0\u{1}latitude\0\u{1}longitude\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._displayText) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._city) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._region) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._country) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._facebookPlaceID) }()
      case 6: try { try decoder.decodeSingularDoubleField(value: &self._latitude) }()
      case 7: try { try decoder.decodeSingularDoubleField(value: &self._longitude) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._displayText {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._city {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._region {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._country {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._facebookPlaceID {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._latitude {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._longitude {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 7)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Openmarket_Api_V1_FacebookMarketplacePlaceObservation, rhs: Openmarket_Api_V1_FacebookMarketplacePlaceObservation) -> Bool {
    if lhs._displayText != rhs._displayText {return false}
    if lhs._city != rhs._city {return false}
    if lhs._region != rhs._region {return false}
    if lhs._country != rhs._country {return false}
    if lhs._facebookPlaceID != rhs._facebookPlaceID {return false}
    if lhs._latitude != rhs._latitude {return false}
    if lhs._longitude != rhs._longitude {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Openmarket_Api_V1_FacebookMarketplaceMediaObservation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FacebookMarketplaceMediaObservation"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}facebook_photo_id\0\u{1}url\0\u{1}position\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._facebookPhotoID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._url) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self._position) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._facebookPhotoID {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._url {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._position {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Openmarket_Api_V1_FacebookMarketplaceMediaObservation, rhs: Openmarket_Api_V1_FacebookMarketplaceMediaObservation) -> Bool {
    if lhs._facebookPhotoID != rhs._facebookPhotoID {return false}
    if lhs._url != rhs._url {return false}
    if lhs._position != rhs._position {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Openmarket_Api_V1_FacebookMarketplaceSellerObservation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FacebookMarketplaceSellerObservation"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}section_status\0\u{3}facebook_profile_id\0\u{3}display_name\0\u{3}joined_text\0\u{3}joined_year\0\u{1}rating\0\u{3}rating_count\0\u{3}highly_rated\0\u{3}seller_location\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.sectionStatus) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._facebookProfileID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._displayName) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._joinedText) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self._joinedYear) }()
      case 6: try { try decoder.decodeSingularDoubleField(value: &self._rating) }()
      case 7: try { try decoder.decodeSingularInt32Field(value: &self._ratingCount) }()
      case 8: try { try decoder.decodeSingularBoolField(value: &self._highlyRated) }()
      case 9: try { try decoder.decodeSingularMessageField(value: &self._sellerLocation) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.sectionStatus != .unspecified {
      try visitor.visitSingularEnumField(value: self.sectionStatus, fieldNumber: 1)
    }
    try { if let v = self._facebookProfileID {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._displayName {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._joinedText {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._joinedYear {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._rating {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._ratingCount {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._highlyRated {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._sellerLocation {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Openmarket_Api_V1_FacebookMarketplaceSellerObservation, rhs: Openmarket_Api_V1_FacebookMarketplaceSellerObservation) -> Bool {
    if lhs.sectionStatus != rhs.sectionStatus {return false}
    if lhs._facebookProfileID != rhs._facebookProfileID {return false}
    if lhs._displayName != rhs._displayName {return false}
    if lhs._joinedText != rhs._joinedText {return false}
    if lhs._joinedYear != rhs._joinedYear {return false}
    if lhs._rating != rhs._rating {return false}
    if lhs._ratingCount != rhs._ratingCount {return false}
    if lhs._highlyRated != rhs._highlyRated {return false}
    if lhs._sellerLocation != rhs._sellerLocation {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Openmarket_Api_V1_FacebookMarketplaceAvailabilityObservation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FacebookMarketplaceAvailabilityObservation"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}sold\0\u{1}live\0\u{1}pending\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self._sold) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self._live) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self._pending) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._sold {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._live {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._pending {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Openmarket_Api_V1_FacebookMarketplaceAvailabilityObservation, rhs: Openmarket_Api_V1_FacebookMarketplaceAvailabilityObservation) -> Bool {
    if lhs._sold != rhs._sold {return false}
    if lhs._live != rhs._live {return false}
    if lhs._pending != rhs._pending {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Openmarket_Api_V1_FacebookMarketplaceSearchListingObservation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FacebookMarketplaceSearchListingObservation"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}context\0\u{1}key\0\u{1}title\0\u{1}price\0\u{3}listing_location\0\u{1}condition\0\u{3}primary_photo\0\u{3}listed_at\0\u{3}delivery_types\0\u{1}availability\0\u{3}facebook_category_id\0\u{3}created_with_seller_app\0")

  fileprivate class _StorageClass {
    var _context: Openmarket_Api_V1_FacebookMarketplaceObservationContext? = nil
    var _key: Openmarket_Api_V1_FacebookListingKey? = nil
    var _title: String? = nil
    var _price: Openmarket_Api_V1_FacebookMarketplacePriceObservation? = nil
    var _listingLocation: Openmarket_Api_V1_FacebookMarketplacePlaceObservation? = nil
    var _condition: String? = nil
    var _primaryPhoto: Openmarket_Api_V1_FacebookMarketplaceMediaObservation? = nil
    var _listedAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _deliveryTypes: [String] = []
    var _availability: Openmarket_Api_V1_FacebookMarketplaceAvailabilityObservation? = nil
    var _facebookCategoryID: String? = nil
    var _createdWithSellerApp: Bool? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _context = source._context
      _key = source._key
      _title = source._title
      _price = source._price
      _listingLocation = source._listingLocation
      _condition = source._condition
      _primaryPhoto = source._primaryPhoto
      _listedAt = source._listedAt
      _deliveryTypes = source._deliveryTypes
      _availability = source._availability
      _facebookCategoryID = source._facebookCategoryID
      _createdWithSellerApp = source._createdWithSellerApp
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._context) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._key) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._title) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._price) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._listingLocation) }()
        case 6: try { try decoder.decodeSingularStringField(value: &_storage._condition) }()
        case 7: try { try decoder.decodeSingularMessageField(value: &_storage._primaryPhoto) }()
        case 8: try { try decoder.decodeSingularMessageField(value: &_storage._listedAt) }()
        case 9: try { try decoder.decodeRepeatedStringField(value: &_storage._deliveryTypes) }()
        case 10: try { try decoder.decodeSingularMessageField(value: &_storage._availability) }()
        case 11: try { try decoder.decodeSingularStringField(value: &_storage._facebookCategoryID) }()
        case 12: try { try decoder.decodeSingularBoolField(value: &_storage._createdWithSellerApp) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._context {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._key {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._title {
        try visitor.visitSingularStringField(value: v, fieldNumber: 3)
      } }()
      try { if let v = _storage._price {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      } }()
      try { if let v = _storage._listingLocation {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
      try { if let v = _storage._condition {
        try visitor.visitSingularStringField(value: v, fieldNumber: 6)
      } }()
      try { if let v = _storage._primaryPhoto {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
      } }()
      try { if let v = _storage._listedAt {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
      } }()
      if !_storage._deliveryTypes.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._deliveryTypes, fieldNumber: 9)
      }
      try { if let v = _storage._availability {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
      } }()
      try { if let v = _storage._facebookCategoryID {
        try visitor.visitSingularStringField(value: v, fieldNumber: 11)
      } }()
      try { if let v = _storage._createdWithSellerApp {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 12)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Openmarket_Api_V1_FacebookMarketplaceSearchListingObservation, rhs: Openmarket_Api_V1_FacebookMarketplaceSearchListingObservation) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._context != rhs_storage._context {return false}
        if _storage._key != rhs_storage._key {return false}
        if _storage._title != rhs_storage._title {return false}
        if _storage._price != rhs_storage._price {return false}
        if _storage._listingLocation != rhs_storage._listingLocation {return false}
        if _storage._condition != rhs_storage._condition {return false}
        if _storage._primaryPhoto != rhs_storage._primaryPhoto {return false}
        if _storage._listedAt != rhs_storage._listedAt {return false}
        if _storage._deliveryTypes != rhs_storage._deliveryTypes {return false}
        if _storage._availability != rhs_storage._availability {return false}
        if _storage._facebookCategoryID != rhs_storage._facebookCategoryID {return false}
        if _storage._createdWithSellerApp != rhs_storage._createdWithSellerApp {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Openmarket_Api_V1_FacebookMarketplaceListingDetailObservation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FacebookMarketplaceListingDetailObservation"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}context\0\u{1}key\0\u{1}title\0\u{1}description\0\u{1}price\0\u{3}listing_location\0\u{1}condition\0\u{1}media\0\u{3}listed_at_text\0\u{3}delivery_types\0\u{1}availability\0\u{1}seller\0")

  fileprivate class _StorageClass {
    var _context: Openmarket_Api_V1_FacebookMarketplaceObservationContext? = nil
    var _key: Openmarket_Api_V1_FacebookListingKey? = nil
    var _title: String? = nil
    var _description_p: String? = nil
    var _price: Openmarket_Api_V1_FacebookMarketplacePriceObservation? = nil
    var _listingLocation: Openmarket_Api_V1_FacebookMarketplacePlaceObservation? = nil
    var _condition: String? = nil
    var _media: [Openmarket_Api_V1_FacebookMarketplaceMediaObservation] = []
    var _listedAtText: String? = nil
    var _deliveryTypes: [String] = []
    var _availability: Openmarket_Api_V1_FacebookMarketplaceAvailabilityObservation? = nil
    var _seller: Openmarket_Api_V1_FacebookMarketplaceSellerObservation? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _context = source._context
      _key = source._key
      _title = source._title
      _description_p = source._description_p
      _price = source._price
      _listingLocation = source._listingLocation
      _condition = source._condition
      _media = source._media
      _listedAtText = source._listedAtText
      _deliveryTypes = source._deliveryTypes
      _availability = source._availability
      _seller = source._seller
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._context) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._key) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._title) }()
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._description_p) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._price) }()
        case 6: try { try decoder.decodeSingularMessageField(value: &_storage._listingLocation) }()
        case 7: try { try decoder.decodeSingularStringField(value: &_storage._condition) }()
        case 8: try { try decoder.decodeRepeatedMessageField(value: &_storage._media) }()
        case 9: try { try decoder.decodeSingularStringField(value: &_storage._listedAtText) }()
        case 10: try { try decoder.decodeRepeatedStringField(value: &_storage._deliveryTypes) }()
        case 11: try { try decoder.decodeSingularMessageField(value: &_storage._availability) }()
        case 12: try { try decoder.decodeSingularMessageField(value: &_storage._seller) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._context {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._key {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._title {
        try visitor.visitSingularStringField(value: v, fieldNumber: 3)
      } }()
      try { if let v = _storage._description_p {
        try visitor.visitSingularStringField(value: v, fieldNumber: 4)
      } }()
      try { if let v = _storage._price {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
      try { if let v = _storage._listingLocation {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      } }()
      try { if let v = _storage._condition {
        try visitor.visitSingularStringField(value: v, fieldNumber: 7)
      } }()
      if !_storage._media.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._media, fieldNumber: 8)
      }
      try { if let v = _storage._listedAtText {
        try visitor.visitSingularStringField(value: v, fieldNumber: 9)
      } }()
      if !_storage._deliveryTypes.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._deliveryTypes, fieldNumber: 10)
      }
      try { if let v = _storage._availability {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
      } }()
      try { if let v = _storage._seller {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Openmarket_Api_V1_FacebookMarketplaceListingDetailObservation, rhs: Openmarket_Api_V1_FacebookMarketplaceListingDetailObservation) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._context != rhs_storage._context {return false}
        if _storage._key != rhs_storage._key {return false}
        if _storage._title != rhs_storage._title {return false}
        if _storage._description_p != rhs_storage._description_p {return false}
        if _storage._price != rhs_storage._price {return false}
        if _storage._listingLocation != rhs_storage._listingLocation {return false}
        if _storage._condition != rhs_storage._condition {return false}
        if _storage._media != rhs_storage._media {return false}
        if _storage._listedAtText != rhs_storage._listedAtText {return false}
        if _storage._deliveryTypes != rhs_storage._deliveryTypes {return false}
        if _storage._availability != rhs_storage._availability {return false}
        if _storage._seller != rhs_storage._seller {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Openmarket_Api_V1_FacebookMarketplaceListingObservation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FacebookMarketplaceListingObservation"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}search\0\u{1}detail\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Openmarket_Api_V1_FacebookMarketplaceSearchListingObservation?
        var hadOneofValue = false
        if let current = self.observation {
          hadOneofValue = true
          if case .search(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.observation = .search(v)
        }
      }()
      case 2: try {
        var v: Openmarket_Api_V1_FacebookMarketplaceListingDetailObservation?
        var hadOneofValue = false
        if let current = self.observation {
          hadOneofValue = true
          if case .detail(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.observation = .detail(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.observation {
    case .search?: try {
      guard case .search(let v)? = self.observation else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .detail?: try {
      guard case .detail(let v)? = self.observation else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Openmarket_Api_V1_FacebookMarketplaceListingObservation, rhs: Openmarket_Api_V1_FacebookMarketplaceListingObservation) -> Bool {
    if lhs.observation != rhs.observation {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
