// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: openmarket/api/v1/observation_service.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Why one observation in the batch was refused. A refusal is per card: a field
/// that is present and does not parse fails the whole card rather than being
/// nulled, because a null is indistinguishable from "this surface did not tell
/// us" (docs/ingest-attribution.md §3.1).
public nonisolated enum Openmarket_Api_V1_ObservationRejectionReason: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0

  /// A field arrived in a shape the parser does not model.
  case malformedField // = 1

  /// Well-formed and outside its envelope: a 1970 timestamp, a price of ten
  /// million, a coordinate in the wrong hemisphere (§3.2).
  case implausibleValue // = 2

  /// Two fields of one observation contradict each other, such as sold and
  /// pending both true.
  case contradictoryFields // = 3

  /// The same key appeared twice in one batch, or every card in the batch shares
  /// one key. Both are extractor collisions rather than real duplicates.
  case keyCollision // = 4

  /// The observation's shape does not match the batch's route: a detail
  /// observation in a search batch, or the reverse.
  case routeMismatch // = 5

  /// The key resolves to a native listing, which no Facebook observation may
  /// touch (docs/data-model.md §3).
  case originConflict // = 6

  /// One alias claims a listing another alias has already claimed.
  case aliasConflict // = 7

  /// Nothing was wrong with this card. The circuit breaker is open for the
  /// surface it came from, so the whole batch was stored for diagnosis instead
  /// of merged (§3.3).
  case sourceSuspended // = 8
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .malformedField
    case 2: self = .implausibleValue
    case 3: self = .contradictoryFields
    case 4: self = .keyCollision
    case 5: self = .routeMismatch
    case 6: self = .originConflict
    case 7: self = .aliasConflict
    case 8: self = .sourceSuspended
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .malformedField: return 1
    case .implausibleValue: return 2
    case .contradictoryFields: return 3
    case .keyCollision: return 4
    case .routeMismatch: return 5
    case .originConflict: return 6
    case .aliasConflict: return 7
    case .sourceSuspended: return 8
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Openmarket_Api_V1_ObservationRejectionReason] = [
    .unspecified,
    .malformedField,
    .implausibleValue,
    .contradictoryFields,
    .keyCollision,
    .routeMismatch,
    .originConflict,
    .aliasConflict,
    .sourceSuspended,
  ]

}

/// What the client's extractor saw, as distinct from what it managed to parse.
///
/// Without this, an extractor that drops every card on a page and a page with
/// nothing on it produce the identical server-side record. That is the failure
/// this whole ingest path is built to make loud, so the counts travel with the
/// batch even though nothing merges them into a listing.
public nonisolated struct Openmarket_Api_V1_ClientExtractionCounts: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Candidate cards the extractor found before parsing. Never fewer than the
  /// number of observations in the request.
  public var cardsSeen: Int32 = 0

  /// Deduplicated reason tokens for what the client dropped, in the vocabulary
  /// its own logs use (docs/parsing-conventions.md §1). Free-form on purpose:
  /// an unrecognised reason is still legible, where an enum would collapse it.
  public var dropReasons: [String] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Openmarket_Api_V1_SubmitObservationsRequest: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var context: Openmarket_Api_V1_FacebookMarketplaceObservationContext {
    get {_storage._context ?? Openmarket_Api_V1_FacebookMarketplaceObservationContext()}
    set {_uniqueStorage()._context = newValue}
  }
  /// Returns true if `context` has been explicitly set.
  public var hasContext: Bool {_storage._context != nil}
  /// Clears the value of `context`. Subsequent reads from it will return its default value.
  public mutating func clearContext() {_uniqueStorage()._context = nil}

  /// Search and discover routes only. Its absence on those routes means the
  /// capture cannot say what query produced it, which costs the inference in
  /// docs/ingest-attribution.md §2.2 and nothing else.
  public var query: Openmarket_Api_V1_FacebookMarketplaceQueryContext {
    get {_storage._query ?? Openmarket_Api_V1_FacebookMarketplaceQueryContext()}
    set {_uniqueStorage()._query = newValue}
  }
  /// Returns true if `query` has been explicitly set.
  public var hasQuery: Bool {_storage._query != nil}
  /// Clears the value of `query`. Subsequent reads from it will return its default value.
  public mutating func clearQuery() {_uniqueStorage()._query = nil}

  /// Identifies the parser, not the app. Debug builds pin the app build to 1
  /// (docs/data-model.md §2), so the app version alone cannot attribute a
  /// regression to the code that caused it.
  public var extractorRevision: String {
    get {_storage._extractorRevision}
    set {_uniqueStorage()._extractorRevision = newValue}
  }

  public var counts: Openmarket_Api_V1_ClientExtractionCounts {
    get {_storage._counts ?? Openmarket_Api_V1_ClientExtractionCounts()}
    set {_uniqueStorage()._counts = newValue}
  }
  /// Returns true if `counts` has been explicitly set.
  public var hasCounts: Bool {_storage._counts != nil}
  /// Clears the value of `counts`. Subsequent reads from it will return its default value.
  public mutating func clearCounts() {_uniqueStorage()._counts = nil}

  /// Hash of the sorted set of key paths the extractor saw in a structured
  /// payload, values excluded. A fingerprint nobody has seen before, arriving
  /// across many devices at once, is Facebook shipping a change — and it fires
  /// whether or not anything failed to parse (docs/ingest-attribution.md §3.4).
  public var shapeFingerprint: Data {
    get {_storage._shapeFingerprint ?? Data()}
    set {_uniqueStorage()._shapeFingerprint = newValue}
  }
  /// Returns true if `shapeFingerprint` has been explicitly set.
  public var hasShapeFingerprint: Bool {_storage._shapeFingerprint != nil}
  /// Clears the value of `shapeFingerprint`. Subsequent reads from it will return its default value.
  public mutating func clearShapeFingerprint() {_uniqueStorage()._shapeFingerprint = nil}

  public var observations: [Openmarket_Api_V1_FacebookMarketplaceListingObservation] {
    get {_storage._observations}
    set {_uniqueStorage()._observations = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public nonisolated struct Openmarket_Api_V1_ObservationRejection: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Index into the request's observations, so the client can name the card in
  /// its own log without the server echoing any of its content back.
  public var index: Int32 = 0

  public var reason: Openmarket_Api_V1_ObservationRejectionReason = .unspecified

  /// Dotted path of the field that failed, empty when the whole observation did.
  public var fieldPath: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Openmarket_Api_V1_SubmitObservationsResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var batchID: String = String()

  public var accepted: Int32 = 0

  public var quarantined: Int32 = 0

  public var rejections: [Openmarket_Api_V1_ObservationRejection] = []

  /// The circuit breaker is open for this browser variant, page route,
  /// extraction method and extractor revision: the combination's quarantine rate
  /// crossed its threshold, so nothing from it is reaching canonical rows
  /// (docs/ingest-attribution.md §3.3). The batch was stored for diagnosis and
  /// the client should stop submitting from this surface until it updates.
  public var sourceSuspended: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "openmarket.api.v1"

nonisolated extension Openmarket_Api_V1_ObservationRejectionReason: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0OBSERVATION_REJECTION_REASON_UNSPECIFIED\0\u{1}OBSERVATION_REJECTION_REASON_MALFORMED_FIELD\0\u{1}OBSERVATION_REJECTION_REASON_IMPLAUSIBLE_VALUE\0\u{1}OBSERVATION_REJECTION_REASON_CONTRADICTORY_FIELDS\0\u{1}OBSERVATION_REJECTION_REASON_KEY_COLLISION\0\u{1}OBSERVATION_REJECTION_REASON_ROUTE_MISMATCH\0\u{1}OBSERVATION_REJECTION_REASON_ORIGIN_CONFLICT\0\u{1}OBSERVATION_REJECTION_REASON_ALIAS_CONFLICT\0\u{1}OBSERVATION_REJECTION_REASON_SOURCE_SUSPENDED\0")
}

nonisolated extension Openmarket_Api_V1_ClientExtractionCounts: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ClientExtractionCounts"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}cards_seen\0\u{3}drop_reasons\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.cardsSeen) }()
      case 2: try { try decoder.decodeRepeatedStringField(value: &self.dropReasons) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.cardsSeen != 0 {
      try visitor.visitSingularInt32Field(value: self.cardsSeen, fieldNumber: 1)
    }
    if !self.dropReasons.isEmpty {
      try visitor.visitRepeatedStringField(value: self.dropReasons, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Openmarket_Api_V1_ClientExtractionCounts, rhs: Openmarket_Api_V1_ClientExtractionCounts) -> Bool {
    if lhs.cardsSeen != rhs.cardsSeen {return false}
    if lhs.dropReasons != rhs.dropReasons {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Openmarket_Api_V1_SubmitObservationsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SubmitObservationsRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}context\0\u{1}query\0\u{3}extractor_revision\0\u{1}counts\0\u{3}shape_fingerprint\0\u{1}observations\0")

  fileprivate class _StorageClass {
    var _context: Openmarket_Api_V1_FacebookMarketplaceObservationContext? = nil
    var _query: Openmarket_Api_V1_FacebookMarketplaceQueryContext? = nil
    var _extractorRevision: String = String()
    var _counts: Openmarket_Api_V1_ClientExtractionCounts? = nil
    var _shapeFingerprint: Data? = nil
    var _observations: [Openmarket_Api_V1_FacebookMarketplaceListingObservation] = []

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _context = source._context
      _query = source._query
      _extractorRevision = source._extractorRevision
      _counts = source._counts
      _shapeFingerprint = source._shapeFingerprint
      _observations = source._observations
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._context) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._query) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._extractorRevision) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._counts) }()
        case 5: try { try decoder.decodeSingularBytesField(value: &_storage._shapeFingerprint) }()
        case 6: try { try decoder.decodeRepeatedMessageField(value: &_storage._observations) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._context {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._query {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      if !_storage._extractorRevision.isEmpty {
        try visitor.visitSingularStringField(value: _storage._extractorRevision, fieldNumber: 3)
      }
      try { if let v = _storage._counts {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      } }()
      try { if let v = _storage._shapeFingerprint {
        try visitor.visitSingularBytesField(value: v, fieldNumber: 5)
      } }()
      if !_storage._observations.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._observations, fieldNumber: 6)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Openmarket_Api_V1_SubmitObservationsRequest, rhs: Openmarket_Api_V1_SubmitObservationsRequest) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._context != rhs_storage._context {return false}
        if _storage._query != rhs_storage._query {return false}
        if _storage._extractorRevision != rhs_storage._extractorRevision {return false}
        if _storage._counts != rhs_storage._counts {return false}
        if _storage._shapeFingerprint != rhs_storage._shapeFingerprint {return false}
        if _storage._observations != rhs_storage._observations {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Openmarket_Api_V1_ObservationRejection: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ObservationRejection"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}index\0\u{1}reason\0\u{3}field_path\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.index) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.reason) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.fieldPath) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.index != 0 {
      try visitor.visitSingularInt32Field(value: self.index, fieldNumber: 1)
    }
    if self.reason != .unspecified {
      try visitor.visitSingularEnumField(value: self.reason, fieldNumber: 2)
    }
    if !self.fieldPath.isEmpty {
      try visitor.visitSingularStringField(value: self.fieldPath, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Openmarket_Api_V1_ObservationRejection, rhs: Openmarket_Api_V1_ObservationRejection) -> Bool {
    if lhs.index != rhs.index {return false}
    if lhs.reason != rhs.reason {return false}
    if lhs.fieldPath != rhs.fieldPath {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Openmarket_Api_V1_SubmitObservationsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SubmitObservationsResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}batch_id\0\u{1}accepted\0\u{1}quarantined\0\u{1}rejections\0\u{3}source_suspended\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.batchID) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.accepted) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.quarantined) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.rejections) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.sourceSuspended) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.batchID.isEmpty {
      try visitor.visitSingularStringField(value: self.batchID, fieldNumber: 1)
    }
    if self.accepted != 0 {
      try visitor.visitSingularInt32Field(value: self.accepted, fieldNumber: 2)
    }
    if self.quarantined != 0 {
      try visitor.visitSingularInt32Field(value: self.quarantined, fieldNumber: 3)
    }
    if !self.rejections.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.rejections, fieldNumber: 4)
    }
    if self.sourceSuspended != false {
      try visitor.visitSingularBoolField(value: self.sourceSuspended, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Openmarket_Api_V1_SubmitObservationsResponse, rhs: Openmarket_Api_V1_SubmitObservationsResponse) -> Bool {
    if lhs.batchID != rhs.batchID {return false}
    if lhs.accepted != rhs.accepted {return false}
    if lhs.quarantined != rhs.quarantined {return false}
    if lhs.rejections != rhs.rejections {return false}
    if lhs.sourceSuspended != rhs.sourceSuspended {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
