// Code generated by protoc-gen-connect-swift. DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Source: openmarket/api/v1/observation_service.proto
//

import Connect
import Foundation
import SwiftProtobuf

/// Ingest for Facebook Marketplace observations.
///
/// One call is one **batch**: everything one device parsed off one page at one
/// time. Capture context and the extractor that produced it are properties of
/// the page, so they are carried once here rather than on every card
/// (docs/ingest-attribution.md §2).
///
/// The submitting device is taken from the authenticated session and never from
/// the request. What is persisted alongside the batch is not the device but a
/// per-epoch pseudonym derived from it (§4).
public protocol Openmarket_Api_V1_ObservationServiceClientInterface: Sendable {

    @available(iOS 13, *)
    func `submitObservations`(request: Openmarket_Api_V1_SubmitObservationsRequest, headers: Connect.Headers) async -> ResponseMessage<Openmarket_Api_V1_SubmitObservationsResponse>
}

/// Concrete implementation of `Openmarket_Api_V1_ObservationServiceClientInterface`.
public final class Openmarket_Api_V1_ObservationServiceClient: Openmarket_Api_V1_ObservationServiceClientInterface, Sendable {
    private let client: Connect.ProtocolClientInterface

    public init(client: Connect.ProtocolClientInterface) {
        self.client = client
    }

    @available(iOS 13, *)
    public func `submitObservations`(request: Openmarket_Api_V1_SubmitObservationsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Openmarket_Api_V1_SubmitObservationsResponse> {
        return await self.client.unary(path: "/openmarket.api.v1.ObservationService/SubmitObservations", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    public enum Metadata {
        public enum Methods {
            public static let submitObservations = Connect.MethodSpec(name: "SubmitObservations", service: "openmarket.api.v1.ObservationService", type: .unary)
        }
    }
}
