// Code generated by protoc-gen-connect-swift. DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Source: openmarket/api/v1/pricing_service.proto
//

import Connect
import Foundation
import SwiftProtobuf

public protocol Openmarket_Api_V1_PricingServiceClientInterface: Sendable {

    /// The only call that reaches a model.
    @available(iOS 13, *)
    func `identifyItem`(request: Openmarket_Api_V1_IdentifyItemRequest, headers: Connect.Headers) async -> ResponseMessage<Openmarket_Api_V1_IdentifyItemResponse>

    /// Recording, not pricing — see the request.
    @available(iOS 13, *)
    func `completePriceCheck`(request: Openmarket_Api_V1_CompletePriceCheckRequest, headers: Connect.Headers) async -> ResponseMessage<Openmarket_Api_V1_CompletePriceCheckResponse>

    /// The asked question.
    @available(iOS 13, *)
    func `submitPriceCheckFeedback`(request: Openmarket_Api_V1_SubmitPriceCheckFeedbackRequest, headers: Connect.Headers) async -> ResponseMessage<Openmarket_Api_V1_SubmitPriceCheckFeedbackResponse>

    /// The unasked one, and the better of the two. Copying is what somebody does
    /// immediately before pasting into Facebook: it is captured on nearly every
    /// successful run, where a prompt is answered by the minority who feel
    /// strongly enough to stop and tap — which skews negative. Idempotent; the
    /// first price copy keeps the timestamp.
    @available(iOS 13, *)
    func `recordPriceCheckCopy`(request: Openmarket_Api_V1_RecordPriceCheckCopyRequest, headers: Connect.Headers) async -> ResponseMessage<Openmarket_Api_V1_RecordPriceCheckCopyResponse>

    /// Reads the rows back. Costs nothing and calls nothing — the row was written
    /// either way.
    @available(iOS 13, *)
    func `listPriceChecks`(request: Openmarket_Api_V1_ListPriceChecksRequest, headers: Connect.Headers) async -> ResponseMessage<Openmarket_Api_V1_ListPriceChecksResponse>
}

/// Concrete implementation of `Openmarket_Api_V1_PricingServiceClientInterface`.
public final class Openmarket_Api_V1_PricingServiceClient: Openmarket_Api_V1_PricingServiceClientInterface, Sendable {
    private let client: Connect.ProtocolClientInterface

    public init(client: Connect.ProtocolClientInterface) {
        self.client = client
    }

    @available(iOS 13, *)
    public func `identifyItem`(request: Openmarket_Api_V1_IdentifyItemRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Openmarket_Api_V1_IdentifyItemResponse> {
        return await self.client.unary(path: "/openmarket.api.v1.PricingService/IdentifyItem", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `completePriceCheck`(request: Openmarket_Api_V1_CompletePriceCheckRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Openmarket_Api_V1_CompletePriceCheckResponse> {
        return await self.client.unary(path: "/openmarket.api.v1.PricingService/CompletePriceCheck", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `submitPriceCheckFeedback`(request: Openmarket_Api_V1_SubmitPriceCheckFeedbackRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Openmarket_Api_V1_SubmitPriceCheckFeedbackResponse> {
        return await self.client.unary(path: "/openmarket.api.v1.PricingService/SubmitPriceCheckFeedback", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `recordPriceCheckCopy`(request: Openmarket_Api_V1_RecordPriceCheckCopyRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Openmarket_Api_V1_RecordPriceCheckCopyResponse> {
        return await self.client.unary(path: "/openmarket.api.v1.PricingService/RecordPriceCheckCopy", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `listPriceChecks`(request: Openmarket_Api_V1_ListPriceChecksRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Openmarket_Api_V1_ListPriceChecksResponse> {
        return await self.client.unary(path: "/openmarket.api.v1.PricingService/ListPriceChecks", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    public enum Metadata {
        public enum Methods {
            public static let identifyItem = Connect.MethodSpec(name: "IdentifyItem", service: "openmarket.api.v1.PricingService", type: .unary)
            public static let completePriceCheck = Connect.MethodSpec(name: "CompletePriceCheck", service: "openmarket.api.v1.PricingService", type: .unary)
            public static let submitPriceCheckFeedback = Connect.MethodSpec(name: "SubmitPriceCheckFeedback", service: "openmarket.api.v1.PricingService", type: .unary)
            public static let recordPriceCheckCopy = Connect.MethodSpec(name: "RecordPriceCheckCopy", service: "openmarket.api.v1.PricingService", type: .unary)
            public static let listPriceChecks = Connect.MethodSpec(name: "ListPriceChecks", service: "openmarket.api.v1.PricingService", type: .unary)
        }
    }
}
