// Code generated by protoc-gen-connect-swift. DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Source: openmarket/api/v1/shopping_service.proto
//

import Connect
import Foundation
import SwiftProtobuf

public protocol Openmarket_Api_V1_ShoppingServiceClientInterface: Sendable {

    @available(iOS 13, *)
    func `startShopping`(request: Openmarket_Api_V1_StartShoppingRequest, headers: Connect.Headers) async -> ResponseMessage<Openmarket_Api_V1_StartShoppingResponse>

    @available(iOS 13, *)
    func `sendShoppingMessage`(request: Openmarket_Api_V1_SendShoppingMessageRequest, headers: Connect.Headers) async -> ResponseMessage<Openmarket_Api_V1_SendShoppingMessageResponse>

    @available(iOS 13, *)
    func `getShoppingSession`(request: Openmarket_Api_V1_GetShoppingSessionRequest, headers: Connect.Headers) async -> ResponseMessage<Openmarket_Api_V1_GetShoppingSessionResponse>

    @available(iOS 13, *)
    func `submitShoppingToolResult`(request: Openmarket_Api_V1_SubmitShoppingToolResultRequest, headers: Connect.Headers) async -> ResponseMessage<Openmarket_Api_V1_SubmitShoppingToolResultResponse>

    @available(iOS 13, *)
    func `controlShoppingSession`(request: Openmarket_Api_V1_ControlShoppingSessionRequest, headers: Connect.Headers) async -> ResponseMessage<Openmarket_Api_V1_ControlShoppingSessionResponse>
}

/// Concrete implementation of `Openmarket_Api_V1_ShoppingServiceClientInterface`.
public final class Openmarket_Api_V1_ShoppingServiceClient: Openmarket_Api_V1_ShoppingServiceClientInterface, Sendable {
    private let client: Connect.ProtocolClientInterface

    public init(client: Connect.ProtocolClientInterface) {
        self.client = client
    }

    @available(iOS 13, *)
    public func `startShopping`(request: Openmarket_Api_V1_StartShoppingRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Openmarket_Api_V1_StartShoppingResponse> {
        return await self.client.unary(path: "/openmarket.api.v1.ShoppingService/StartShopping", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `sendShoppingMessage`(request: Openmarket_Api_V1_SendShoppingMessageRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Openmarket_Api_V1_SendShoppingMessageResponse> {
        return await self.client.unary(path: "/openmarket.api.v1.ShoppingService/SendShoppingMessage", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `getShoppingSession`(request: Openmarket_Api_V1_GetShoppingSessionRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Openmarket_Api_V1_GetShoppingSessionResponse> {
        return await self.client.unary(path: "/openmarket.api.v1.ShoppingService/GetShoppingSession", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `submitShoppingToolResult`(request: Openmarket_Api_V1_SubmitShoppingToolResultRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Openmarket_Api_V1_SubmitShoppingToolResultResponse> {
        return await self.client.unary(path: "/openmarket.api.v1.ShoppingService/SubmitShoppingToolResult", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `controlShoppingSession`(request: Openmarket_Api_V1_ControlShoppingSessionRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Openmarket_Api_V1_ControlShoppingSessionResponse> {
        return await self.client.unary(path: "/openmarket.api.v1.ShoppingService/ControlShoppingSession", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    public enum Metadata {
        public enum Methods {
            public static let startShopping = Connect.MethodSpec(name: "StartShopping", service: "openmarket.api.v1.ShoppingService", type: .unary)
            public static let sendShoppingMessage = Connect.MethodSpec(name: "SendShoppingMessage", service: "openmarket.api.v1.ShoppingService", type: .unary)
            public static let getShoppingSession = Connect.MethodSpec(name: "GetShoppingSession", service: "openmarket.api.v1.ShoppingService", type: .unary)
            public static let submitShoppingToolResult = Connect.MethodSpec(name: "SubmitShoppingToolResult", service: "openmarket.api.v1.ShoppingService", type: .unary)
            public static let controlShoppingSession = Connect.MethodSpec(name: "ControlShoppingSession", service: "openmarket.api.v1.ShoppingService", type: .unary)
        }
    }
}
