// Code generated by protoc-gen-connect-swift. DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Source: openmarket/api/v1/user_service.proto
//

import Connect
import Foundation
import SwiftProtobuf

public protocol Openmarket_Api_V1_UserServiceClientInterface: Sendable {

    @available(iOS 13, *)
    func `getViewer`(request: Openmarket_Api_V1_GetViewerRequest, headers: Connect.Headers) async -> ResponseMessage<Openmarket_Api_V1_GetViewerResponse>

    @available(iOS 13, *)
    func `updateViewer`(request: Openmarket_Api_V1_UpdateViewerRequest, headers: Connect.Headers) async -> ResponseMessage<Openmarket_Api_V1_UpdateViewerResponse>

    @available(iOS 13, *)
    func `registerDeviceToken`(request: Openmarket_Api_V1_RegisterDeviceTokenRequest, headers: Connect.Headers) async -> ResponseMessage<Openmarket_Api_V1_RegisterDeviceTokenResponse>

    /// Reports whether the Facebook webview session exists on this install. The
    /// client is the only thing that can know — the state is a cookie jar it owns —
    /// so this is a report, not a request to change anything.
    @available(iOS 13, *)
    func `setFacebookConnection`(request: Openmarket_Api_V1_SetFacebookConnectionRequest, headers: Connect.Headers) async -> ResponseMessage<Openmarket_Api_V1_SetFacebookConnectionResponse>

    /// Required by App Store Guideline 5.1.1(v): an app that creates an account
    /// must let the user delete it in-app.
    @available(iOS 13, *)
    func `deleteAccount`(request: Openmarket_Api_V1_DeleteAccountRequest, headers: Connect.Headers) async -> ResponseMessage<Openmarket_Api_V1_DeleteAccountResponse>
}

/// Concrete implementation of `Openmarket_Api_V1_UserServiceClientInterface`.
public final class Openmarket_Api_V1_UserServiceClient: Openmarket_Api_V1_UserServiceClientInterface, Sendable {
    private let client: Connect.ProtocolClientInterface

    public init(client: Connect.ProtocolClientInterface) {
        self.client = client
    }

    @available(iOS 13, *)
    public func `getViewer`(request: Openmarket_Api_V1_GetViewerRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Openmarket_Api_V1_GetViewerResponse> {
        return await self.client.unary(path: "/openmarket.api.v1.UserService/GetViewer", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `updateViewer`(request: Openmarket_Api_V1_UpdateViewerRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Openmarket_Api_V1_UpdateViewerResponse> {
        return await self.client.unary(path: "/openmarket.api.v1.UserService/UpdateViewer", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `registerDeviceToken`(request: Openmarket_Api_V1_RegisterDeviceTokenRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Openmarket_Api_V1_RegisterDeviceTokenResponse> {
        return await self.client.unary(path: "/openmarket.api.v1.UserService/RegisterDeviceToken", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `setFacebookConnection`(request: Openmarket_Api_V1_SetFacebookConnectionRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Openmarket_Api_V1_SetFacebookConnectionResponse> {
        return await self.client.unary(path: "/openmarket.api.v1.UserService/SetFacebookConnection", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `deleteAccount`(request: Openmarket_Api_V1_DeleteAccountRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Openmarket_Api_V1_DeleteAccountResponse> {
        return await self.client.unary(path: "/openmarket.api.v1.UserService/DeleteAccount", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    public enum Metadata {
        public enum Methods {
            public static let getViewer = Connect.MethodSpec(name: "GetViewer", service: "openmarket.api.v1.UserService", type: .unary)
            public static let updateViewer = Connect.MethodSpec(name: "UpdateViewer", service: "openmarket.api.v1.UserService", type: .unary)
            public static let registerDeviceToken = Connect.MethodSpec(name: "RegisterDeviceToken", service: "openmarket.api.v1.UserService", type: .unary)
            public static let setFacebookConnection = Connect.MethodSpec(name: "SetFacebookConnection", service: "openmarket.api.v1.UserService", type: .unary)
            public static let deleteAccount = Connect.MethodSpec(name: "DeleteAccount", service: "openmarket.api.v1.UserService", type: .unary)
        }
    }
}
