// swift-tools-version:5.9
import PackageDescription

// Generated code only. Everything under Sources/OpenMarketProtos/openmarket and
// .../buf is written by `buf generate` from /protos and must never be edited by
// hand — see Aliases.swift for the one file here that is hand-written, and the
// reason it is kept separate.
let package = Package(
    name: "OpenMarketProtos",
    // iOS is the only platform that ships. macOS is declared so `swift build`
    // can verify this target from the command line without an Xcode scheme —
    // without it SPM assumes macOS 10.13 and refuses to link Connect.
    platforms: [.iOS(.v17), .macOS(.v13)],
    products: [
        .library(name: "OpenMarketProtos", targets: ["OpenMarketProtos"])
    ],
    // Exact versions, not ranges.
    //
    // The .xcodeproj is generated by xcodegen and gitignored, and the resolved
    // versions for a local package live inside it — so there is no committed
    // Package.resolved anywhere in this repo to pin them. With a range, two
    // checkouts of the same commit can build against different dependency
    // versions, and the one that breaks is whichever machine resolved later.
    // Bumping these is a visible one-line commit, which is the right shape for
    // a dependency that ships inside a signed app.
    dependencies: [
        .package(url: "https://github.com/apple/swift-protobuf.git", exact: "1.38.1"),
        // connect-swift rides on URLSession rather than bringing its own HTTP/2
        // stack, which is the entire reason this app uses Connect instead of
        // gRPC: the system keeps handling cellular, proxies, ATS and background
        // transfer exactly as it does for every other request the app makes.
        .package(url: "https://github.com/connectrpc/connect-swift.git", exact: "1.2.3"),
    ],
    targets: [
        .target(
            name: "OpenMarketProtos",
            dependencies: [
                .product(name: "SwiftProtobuf", package: "swift-protobuf"),
                .product(name: "Connect", package: "connect-swift"),
            ],
            path: "Sources/OpenMarketProtos"
        )
    ]
)
