// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: openmarket/api/v1/auth_service.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "frens.lol/openmarket/backend/pkg/protos/openmarket/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "openmarket.api.v1.AuthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthServiceGetSignInOptionsProcedure is the fully-qualified name of the AuthService's
	// GetSignInOptions RPC.
	AuthServiceGetSignInOptionsProcedure = "/openmarket.api.v1.AuthService/GetSignInOptions"
	// AuthServiceStartPhoneVerificationProcedure is the fully-qualified name of the AuthService's
	// StartPhoneVerification RPC.
	AuthServiceStartPhoneVerificationProcedure = "/openmarket.api.v1.AuthService/StartPhoneVerification"
	// AuthServiceVerifyPhoneProcedure is the fully-qualified name of the AuthService's VerifyPhone RPC.
	AuthServiceVerifyPhoneProcedure = "/openmarket.api.v1.AuthService/VerifyPhone"
	// AuthServiceRefreshTokenProcedure is the fully-qualified name of the AuthService's RefreshToken
	// RPC.
	AuthServiceRefreshTokenProcedure = "/openmarket.api.v1.AuthService/RefreshToken"
	// AuthServiceLogoutProcedure is the fully-qualified name of the AuthService's Logout RPC.
	AuthServiceLogoutProcedure = "/openmarket.api.v1.AuthService/Logout"
)

// AuthServiceClient is a client for the openmarket.api.v1.AuthService service.
type AuthServiceClient interface {
	GetSignInOptions(context.Context, *connect.Request[v1.GetSignInOptionsRequest]) (*connect.Response[v1.GetSignInOptionsResponse], error)
	StartPhoneVerification(context.Context, *connect.Request[v1.StartPhoneVerificationRequest]) (*connect.Response[v1.StartPhoneVerificationResponse], error)
	VerifyPhone(context.Context, *connect.Request[v1.VerifyPhoneRequest]) (*connect.Response[v1.VerifyPhoneResponse], error)
	RefreshToken(context.Context, *connect.Request[v1.RefreshTokenRequest]) (*connect.Response[v1.RefreshTokenResponse], error)
	Logout(context.Context, *connect.Request[v1.LogoutRequest]) (*connect.Response[v1.LogoutResponse], error)
}

// NewAuthServiceClient constructs a client for the openmarket.api.v1.AuthService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authServiceMethods := v1.File_openmarket_api_v1_auth_service_proto.Services().ByName("AuthService").Methods()
	return &authServiceClient{
		getSignInOptions: connect.NewClient[v1.GetSignInOptionsRequest, v1.GetSignInOptionsResponse](
			httpClient,
			baseURL+AuthServiceGetSignInOptionsProcedure,
			connect.WithSchema(authServiceMethods.ByName("GetSignInOptions")),
			connect.WithClientOptions(opts...),
		),
		startPhoneVerification: connect.NewClient[v1.StartPhoneVerificationRequest, v1.StartPhoneVerificationResponse](
			httpClient,
			baseURL+AuthServiceStartPhoneVerificationProcedure,
			connect.WithSchema(authServiceMethods.ByName("StartPhoneVerification")),
			connect.WithClientOptions(opts...),
		),
		verifyPhone: connect.NewClient[v1.VerifyPhoneRequest, v1.VerifyPhoneResponse](
			httpClient,
			baseURL+AuthServiceVerifyPhoneProcedure,
			connect.WithSchema(authServiceMethods.ByName("VerifyPhone")),
			connect.WithClientOptions(opts...),
		),
		refreshToken: connect.NewClient[v1.RefreshTokenRequest, v1.RefreshTokenResponse](
			httpClient,
			baseURL+AuthServiceRefreshTokenProcedure,
			connect.WithSchema(authServiceMethods.ByName("RefreshToken")),
			connect.WithClientOptions(opts...),
		),
		logout: connect.NewClient[v1.LogoutRequest, v1.LogoutResponse](
			httpClient,
			baseURL+AuthServiceLogoutProcedure,
			connect.WithSchema(authServiceMethods.ByName("Logout")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	getSignInOptions       *connect.Client[v1.GetSignInOptionsRequest, v1.GetSignInOptionsResponse]
	startPhoneVerification *connect.Client[v1.StartPhoneVerificationRequest, v1.StartPhoneVerificationResponse]
	verifyPhone            *connect.Client[v1.VerifyPhoneRequest, v1.VerifyPhoneResponse]
	refreshToken           *connect.Client[v1.RefreshTokenRequest, v1.RefreshTokenResponse]
	logout                 *connect.Client[v1.LogoutRequest, v1.LogoutResponse]
}

// GetSignInOptions calls openmarket.api.v1.AuthService.GetSignInOptions.
func (c *authServiceClient) GetSignInOptions(ctx context.Context, req *connect.Request[v1.GetSignInOptionsRequest]) (*connect.Response[v1.GetSignInOptionsResponse], error) {
	return c.getSignInOptions.CallUnary(ctx, req)
}

// StartPhoneVerification calls openmarket.api.v1.AuthService.StartPhoneVerification.
func (c *authServiceClient) StartPhoneVerification(ctx context.Context, req *connect.Request[v1.StartPhoneVerificationRequest]) (*connect.Response[v1.StartPhoneVerificationResponse], error) {
	return c.startPhoneVerification.CallUnary(ctx, req)
}

// VerifyPhone calls openmarket.api.v1.AuthService.VerifyPhone.
func (c *authServiceClient) VerifyPhone(ctx context.Context, req *connect.Request[v1.VerifyPhoneRequest]) (*connect.Response[v1.VerifyPhoneResponse], error) {
	return c.verifyPhone.CallUnary(ctx, req)
}

// RefreshToken calls openmarket.api.v1.AuthService.RefreshToken.
func (c *authServiceClient) RefreshToken(ctx context.Context, req *connect.Request[v1.RefreshTokenRequest]) (*connect.Response[v1.RefreshTokenResponse], error) {
	return c.refreshToken.CallUnary(ctx, req)
}

// Logout calls openmarket.api.v1.AuthService.Logout.
func (c *authServiceClient) Logout(ctx context.Context, req *connect.Request[v1.LogoutRequest]) (*connect.Response[v1.LogoutResponse], error) {
	return c.logout.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the openmarket.api.v1.AuthService service.
type AuthServiceHandler interface {
	GetSignInOptions(context.Context, *connect.Request[v1.GetSignInOptionsRequest]) (*connect.Response[v1.GetSignInOptionsResponse], error)
	StartPhoneVerification(context.Context, *connect.Request[v1.StartPhoneVerificationRequest]) (*connect.Response[v1.StartPhoneVerificationResponse], error)
	VerifyPhone(context.Context, *connect.Request[v1.VerifyPhoneRequest]) (*connect.Response[v1.VerifyPhoneResponse], error)
	RefreshToken(context.Context, *connect.Request[v1.RefreshTokenRequest]) (*connect.Response[v1.RefreshTokenResponse], error)
	Logout(context.Context, *connect.Request[v1.LogoutRequest]) (*connect.Response[v1.LogoutResponse], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authServiceMethods := v1.File_openmarket_api_v1_auth_service_proto.Services().ByName("AuthService").Methods()
	authServiceGetSignInOptionsHandler := connect.NewUnaryHandler(
		AuthServiceGetSignInOptionsProcedure,
		svc.GetSignInOptions,
		connect.WithSchema(authServiceMethods.ByName("GetSignInOptions")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceStartPhoneVerificationHandler := connect.NewUnaryHandler(
		AuthServiceStartPhoneVerificationProcedure,
		svc.StartPhoneVerification,
		connect.WithSchema(authServiceMethods.ByName("StartPhoneVerification")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceVerifyPhoneHandler := connect.NewUnaryHandler(
		AuthServiceVerifyPhoneProcedure,
		svc.VerifyPhone,
		connect.WithSchema(authServiceMethods.ByName("VerifyPhone")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceRefreshTokenHandler := connect.NewUnaryHandler(
		AuthServiceRefreshTokenProcedure,
		svc.RefreshToken,
		connect.WithSchema(authServiceMethods.ByName("RefreshToken")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceLogoutHandler := connect.NewUnaryHandler(
		AuthServiceLogoutProcedure,
		svc.Logout,
		connect.WithSchema(authServiceMethods.ByName("Logout")),
		connect.WithHandlerOptions(opts...),
	)
	return "/openmarket.api.v1.AuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthServiceGetSignInOptionsProcedure:
			authServiceGetSignInOptionsHandler.ServeHTTP(w, r)
		case AuthServiceStartPhoneVerificationProcedure:
			authServiceStartPhoneVerificationHandler.ServeHTTP(w, r)
		case AuthServiceVerifyPhoneProcedure:
			authServiceVerifyPhoneHandler.ServeHTTP(w, r)
		case AuthServiceRefreshTokenProcedure:
			authServiceRefreshTokenHandler.ServeHTTP(w, r)
		case AuthServiceLogoutProcedure:
			authServiceLogoutHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) GetSignInOptions(context.Context, *connect.Request[v1.GetSignInOptionsRequest]) (*connect.Response[v1.GetSignInOptionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmarket.api.v1.AuthService.GetSignInOptions is not implemented"))
}

func (UnimplementedAuthServiceHandler) StartPhoneVerification(context.Context, *connect.Request[v1.StartPhoneVerificationRequest]) (*connect.Response[v1.StartPhoneVerificationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmarket.api.v1.AuthService.StartPhoneVerification is not implemented"))
}

func (UnimplementedAuthServiceHandler) VerifyPhone(context.Context, *connect.Request[v1.VerifyPhoneRequest]) (*connect.Response[v1.VerifyPhoneResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmarket.api.v1.AuthService.VerifyPhone is not implemented"))
}

func (UnimplementedAuthServiceHandler) RefreshToken(context.Context, *connect.Request[v1.RefreshTokenRequest]) (*connect.Response[v1.RefreshTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmarket.api.v1.AuthService.RefreshToken is not implemented"))
}

func (UnimplementedAuthServiceHandler) Logout(context.Context, *connect.Request[v1.LogoutRequest]) (*connect.Response[v1.LogoutResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmarket.api.v1.AuthService.Logout is not implemented"))
}
