// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: openmarket/api/v1/observation_service.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "frens.lol/openmarket/backend/pkg/protos/openmarket/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ObservationServiceName is the fully-qualified name of the ObservationService service.
	ObservationServiceName = "openmarket.api.v1.ObservationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ObservationServiceSubmitObservationsProcedure is the fully-qualified name of the
	// ObservationService's SubmitObservations RPC.
	ObservationServiceSubmitObservationsProcedure = "/openmarket.api.v1.ObservationService/SubmitObservations"
)

// ObservationServiceClient is a client for the openmarket.api.v1.ObservationService service.
type ObservationServiceClient interface {
	SubmitObservations(context.Context, *connect.Request[v1.SubmitObservationsRequest]) (*connect.Response[v1.SubmitObservationsResponse], error)
}

// NewObservationServiceClient constructs a client for the openmarket.api.v1.ObservationService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewObservationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ObservationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	observationServiceMethods := v1.File_openmarket_api_v1_observation_service_proto.Services().ByName("ObservationService").Methods()
	return &observationServiceClient{
		submitObservations: connect.NewClient[v1.SubmitObservationsRequest, v1.SubmitObservationsResponse](
			httpClient,
			baseURL+ObservationServiceSubmitObservationsProcedure,
			connect.WithSchema(observationServiceMethods.ByName("SubmitObservations")),
			connect.WithClientOptions(opts...),
		),
	}
}

// observationServiceClient implements ObservationServiceClient.
type observationServiceClient struct {
	submitObservations *connect.Client[v1.SubmitObservationsRequest, v1.SubmitObservationsResponse]
}

// SubmitObservations calls openmarket.api.v1.ObservationService.SubmitObservations.
func (c *observationServiceClient) SubmitObservations(ctx context.Context, req *connect.Request[v1.SubmitObservationsRequest]) (*connect.Response[v1.SubmitObservationsResponse], error) {
	return c.submitObservations.CallUnary(ctx, req)
}

// ObservationServiceHandler is an implementation of the openmarket.api.v1.ObservationService
// service.
type ObservationServiceHandler interface {
	SubmitObservations(context.Context, *connect.Request[v1.SubmitObservationsRequest]) (*connect.Response[v1.SubmitObservationsResponse], error)
}

// NewObservationServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewObservationServiceHandler(svc ObservationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	observationServiceMethods := v1.File_openmarket_api_v1_observation_service_proto.Services().ByName("ObservationService").Methods()
	observationServiceSubmitObservationsHandler := connect.NewUnaryHandler(
		ObservationServiceSubmitObservationsProcedure,
		svc.SubmitObservations,
		connect.WithSchema(observationServiceMethods.ByName("SubmitObservations")),
		connect.WithHandlerOptions(opts...),
	)
	return "/openmarket.api.v1.ObservationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ObservationServiceSubmitObservationsProcedure:
			observationServiceSubmitObservationsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedObservationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedObservationServiceHandler struct{}

func (UnimplementedObservationServiceHandler) SubmitObservations(context.Context, *connect.Request[v1.SubmitObservationsRequest]) (*connect.Response[v1.SubmitObservationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmarket.api.v1.ObservationService.SubmitObservations is not implemented"))
}
