// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: openmarket/api/v1/pricing_service.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "frens.lol/openmarket/backend/pkg/protos/openmarket/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PricingServiceName is the fully-qualified name of the PricingService service.
	PricingServiceName = "openmarket.api.v1.PricingService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PricingServiceIdentifyItemProcedure is the fully-qualified name of the PricingService's
	// IdentifyItem RPC.
	PricingServiceIdentifyItemProcedure = "/openmarket.api.v1.PricingService/IdentifyItem"
	// PricingServicePriceItemProcedure is the fully-qualified name of the PricingService's PriceItem
	// RPC.
	PricingServicePriceItemProcedure = "/openmarket.api.v1.PricingService/PriceItem"
	// PricingServiceSubmitPriceCheckFeedbackProcedure is the fully-qualified name of the
	// PricingService's SubmitPriceCheckFeedback RPC.
	PricingServiceSubmitPriceCheckFeedbackProcedure = "/openmarket.api.v1.PricingService/SubmitPriceCheckFeedback"
	// PricingServiceRecordPriceCopiedProcedure is the fully-qualified name of the PricingService's
	// RecordPriceCopied RPC.
	PricingServiceRecordPriceCopiedProcedure = "/openmarket.api.v1.PricingService/RecordPriceCopied"
)

// PricingServiceClient is a client for the openmarket.api.v1.PricingService service.
type PricingServiceClient interface {
	IdentifyItem(context.Context, *connect.Request[v1.IdentifyItemRequest]) (*connect.Response[v1.IdentifyItemResponse], error)
	PriceItem(context.Context, *connect.Request[v1.PriceItemRequest]) (*connect.Response[v1.PriceItemResponse], error)
	// The asked question.
	SubmitPriceCheckFeedback(context.Context, *connect.Request[v1.SubmitPriceCheckFeedbackRequest]) (*connect.Response[v1.SubmitPriceCheckFeedbackResponse], error)
	// The unasked one, and the better of the two. Copying the price is what
	// somebody does immediately before pasting it into Facebook's price box: it
	// is captured on nearly every successful run, where a prompt is answered by
	// the minority who feel strongly enough to stop and tap — which skews
	// negative. Idempotent; the first copy keeps the timestamp.
	RecordPriceCopied(context.Context, *connect.Request[v1.RecordPriceCopiedRequest]) (*connect.Response[v1.RecordPriceCopiedResponse], error)
}

// NewPricingServiceClient constructs a client for the openmarket.api.v1.PricingService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPricingServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PricingServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	pricingServiceMethods := v1.File_openmarket_api_v1_pricing_service_proto.Services().ByName("PricingService").Methods()
	return &pricingServiceClient{
		identifyItem: connect.NewClient[v1.IdentifyItemRequest, v1.IdentifyItemResponse](
			httpClient,
			baseURL+PricingServiceIdentifyItemProcedure,
			connect.WithSchema(pricingServiceMethods.ByName("IdentifyItem")),
			connect.WithClientOptions(opts...),
		),
		priceItem: connect.NewClient[v1.PriceItemRequest, v1.PriceItemResponse](
			httpClient,
			baseURL+PricingServicePriceItemProcedure,
			connect.WithSchema(pricingServiceMethods.ByName("PriceItem")),
			connect.WithClientOptions(opts...),
		),
		submitPriceCheckFeedback: connect.NewClient[v1.SubmitPriceCheckFeedbackRequest, v1.SubmitPriceCheckFeedbackResponse](
			httpClient,
			baseURL+PricingServiceSubmitPriceCheckFeedbackProcedure,
			connect.WithSchema(pricingServiceMethods.ByName("SubmitPriceCheckFeedback")),
			connect.WithClientOptions(opts...),
		),
		recordPriceCopied: connect.NewClient[v1.RecordPriceCopiedRequest, v1.RecordPriceCopiedResponse](
			httpClient,
			baseURL+PricingServiceRecordPriceCopiedProcedure,
			connect.WithSchema(pricingServiceMethods.ByName("RecordPriceCopied")),
			connect.WithClientOptions(opts...),
		),
	}
}

// pricingServiceClient implements PricingServiceClient.
type pricingServiceClient struct {
	identifyItem             *connect.Client[v1.IdentifyItemRequest, v1.IdentifyItemResponse]
	priceItem                *connect.Client[v1.PriceItemRequest, v1.PriceItemResponse]
	submitPriceCheckFeedback *connect.Client[v1.SubmitPriceCheckFeedbackRequest, v1.SubmitPriceCheckFeedbackResponse]
	recordPriceCopied        *connect.Client[v1.RecordPriceCopiedRequest, v1.RecordPriceCopiedResponse]
}

// IdentifyItem calls openmarket.api.v1.PricingService.IdentifyItem.
func (c *pricingServiceClient) IdentifyItem(ctx context.Context, req *connect.Request[v1.IdentifyItemRequest]) (*connect.Response[v1.IdentifyItemResponse], error) {
	return c.identifyItem.CallUnary(ctx, req)
}

// PriceItem calls openmarket.api.v1.PricingService.PriceItem.
func (c *pricingServiceClient) PriceItem(ctx context.Context, req *connect.Request[v1.PriceItemRequest]) (*connect.Response[v1.PriceItemResponse], error) {
	return c.priceItem.CallUnary(ctx, req)
}

// SubmitPriceCheckFeedback calls openmarket.api.v1.PricingService.SubmitPriceCheckFeedback.
func (c *pricingServiceClient) SubmitPriceCheckFeedback(ctx context.Context, req *connect.Request[v1.SubmitPriceCheckFeedbackRequest]) (*connect.Response[v1.SubmitPriceCheckFeedbackResponse], error) {
	return c.submitPriceCheckFeedback.CallUnary(ctx, req)
}

// RecordPriceCopied calls openmarket.api.v1.PricingService.RecordPriceCopied.
func (c *pricingServiceClient) RecordPriceCopied(ctx context.Context, req *connect.Request[v1.RecordPriceCopiedRequest]) (*connect.Response[v1.RecordPriceCopiedResponse], error) {
	return c.recordPriceCopied.CallUnary(ctx, req)
}

// PricingServiceHandler is an implementation of the openmarket.api.v1.PricingService service.
type PricingServiceHandler interface {
	IdentifyItem(context.Context, *connect.Request[v1.IdentifyItemRequest]) (*connect.Response[v1.IdentifyItemResponse], error)
	PriceItem(context.Context, *connect.Request[v1.PriceItemRequest]) (*connect.Response[v1.PriceItemResponse], error)
	// The asked question.
	SubmitPriceCheckFeedback(context.Context, *connect.Request[v1.SubmitPriceCheckFeedbackRequest]) (*connect.Response[v1.SubmitPriceCheckFeedbackResponse], error)
	// The unasked one, and the better of the two. Copying the price is what
	// somebody does immediately before pasting it into Facebook's price box: it
	// is captured on nearly every successful run, where a prompt is answered by
	// the minority who feel strongly enough to stop and tap — which skews
	// negative. Idempotent; the first copy keeps the timestamp.
	RecordPriceCopied(context.Context, *connect.Request[v1.RecordPriceCopiedRequest]) (*connect.Response[v1.RecordPriceCopiedResponse], error)
}

// NewPricingServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPricingServiceHandler(svc PricingServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	pricingServiceMethods := v1.File_openmarket_api_v1_pricing_service_proto.Services().ByName("PricingService").Methods()
	pricingServiceIdentifyItemHandler := connect.NewUnaryHandler(
		PricingServiceIdentifyItemProcedure,
		svc.IdentifyItem,
		connect.WithSchema(pricingServiceMethods.ByName("IdentifyItem")),
		connect.WithHandlerOptions(opts...),
	)
	pricingServicePriceItemHandler := connect.NewUnaryHandler(
		PricingServicePriceItemProcedure,
		svc.PriceItem,
		connect.WithSchema(pricingServiceMethods.ByName("PriceItem")),
		connect.WithHandlerOptions(opts...),
	)
	pricingServiceSubmitPriceCheckFeedbackHandler := connect.NewUnaryHandler(
		PricingServiceSubmitPriceCheckFeedbackProcedure,
		svc.SubmitPriceCheckFeedback,
		connect.WithSchema(pricingServiceMethods.ByName("SubmitPriceCheckFeedback")),
		connect.WithHandlerOptions(opts...),
	)
	pricingServiceRecordPriceCopiedHandler := connect.NewUnaryHandler(
		PricingServiceRecordPriceCopiedProcedure,
		svc.RecordPriceCopied,
		connect.WithSchema(pricingServiceMethods.ByName("RecordPriceCopied")),
		connect.WithHandlerOptions(opts...),
	)
	return "/openmarket.api.v1.PricingService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PricingServiceIdentifyItemProcedure:
			pricingServiceIdentifyItemHandler.ServeHTTP(w, r)
		case PricingServicePriceItemProcedure:
			pricingServicePriceItemHandler.ServeHTTP(w, r)
		case PricingServiceSubmitPriceCheckFeedbackProcedure:
			pricingServiceSubmitPriceCheckFeedbackHandler.ServeHTTP(w, r)
		case PricingServiceRecordPriceCopiedProcedure:
			pricingServiceRecordPriceCopiedHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPricingServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPricingServiceHandler struct{}

func (UnimplementedPricingServiceHandler) IdentifyItem(context.Context, *connect.Request[v1.IdentifyItemRequest]) (*connect.Response[v1.IdentifyItemResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmarket.api.v1.PricingService.IdentifyItem is not implemented"))
}

func (UnimplementedPricingServiceHandler) PriceItem(context.Context, *connect.Request[v1.PriceItemRequest]) (*connect.Response[v1.PriceItemResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmarket.api.v1.PricingService.PriceItem is not implemented"))
}

func (UnimplementedPricingServiceHandler) SubmitPriceCheckFeedback(context.Context, *connect.Request[v1.SubmitPriceCheckFeedbackRequest]) (*connect.Response[v1.SubmitPriceCheckFeedbackResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmarket.api.v1.PricingService.SubmitPriceCheckFeedback is not implemented"))
}

func (UnimplementedPricingServiceHandler) RecordPriceCopied(context.Context, *connect.Request[v1.RecordPriceCopiedRequest]) (*connect.Response[v1.RecordPriceCopiedResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmarket.api.v1.PricingService.RecordPriceCopied is not implemented"))
}
