// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: openmarket/api/v1/user_service.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "frens.lol/openmarket/backend/pkg/protos/openmarket/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// UserServiceName is the fully-qualified name of the UserService service.
	UserServiceName = "openmarket.api.v1.UserService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UserServiceGetViewerProcedure is the fully-qualified name of the UserService's GetViewer RPC.
	UserServiceGetViewerProcedure = "/openmarket.api.v1.UserService/GetViewer"
	// UserServiceUpdateViewerProcedure is the fully-qualified name of the UserService's UpdateViewer
	// RPC.
	UserServiceUpdateViewerProcedure = "/openmarket.api.v1.UserService/UpdateViewer"
	// UserServiceRegisterDeviceTokenProcedure is the fully-qualified name of the UserService's
	// RegisterDeviceToken RPC.
	UserServiceRegisterDeviceTokenProcedure = "/openmarket.api.v1.UserService/RegisterDeviceToken"
	// UserServiceSetFacebookConnectionProcedure is the fully-qualified name of the UserService's
	// SetFacebookConnection RPC.
	UserServiceSetFacebookConnectionProcedure = "/openmarket.api.v1.UserService/SetFacebookConnection"
	// UserServiceDeleteAccountProcedure is the fully-qualified name of the UserService's DeleteAccount
	// RPC.
	UserServiceDeleteAccountProcedure = "/openmarket.api.v1.UserService/DeleteAccount"
)

// UserServiceClient is a client for the openmarket.api.v1.UserService service.
type UserServiceClient interface {
	GetViewer(context.Context, *connect.Request[v1.GetViewerRequest]) (*connect.Response[v1.GetViewerResponse], error)
	UpdateViewer(context.Context, *connect.Request[v1.UpdateViewerRequest]) (*connect.Response[v1.UpdateViewerResponse], error)
	RegisterDeviceToken(context.Context, *connect.Request[v1.RegisterDeviceTokenRequest]) (*connect.Response[v1.RegisterDeviceTokenResponse], error)
	// Reports whether the Facebook webview session exists on this install. The
	// client is the only thing that can know — the state is a cookie jar it owns —
	// so this is a report, not a request to change anything.
	SetFacebookConnection(context.Context, *connect.Request[v1.SetFacebookConnectionRequest]) (*connect.Response[v1.SetFacebookConnectionResponse], error)
	// Required by App Store Guideline 5.1.1(v): an app that creates an account
	// must let the user delete it in-app.
	DeleteAccount(context.Context, *connect.Request[v1.DeleteAccountRequest]) (*connect.Response[v1.DeleteAccountResponse], error)
}

// NewUserServiceClient constructs a client for the openmarket.api.v1.UserService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUserServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UserServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	userServiceMethods := v1.File_openmarket_api_v1_user_service_proto.Services().ByName("UserService").Methods()
	return &userServiceClient{
		getViewer: connect.NewClient[v1.GetViewerRequest, v1.GetViewerResponse](
			httpClient,
			baseURL+UserServiceGetViewerProcedure,
			connect.WithSchema(userServiceMethods.ByName("GetViewer")),
			connect.WithClientOptions(opts...),
		),
		updateViewer: connect.NewClient[v1.UpdateViewerRequest, v1.UpdateViewerResponse](
			httpClient,
			baseURL+UserServiceUpdateViewerProcedure,
			connect.WithSchema(userServiceMethods.ByName("UpdateViewer")),
			connect.WithClientOptions(opts...),
		),
		registerDeviceToken: connect.NewClient[v1.RegisterDeviceTokenRequest, v1.RegisterDeviceTokenResponse](
			httpClient,
			baseURL+UserServiceRegisterDeviceTokenProcedure,
			connect.WithSchema(userServiceMethods.ByName("RegisterDeviceToken")),
			connect.WithClientOptions(opts...),
		),
		setFacebookConnection: connect.NewClient[v1.SetFacebookConnectionRequest, v1.SetFacebookConnectionResponse](
			httpClient,
			baseURL+UserServiceSetFacebookConnectionProcedure,
			connect.WithSchema(userServiceMethods.ByName("SetFacebookConnection")),
			connect.WithClientOptions(opts...),
		),
		deleteAccount: connect.NewClient[v1.DeleteAccountRequest, v1.DeleteAccountResponse](
			httpClient,
			baseURL+UserServiceDeleteAccountProcedure,
			connect.WithSchema(userServiceMethods.ByName("DeleteAccount")),
			connect.WithClientOptions(opts...),
		),
	}
}

// userServiceClient implements UserServiceClient.
type userServiceClient struct {
	getViewer             *connect.Client[v1.GetViewerRequest, v1.GetViewerResponse]
	updateViewer          *connect.Client[v1.UpdateViewerRequest, v1.UpdateViewerResponse]
	registerDeviceToken   *connect.Client[v1.RegisterDeviceTokenRequest, v1.RegisterDeviceTokenResponse]
	setFacebookConnection *connect.Client[v1.SetFacebookConnectionRequest, v1.SetFacebookConnectionResponse]
	deleteAccount         *connect.Client[v1.DeleteAccountRequest, v1.DeleteAccountResponse]
}

// GetViewer calls openmarket.api.v1.UserService.GetViewer.
func (c *userServiceClient) GetViewer(ctx context.Context, req *connect.Request[v1.GetViewerRequest]) (*connect.Response[v1.GetViewerResponse], error) {
	return c.getViewer.CallUnary(ctx, req)
}

// UpdateViewer calls openmarket.api.v1.UserService.UpdateViewer.
func (c *userServiceClient) UpdateViewer(ctx context.Context, req *connect.Request[v1.UpdateViewerRequest]) (*connect.Response[v1.UpdateViewerResponse], error) {
	return c.updateViewer.CallUnary(ctx, req)
}

// RegisterDeviceToken calls openmarket.api.v1.UserService.RegisterDeviceToken.
func (c *userServiceClient) RegisterDeviceToken(ctx context.Context, req *connect.Request[v1.RegisterDeviceTokenRequest]) (*connect.Response[v1.RegisterDeviceTokenResponse], error) {
	return c.registerDeviceToken.CallUnary(ctx, req)
}

// SetFacebookConnection calls openmarket.api.v1.UserService.SetFacebookConnection.
func (c *userServiceClient) SetFacebookConnection(ctx context.Context, req *connect.Request[v1.SetFacebookConnectionRequest]) (*connect.Response[v1.SetFacebookConnectionResponse], error) {
	return c.setFacebookConnection.CallUnary(ctx, req)
}

// DeleteAccount calls openmarket.api.v1.UserService.DeleteAccount.
func (c *userServiceClient) DeleteAccount(ctx context.Context, req *connect.Request[v1.DeleteAccountRequest]) (*connect.Response[v1.DeleteAccountResponse], error) {
	return c.deleteAccount.CallUnary(ctx, req)
}

// UserServiceHandler is an implementation of the openmarket.api.v1.UserService service.
type UserServiceHandler interface {
	GetViewer(context.Context, *connect.Request[v1.GetViewerRequest]) (*connect.Response[v1.GetViewerResponse], error)
	UpdateViewer(context.Context, *connect.Request[v1.UpdateViewerRequest]) (*connect.Response[v1.UpdateViewerResponse], error)
	RegisterDeviceToken(context.Context, *connect.Request[v1.RegisterDeviceTokenRequest]) (*connect.Response[v1.RegisterDeviceTokenResponse], error)
	// Reports whether the Facebook webview session exists on this install. The
	// client is the only thing that can know — the state is a cookie jar it owns —
	// so this is a report, not a request to change anything.
	SetFacebookConnection(context.Context, *connect.Request[v1.SetFacebookConnectionRequest]) (*connect.Response[v1.SetFacebookConnectionResponse], error)
	// Required by App Store Guideline 5.1.1(v): an app that creates an account
	// must let the user delete it in-app.
	DeleteAccount(context.Context, *connect.Request[v1.DeleteAccountRequest]) (*connect.Response[v1.DeleteAccountResponse], error)
}

// NewUserServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUserServiceHandler(svc UserServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	userServiceMethods := v1.File_openmarket_api_v1_user_service_proto.Services().ByName("UserService").Methods()
	userServiceGetViewerHandler := connect.NewUnaryHandler(
		UserServiceGetViewerProcedure,
		svc.GetViewer,
		connect.WithSchema(userServiceMethods.ByName("GetViewer")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceUpdateViewerHandler := connect.NewUnaryHandler(
		UserServiceUpdateViewerProcedure,
		svc.UpdateViewer,
		connect.WithSchema(userServiceMethods.ByName("UpdateViewer")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceRegisterDeviceTokenHandler := connect.NewUnaryHandler(
		UserServiceRegisterDeviceTokenProcedure,
		svc.RegisterDeviceToken,
		connect.WithSchema(userServiceMethods.ByName("RegisterDeviceToken")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceSetFacebookConnectionHandler := connect.NewUnaryHandler(
		UserServiceSetFacebookConnectionProcedure,
		svc.SetFacebookConnection,
		connect.WithSchema(userServiceMethods.ByName("SetFacebookConnection")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceDeleteAccountHandler := connect.NewUnaryHandler(
		UserServiceDeleteAccountProcedure,
		svc.DeleteAccount,
		connect.WithSchema(userServiceMethods.ByName("DeleteAccount")),
		connect.WithHandlerOptions(opts...),
	)
	return "/openmarket.api.v1.UserService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UserServiceGetViewerProcedure:
			userServiceGetViewerHandler.ServeHTTP(w, r)
		case UserServiceUpdateViewerProcedure:
			userServiceUpdateViewerHandler.ServeHTTP(w, r)
		case UserServiceRegisterDeviceTokenProcedure:
			userServiceRegisterDeviceTokenHandler.ServeHTTP(w, r)
		case UserServiceSetFacebookConnectionProcedure:
			userServiceSetFacebookConnectionHandler.ServeHTTP(w, r)
		case UserServiceDeleteAccountProcedure:
			userServiceDeleteAccountHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUserServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUserServiceHandler struct{}

func (UnimplementedUserServiceHandler) GetViewer(context.Context, *connect.Request[v1.GetViewerRequest]) (*connect.Response[v1.GetViewerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmarket.api.v1.UserService.GetViewer is not implemented"))
}

func (UnimplementedUserServiceHandler) UpdateViewer(context.Context, *connect.Request[v1.UpdateViewerRequest]) (*connect.Response[v1.UpdateViewerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmarket.api.v1.UserService.UpdateViewer is not implemented"))
}

func (UnimplementedUserServiceHandler) RegisterDeviceToken(context.Context, *connect.Request[v1.RegisterDeviceTokenRequest]) (*connect.Response[v1.RegisterDeviceTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmarket.api.v1.UserService.RegisterDeviceToken is not implemented"))
}

func (UnimplementedUserServiceHandler) SetFacebookConnection(context.Context, *connect.Request[v1.SetFacebookConnectionRequest]) (*connect.Response[v1.SetFacebookConnectionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmarket.api.v1.UserService.SetFacebookConnection is not implemented"))
}

func (UnimplementedUserServiceHandler) DeleteAccount(context.Context, *connect.Request[v1.DeleteAccountRequest]) (*connect.Response[v1.DeleteAccountResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmarket.api.v1.UserService.DeleteAccount is not implemented"))
}
