// Hand-written. Everything else in this target is generated by `buf generate`
// and will be overwritten; this file is not, because buf only writes the paths
// it owns (openmarket/…, buf/…).
//
// protoc-gen-swift derives type names from the proto package, so every message
// arrives as `Openmarket_Api_V1_Something`. That prefix would spread through
// every call site in the app for no benefit, so it is renamed once, here.

public typealias AuthServiceClient = Openmarket_Api_V1_AuthServiceClient
public typealias UserServiceClient = Openmarket_Api_V1_UserServiceClient

public typealias Viewer = Openmarket_Api_V1_Viewer
public typealias Device = Openmarket_Api_V1_Device
public typealias DevicePlatform = Openmarket_Api_V1_DevicePlatform
public typealias NotificationPermissionStatus = Openmarket_Api_V1_NotificationPermissionStatus

public typealias StartPhoneVerificationRequest = Openmarket_Api_V1_StartPhoneVerificationRequest
public typealias StartPhoneVerificationResponse = Openmarket_Api_V1_StartPhoneVerificationResponse
public typealias VerifyPhoneRequest = Openmarket_Api_V1_VerifyPhoneRequest
public typealias VerifyPhoneResponse = Openmarket_Api_V1_VerifyPhoneResponse
public typealias RefreshTokenRequest = Openmarket_Api_V1_RefreshTokenRequest
public typealias RefreshTokenResponse = Openmarket_Api_V1_RefreshTokenResponse
public typealias LogoutRequest = Openmarket_Api_V1_LogoutRequest

public typealias GetViewerRequest = Openmarket_Api_V1_GetViewerRequest
public typealias UpdateViewerRequest = Openmarket_Api_V1_UpdateViewerRequest
public typealias RegisterDeviceTokenRequest = Openmarket_Api_V1_RegisterDeviceTokenRequest
public typealias SetFacebookConnectionRequest = Openmarket_Api_V1_SetFacebookConnectionRequest
public typealias DeleteAccountRequest = Openmarket_Api_V1_DeleteAccountRequest
