// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const clearDevicePushTokenElsewhere = `-- name: ClearDevicePushTokenElsewhere :exec
UPDATE user_devices
SET push_token = NULL,
    push_token_updated_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE push_token = $1
  AND id <> $2
`

type ClearDevicePushTokenElsewhereParams struct {
	PushToken *string
	ID        uuid.UUID
}

// The same token can migrate between rows — one phone, two accounts. The unique
// index would reject the new holder, so the old one is cleared first, in the
// same transaction.
func (q *Queries) ClearDevicePushTokenElsewhere(ctx context.Context, arg ClearDevicePushTokenElsewhereParams) error {
	_, err := q.db.Exec(ctx, clearDevicePushTokenElsewhere, arg.PushToken, arg.ID)
	return err
}

const getDeviceForSession = `-- name: GetDeviceForSession :one
SELECT d.id, d.user_id, d.install_id, d.platform, d.facebook_connected, d.facebook_connected_at, d.facebook_disconnected_at, d.push_token, d.push_token_updated_at, d.notification_permission_status, d.created_at, d.updated_at, d.last_seen_at
FROM user_devices d
JOIN user_sessions s ON s.device_id = d.id
WHERE s.id = $1
`

// Every authenticated call already carries a session, and the session knows its
// device — so the client never has to send install_id again after login, and
// cannot claim to be a device it isn't.
func (q *Queries) GetDeviceForSession(ctx context.Context, id uuid.UUID) (UserDevice, error) {
	row := q.db.QueryRow(ctx, getDeviceForSession, id)
	var i UserDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstallID,
		&i.Platform,
		&i.FacebookConnected,
		&i.FacebookConnectedAt,
		&i.FacebookDisconnectedAt,
		&i.PushToken,
		&i.PushTokenUpdatedAt,
		&i.NotificationPermissionStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const setDeviceFacebookConnection = `-- name: SetDeviceFacebookConnection :one
UPDATE user_devices
SET facebook_connected = $2::boolean,
    facebook_connected_at = CASE
        WHEN $2::boolean AND NOT facebook_connected
            THEN CURRENT_TIMESTAMP
        ELSE facebook_connected_at
    END,
    facebook_disconnected_at = CASE
        WHEN NOT $2::boolean AND facebook_connected
            THEN CURRENT_TIMESTAMP
        ELSE facebook_disconnected_at
    END,
    last_seen_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, user_id, install_id, platform, facebook_connected, facebook_connected_at, facebook_disconnected_at, push_token, push_token_updated_at, notification_permission_status, created_at, updated_at, last_seen_at
`

type SetDeviceFacebookConnectionParams struct {
	ID        uuid.UUID
	Connected bool
}

// Idempotent: reporting the state it already holds leaves the timestamps alone,
// so a client that reports on every foreground doesn't rewrite history.
func (q *Queries) SetDeviceFacebookConnection(ctx context.Context, arg SetDeviceFacebookConnectionParams) (UserDevice, error) {
	row := q.db.QueryRow(ctx, setDeviceFacebookConnection, arg.ID, arg.Connected)
	var i UserDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstallID,
		&i.Platform,
		&i.FacebookConnected,
		&i.FacebookConnectedAt,
		&i.FacebookDisconnectedAt,
		&i.PushToken,
		&i.PushTokenUpdatedAt,
		&i.NotificationPermissionStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const setSessionDevice = `-- name: SetSessionDevice :exec
UPDATE user_sessions
SET device_id = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type SetSessionDeviceParams struct {
	ID       uuid.UUID
	DeviceID *uuid.UUID
}

func (q *Queries) SetSessionDevice(ctx context.Context, arg SetSessionDeviceParams) error {
	_, err := q.db.Exec(ctx, setSessionDevice, arg.ID, arg.DeviceID)
	return err
}

const updateDevicePushToken = `-- name: UpdateDevicePushToken :exec
UPDATE user_devices
SET push_token = $2,
    push_token_updated_at = CURRENT_TIMESTAMP,
    notification_permission_status = $3,
    last_seen_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateDevicePushTokenParams struct {
	ID                           uuid.UUID
	PushToken                    *string
	NotificationPermissionStatus NotificationPermissionStatus
}

func (q *Queries) UpdateDevicePushToken(ctx context.Context, arg UpdateDevicePushTokenParams) error {
	_, err := q.db.Exec(ctx, updateDevicePushToken, arg.ID, arg.PushToken, arg.NotificationPermissionStatus)
	return err
}

const upsertDevice = `-- name: UpsertDevice :one
INSERT INTO user_devices (user_id, install_id, platform)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, install_id) DO UPDATE
SET platform = EXCLUDED.platform,
    last_seen_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, user_id, install_id, platform, facebook_connected, facebook_connected_at, facebook_disconnected_at, push_token, push_token_updated_at, notification_permission_status, created_at, updated_at, last_seen_at
`

type UpsertDeviceParams struct {
	UserID    uuid.UUID
	InstallID string
	Platform  DevicePlatform
}

// Called at login. The install is the identity, so signing in again on the same
// phone finds the existing row and keeps its Facebook and push state rather than
// starting a second one.
func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (UserDevice, error) {
	row := q.db.QueryRow(ctx, upsertDevice, arg.UserID, arg.InstallID, arg.Platform)
	var i UserDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstallID,
		&i.Platform,
		&i.FacebookConnected,
		&i.FacebookConnectedAt,
		&i.FacebookDisconnectedAt,
		&i.PushToken,
		&i.PushTokenUpdatedAt,
		&i.NotificationPermissionStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
	)
	return i, err
}
