// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingest.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bumpDeviceActivity = `-- name: BumpDeviceActivity :one
INSERT INTO device_activity (device_id, day, batches, cards)
VALUES ($1, CURRENT_DATE, 1, $2::int)
ON CONFLICT (device_id, day) DO UPDATE
SET batches = device_activity.batches + 1,
    cards = device_activity.cards + EXCLUDED.cards
RETURNING device_id, day, batches, cards
`

type BumpDeviceActivityParams struct {
	DeviceID uuid.UUID
	Cards    int32
}

// The volume half of the split. No listing ids reach this table, which is why
// rate limiting can read the real device id without reading a history.
func (q *Queries) BumpDeviceActivity(ctx context.Context, arg BumpDeviceActivityParams) (DeviceActivity, error) {
	row := q.db.QueryRow(ctx, bumpDeviceActivity, arg.DeviceID, arg.Cards)
	var i DeviceActivity
	err := row.Scan(
		&i.DeviceID,
		&i.Day,
		&i.Batches,
		&i.Cards,
	)
	return i, err
}

const countBatchesWithShapeFingerprint = `-- name: CountBatchesWithShapeFingerprint :one
SELECT COUNT(*)::bigint AS seen
FROM observation_batches
WHERE facebook_browser_variant = $1
  AND facebook_page_route = $2
  AND extraction_method = $3
  AND shape_fingerprint = $4
  AND received_at > CURRENT_TIMESTAMP - $5::interval
`

type CountBatchesWithShapeFingerprintParams struct {
	BrowserVariant   string
	PageRoute        string
	ExtractionMethod string
	ShapeFingerprint []byte
	Window           pgtype.Interval
}

// A shape fingerprint nobody has seen on this surface is Facebook shipping a
// change, and it is worth saying so whether or not anything failed to parse.
func (q *Queries) CountBatchesWithShapeFingerprint(ctx context.Context, arg CountBatchesWithShapeFingerprintParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBatchesWithShapeFingerprint,
		arg.BrowserVariant,
		arg.PageRoute,
		arg.ExtractionMethod,
		arg.ShapeFingerprint,
		arg.Window,
	)
	var seen int64
	err := row.Scan(&seen)
	return seen, err
}

const createIngestEpochKey = `-- name: CreateIngestEpochKey :one
INSERT INTO ingest_epoch_keys (epoch, key, expires_at)
VALUES ($1, $2, $3)
ON CONFLICT (epoch) DO UPDATE SET epoch = EXCLUDED.epoch
RETURNING epoch, key, created_at, expires_at
`

type CreateIngestEpochKeyParams struct {
	Epoch     pgtype.Date
	Key       []byte
	ExpiresAt pgtype.Timestamptz
}

// Get-or-create in one statement. Two instances minting the first pseudonym of
// an epoch at the same moment must end up with the same key, or the two halves
// of that epoch would never compare equal.
func (q *Queries) CreateIngestEpochKey(ctx context.Context, arg CreateIngestEpochKeyParams) (IngestEpochKey, error) {
	row := q.db.QueryRow(ctx, createIngestEpochKey, arg.Epoch, arg.Key, arg.ExpiresAt)
	var i IngestEpochKey
	err := row.Scan(
		&i.Epoch,
		&i.Key,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredIngestEpochKeys = `-- name: DeleteExpiredIngestEpochKeys :execrows
DELETE FROM ingest_epoch_keys WHERE expires_at <= CURRENT_TIMESTAMP
`

// The operation that makes the privacy claim true. Deliberately a hard delete:
// a key kept "just in case" is a key that still resolves.
func (q *Queries) DeleteExpiredIngestEpochKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIngestEpochKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIngestEpochKey = `-- name: GetIngestEpochKey :one
SELECT epoch, key, created_at, expires_at FROM ingest_epoch_keys WHERE epoch = $1
`

func (q *Queries) GetIngestEpochKey(ctx context.Context, epoch pgtype.Date) (IngestEpochKey, error) {
	row := q.db.QueryRow(ctx, getIngestEpochKey, epoch)
	var i IngestEpochKey
	err := row.Scan(
		&i.Epoch,
		&i.Key,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getOrCreateDeviceReputation = `-- name: GetOrCreateDeviceReputation :one
INSERT INTO device_reputation (device_id)
VALUES ($1)
ON CONFLICT (device_id) DO UPDATE
SET last_seen_at = CURRENT_TIMESTAMP
RETURNING device_id, batches_accepted, cards_accepted, cards_quarantined, conflicts_caused, tier, first_seen_at, last_seen_at
`

func (q *Queries) GetOrCreateDeviceReputation(ctx context.Context, deviceID uuid.UUID) (DeviceReputation, error) {
	row := q.db.QueryRow(ctx, getOrCreateDeviceReputation, deviceID)
	var i DeviceReputation
	err := row.Scan(
		&i.DeviceID,
		&i.BatchesAccepted,
		&i.CardsAccepted,
		&i.CardsQuarantined,
		&i.ConflictsCaused,
		&i.Tier,
		&i.FirstSeenAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getSourceHealth = `-- name: GetSourceHealth :one
SELECT
    COALESCE(SUM(cards_submitted), 0)::bigint AS submitted,
    COALESCE(SUM(cards_quarantined), 0)::bigint AS quarantined,
    COUNT(*)::bigint AS batches
FROM observation_batches
WHERE facebook_browser_variant = $1
  AND facebook_page_route = $2
  AND extraction_method = $3
  AND extractor_revision = $4
  AND received_at > CURRENT_TIMESTAMP - $5::interval
`

type GetSourceHealthParams struct {
	BrowserVariant    string
	PageRoute         string
	ExtractionMethod  string
	ExtractorRevision string
	Window            pgtype.Interval
}

type GetSourceHealthRow struct {
	Submitted   int64
	Quarantined int64
	Batches     int64
}

// The circuit breaker's input: how this extractor is doing on this surface over
// a window. Counted from batches rather than from quarantine rows so a batch
// that was refused whole still registers.
func (q *Queries) GetSourceHealth(ctx context.Context, arg GetSourceHealthParams) (GetSourceHealthRow, error) {
	row := q.db.QueryRow(ctx, getSourceHealth,
		arg.BrowserVariant,
		arg.PageRoute,
		arg.ExtractionMethod,
		arg.ExtractorRevision,
		arg.Window,
	)
	var i GetSourceHealthRow
	err := row.Scan(&i.Submitted, &i.Quarantined, &i.Batches)
	return i, err
}

const pruneDeviceActivity = `-- name: PruneDeviceActivity :execrows
DELETE FROM device_activity WHERE day < (CURRENT_DATE - $1::int)
`

func (q *Queries) PruneDeviceActivity(ctx context.Context, keepDays int32) (int64, error) {
	result, err := q.db.Exec(ctx, pruneDeviceActivity, keepDays)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordBatchOutcome = `-- name: RecordBatchOutcome :exec
UPDATE device_reputation
SET batches_accepted = batches_accepted + 1,
    cards_accepted = cards_accepted + $1::bigint,
    cards_quarantined = cards_quarantined + $2::bigint,
    conflicts_caused = conflicts_caused + $3::bigint,
    last_seen_at = CURRENT_TIMESTAMP
WHERE device_id = $4
`

type RecordBatchOutcomeParams struct {
	Accepted    int64
	Quarantined int64
	Conflicts   int64
	DeviceID    uuid.UUID
}

func (q *Queries) RecordBatchOutcome(ctx context.Context, arg RecordBatchOutcomeParams) error {
	_, err := q.db.Exec(ctx, recordBatchOutcome,
		arg.Accepted,
		arg.Quarantined,
		arg.Conflicts,
		arg.DeviceID,
	)
	return err
}

const setDeviceTrustTier = `-- name: SetDeviceTrustTier :exec
UPDATE device_reputation SET tier = $2 WHERE device_id = $1
`

type SetDeviceTrustTierParams struct {
	DeviceID uuid.UUID
	Tier     IngestTrustTier
}

func (q *Queries) SetDeviceTrustTier(ctx context.Context, arg SetDeviceTrustTierParams) error {
	_, err := q.db.Exec(ctx, setDeviceTrustTier, arg.DeviceID, arg.Tier)
	return err
}
