// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listing.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const attachListingAliases = `-- name: AttachListingAliases :one
UPDATE listings
SET facebook_listing_id = COALESCE(facebook_listing_id, $1),
    cover_photo_fbid = COALESCE(cover_photo_fbid, $2),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $3
RETURNING id, origin, owner_id, facebook_listing_id, cover_photo_fbid, title, description, condition, category_path, facebook_category_id, price_minor, price_currency, price_formatted, previous_price_minor, price_changed_at, availability, availability_raw, sold_not_before, sold_not_after, delivery_types, listing_location_text, listing_city, listing_region, listing_country, facebook_place_id, listing_approx_lat, listing_approx_lon, seller_id, listed_at, listed_at_text, listed_at_precision, first_observed_at, last_observed_at, detail_observed_at, moderation_state, deleted_at, created_at, updated_at, price_observed_at, availability_observed_at
`

type AttachListingAliasesParams struct {
	FacebookListingID *string
	CoverPhotoFbid    *string
	ID                uuid.UUID
}

// An observation joined by one alias and carrying the other attaches it. A
// disagreement is never resolved here: the caller checks first and quarantines,
// because last-writer-wins on an alias silently merges two listings.
func (q *Queries) AttachListingAliases(ctx context.Context, arg AttachListingAliasesParams) (Listing, error) {
	row := q.db.QueryRow(ctx, attachListingAliases, arg.FacebookListingID, arg.CoverPhotoFbid, arg.ID)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.Origin,
		&i.OwnerID,
		&i.FacebookListingID,
		&i.CoverPhotoFbid,
		&i.Title,
		&i.Description,
		&i.Condition,
		&i.CategoryPath,
		&i.FacebookCategoryID,
		&i.PriceMinor,
		&i.PriceCurrency,
		&i.PriceFormatted,
		&i.PreviousPriceMinor,
		&i.PriceChangedAt,
		&i.Availability,
		&i.AvailabilityRaw,
		&i.SoldNotBefore,
		&i.SoldNotAfter,
		&i.DeliveryTypes,
		&i.ListingLocationText,
		&i.ListingCity,
		&i.ListingRegion,
		&i.ListingCountry,
		&i.FacebookPlaceID,
		&i.ListingApproxLat,
		&i.ListingApproxLon,
		&i.SellerID,
		&i.ListedAt,
		&i.ListedAtText,
		&i.ListedAtPrecision,
		&i.FirstObservedAt,
		&i.LastObservedAt,
		&i.DetailObservedAt,
		&i.ModerationState,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PriceObservedAt,
		&i.AvailabilityObservedAt,
	)
	return i, err
}

const claimFacebookProfileID = `-- name: ClaimFacebookProfileID :one
UPDATE sellers
SET facebook_profile_id = $1,
    updated_at = CURRENT_TIMESTAMP
WHERE sellers.id = $2
  AND sellers.facebook_profile_id IS NULL
  AND NOT EXISTS (SELECT 1 FROM sellers s2 WHERE s2.facebook_profile_id = $1)
RETURNING id, display_name, rating, joined_text, joined_year, rating_count, highly_rated, first_observed_at, last_observed_at, created_at, updated_at, facebook_profile_id
`

type ClaimFacebookProfileIDParams struct {
	FacebookProfileID *string
	ID                uuid.UUID
}

// Promotes an unresolved seller when a capture finally supplies the profile id.
// DO NOTHING on conflict: another row already holds that key, and merging two
// seller histories on a first sighting is a guess, so the caller repoints the
// listing instead.
func (q *Queries) ClaimFacebookProfileID(ctx context.Context, arg ClaimFacebookProfileIDParams) (Seller, error) {
	row := q.db.QueryRow(ctx, claimFacebookProfileID, arg.FacebookProfileID, arg.ID)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Rating,
		&i.JoinedText,
		&i.JoinedYear,
		&i.RatingCount,
		&i.HighlyRated,
		&i.FirstObservedAt,
		&i.LastObservedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FacebookProfileID,
	)
	return i, err
}

const createFacebookListing = `-- name: CreateFacebookListing :one
INSERT INTO listings (origin, facebook_listing_id, cover_photo_fbid, first_observed_at, last_observed_at)
VALUES ('facebook', $1, $2, $3, $3)
ON CONFLICT DO NOTHING
RETURNING id, origin, owner_id, facebook_listing_id, cover_photo_fbid, title, description, condition, category_path, facebook_category_id, price_minor, price_currency, price_formatted, previous_price_minor, price_changed_at, availability, availability_raw, sold_not_before, sold_not_after, delivery_types, listing_location_text, listing_city, listing_region, listing_country, facebook_place_id, listing_approx_lat, listing_approx_lon, seller_id, listed_at, listed_at_text, listed_at_precision, first_observed_at, last_observed_at, detail_observed_at, moderation_state, deleted_at, created_at, updated_at, price_observed_at, availability_observed_at
`

type CreateFacebookListingParams struct {
	FacebookListingID *string
	CoverPhotoFbid    *string
	FirstObservedAt   pgtype.Timestamptz
}

func (q *Queries) CreateFacebookListing(ctx context.Context, arg CreateFacebookListingParams) (Listing, error) {
	row := q.db.QueryRow(ctx, createFacebookListing, arg.FacebookListingID, arg.CoverPhotoFbid, arg.FirstObservedAt)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.Origin,
		&i.OwnerID,
		&i.FacebookListingID,
		&i.CoverPhotoFbid,
		&i.Title,
		&i.Description,
		&i.Condition,
		&i.CategoryPath,
		&i.FacebookCategoryID,
		&i.PriceMinor,
		&i.PriceCurrency,
		&i.PriceFormatted,
		&i.PreviousPriceMinor,
		&i.PriceChangedAt,
		&i.Availability,
		&i.AvailabilityRaw,
		&i.SoldNotBefore,
		&i.SoldNotAfter,
		&i.DeliveryTypes,
		&i.ListingLocationText,
		&i.ListingCity,
		&i.ListingRegion,
		&i.ListingCountry,
		&i.FacebookPlaceID,
		&i.ListingApproxLat,
		&i.ListingApproxLon,
		&i.SellerID,
		&i.ListedAt,
		&i.ListedAtText,
		&i.ListedAtPrecision,
		&i.FirstObservedAt,
		&i.LastObservedAt,
		&i.DetailObservedAt,
		&i.ModerationState,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PriceObservedAt,
		&i.AvailabilityObservedAt,
	)
	return i, err
}

const createUnresolvedSeller = `-- name: CreateUnresolvedSeller :one
INSERT INTO sellers (display_name, rating, joined_text, joined_year, rating_count,
                     highly_rated, first_observed_at, last_observed_at)
VALUES ($1, $2, $3,
        $4, $5, $6,
        $7, $7)
RETURNING id, display_name, rating, joined_text, joined_year, rating_count, highly_rated, first_observed_at, last_observed_at, created_at, updated_at, facebook_profile_id
`

type CreateUnresolvedSellerParams struct {
	DisplayName *string
	Rating      *float32
	JoinedText  *string
	JoinedYear  *int32
	RatingCount *int32
	HighlyRated *bool
	ObservedAt  pgtype.Timestamptz
}

// A seller observed without Facebook's profile id: mobile item pages publish
// the name and rating and no profile link at all. The row is deliberately not
// clustered — data-model.md §4 forbids grouping on (name, coordinate), because
// a listing's coordinate is not a seller's and names are not identities.
func (q *Queries) CreateUnresolvedSeller(ctx context.Context, arg CreateUnresolvedSellerParams) (Seller, error) {
	row := q.db.QueryRow(ctx, createUnresolvedSeller,
		arg.DisplayName,
		arg.Rating,
		arg.JoinedText,
		arg.JoinedYear,
		arg.RatingCount,
		arg.HighlyRated,
		arg.ObservedAt,
	)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Rating,
		&i.JoinedText,
		&i.JoinedYear,
		&i.RatingCount,
		&i.HighlyRated,
		&i.FirstObservedAt,
		&i.LastObservedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FacebookProfileID,
	)
	return i, err
}

const deleteListingMediaNotIn = `-- name: DeleteListingMediaNotIn :execrows
DELETE FROM listing_media
WHERE listing_id = $1
  AND facebook_photo_id IS NOT NULL
  AND NOT (facebook_photo_id = ANY ($2::text[]))
`

type DeleteListingMediaNotInParams struct {
	ListingID uuid.UUID
	Keep      []string
}

// Only a settled item-page capture may shrink a gallery. A search card carries
// one cover photo and a partial detail read carries whatever had loaded, so
// either would delete most of a listing's photos on every pass.
func (q *Queries) DeleteListingMediaNotIn(ctx context.Context, arg DeleteListingMediaNotInParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteListingMediaNotIn, arg.ListingID, arg.Keep)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getListingByCoverPhotoFBID = `-- name: GetListingByCoverPhotoFBID :one
SELECT id, origin, owner_id, facebook_listing_id, cover_photo_fbid, title, description, condition, category_path, facebook_category_id, price_minor, price_currency, price_formatted, previous_price_minor, price_changed_at, availability, availability_raw, sold_not_before, sold_not_after, delivery_types, listing_location_text, listing_city, listing_region, listing_country, facebook_place_id, listing_approx_lat, listing_approx_lon, seller_id, listed_at, listed_at_text, listed_at_precision, first_observed_at, last_observed_at, detail_observed_at, moderation_state, deleted_at, created_at, updated_at, price_observed_at, availability_observed_at FROM listings
WHERE origin = 'facebook' AND cover_photo_fbid = $1
`

func (q *Queries) GetListingByCoverPhotoFBID(ctx context.Context, coverPhotoFbid *string) (Listing, error) {
	row := q.db.QueryRow(ctx, getListingByCoverPhotoFBID, coverPhotoFbid)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.Origin,
		&i.OwnerID,
		&i.FacebookListingID,
		&i.CoverPhotoFbid,
		&i.Title,
		&i.Description,
		&i.Condition,
		&i.CategoryPath,
		&i.FacebookCategoryID,
		&i.PriceMinor,
		&i.PriceCurrency,
		&i.PriceFormatted,
		&i.PreviousPriceMinor,
		&i.PriceChangedAt,
		&i.Availability,
		&i.AvailabilityRaw,
		&i.SoldNotBefore,
		&i.SoldNotAfter,
		&i.DeliveryTypes,
		&i.ListingLocationText,
		&i.ListingCity,
		&i.ListingRegion,
		&i.ListingCountry,
		&i.FacebookPlaceID,
		&i.ListingApproxLat,
		&i.ListingApproxLon,
		&i.SellerID,
		&i.ListedAt,
		&i.ListedAtText,
		&i.ListedAtPrecision,
		&i.FirstObservedAt,
		&i.LastObservedAt,
		&i.DetailObservedAt,
		&i.ModerationState,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PriceObservedAt,
		&i.AvailabilityObservedAt,
	)
	return i, err
}

const getListingByFacebookID = `-- name: GetListingByFacebookID :one
SELECT id, origin, owner_id, facebook_listing_id, cover_photo_fbid, title, description, condition, category_path, facebook_category_id, price_minor, price_currency, price_formatted, previous_price_minor, price_changed_at, availability, availability_raw, sold_not_before, sold_not_after, delivery_types, listing_location_text, listing_city, listing_region, listing_country, facebook_place_id, listing_approx_lat, listing_approx_lon, seller_id, listed_at, listed_at_text, listed_at_precision, first_observed_at, last_observed_at, detail_observed_at, moderation_state, deleted_at, created_at, updated_at, price_observed_at, availability_observed_at FROM listings
WHERE origin = 'facebook' AND facebook_listing_id = $1
`

func (q *Queries) GetListingByFacebookID(ctx context.Context, facebookListingID *string) (Listing, error) {
	row := q.db.QueryRow(ctx, getListingByFacebookID, facebookListingID)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.Origin,
		&i.OwnerID,
		&i.FacebookListingID,
		&i.CoverPhotoFbid,
		&i.Title,
		&i.Description,
		&i.Condition,
		&i.CategoryPath,
		&i.FacebookCategoryID,
		&i.PriceMinor,
		&i.PriceCurrency,
		&i.PriceFormatted,
		&i.PreviousPriceMinor,
		&i.PriceChangedAt,
		&i.Availability,
		&i.AvailabilityRaw,
		&i.SoldNotBefore,
		&i.SoldNotAfter,
		&i.DeliveryTypes,
		&i.ListingLocationText,
		&i.ListingCity,
		&i.ListingRegion,
		&i.ListingCountry,
		&i.FacebookPlaceID,
		&i.ListingApproxLat,
		&i.ListingApproxLon,
		&i.SellerID,
		&i.ListedAt,
		&i.ListedAtText,
		&i.ListedAtPrecision,
		&i.FirstObservedAt,
		&i.LastObservedAt,
		&i.DetailObservedAt,
		&i.ModerationState,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PriceObservedAt,
		&i.AvailabilityObservedAt,
	)
	return i, err
}

const listListingMedia = `-- name: ListListingMedia :many
SELECT id, listing_id, facebook_photo_id, storage_key, kind, position, last_source_url, last_source_url_at, first_observed_at, last_observed_at FROM listing_media WHERE listing_id = $1 ORDER BY position NULLS LAST, first_observed_at
`

func (q *Queries) ListListingMedia(ctx context.Context, listingID uuid.UUID) ([]ListingMedium, error) {
	rows, err := q.db.Query(ctx, listListingMedia, listingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListingMedium
	for rows.Next() {
		var i ListingMedium
		if err := rows.Scan(
			&i.ID,
			&i.ListingID,
			&i.FacebookPhotoID,
			&i.StorageKey,
			&i.Kind,
			&i.Position,
			&i.LastSourceUrl,
			&i.LastSourceUrlAt,
			&i.FirstObservedAt,
			&i.LastObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockListing = `-- name: LockListing :one
SELECT id, origin, owner_id, facebook_listing_id, cover_photo_fbid, title, description, condition, category_path, facebook_category_id, price_minor, price_currency, price_formatted, previous_price_minor, price_changed_at, availability, availability_raw, sold_not_before, sold_not_after, delivery_types, listing_location_text, listing_city, listing_region, listing_country, facebook_place_id, listing_approx_lat, listing_approx_lon, seller_id, listed_at, listed_at_text, listed_at_precision, first_observed_at, last_observed_at, detail_observed_at, moderation_state, deleted_at, created_at, updated_at, price_observed_at, availability_observed_at FROM listings WHERE id = $1 FOR UPDATE
`

// The merge reads the current row, decides per field group, and writes once.
// Two devices observing one listing at the same moment must not interleave
// inside that, or a partial observation can erase a richer fact it never saw.
func (q *Queries) LockListing(ctx context.Context, id uuid.UUID) (Listing, error) {
	row := q.db.QueryRow(ctx, lockListing, id)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.Origin,
		&i.OwnerID,
		&i.FacebookListingID,
		&i.CoverPhotoFbid,
		&i.Title,
		&i.Description,
		&i.Condition,
		&i.CategoryPath,
		&i.FacebookCategoryID,
		&i.PriceMinor,
		&i.PriceCurrency,
		&i.PriceFormatted,
		&i.PreviousPriceMinor,
		&i.PriceChangedAt,
		&i.Availability,
		&i.AvailabilityRaw,
		&i.SoldNotBefore,
		&i.SoldNotAfter,
		&i.DeliveryTypes,
		&i.ListingLocationText,
		&i.ListingCity,
		&i.ListingRegion,
		&i.ListingCountry,
		&i.FacebookPlaceID,
		&i.ListingApproxLat,
		&i.ListingApproxLon,
		&i.SellerID,
		&i.ListedAt,
		&i.ListedAtText,
		&i.ListedAtPrecision,
		&i.FirstObservedAt,
		&i.LastObservedAt,
		&i.DetailObservedAt,
		&i.ModerationState,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PriceObservedAt,
		&i.AvailabilityObservedAt,
	)
	return i, err
}

const updateListingFromObservation = `-- name: UpdateListingFromObservation :one
UPDATE listings
SET title = $1,
    description = $2,
    condition = $3,
    category_path = $4,
    facebook_category_id = $5,
    price_minor = $6,
    price_currency = $7,
    price_formatted = $8,
    previous_price_minor = $9,
    price_changed_at = $10,
    price_observed_at = $11,
    availability = $12,
    availability_raw = $13,
    availability_observed_at = $14,
    sold_not_before = $15,
    sold_not_after = $16,
    delivery_types = $17,
    listing_location_text = $18,
    listing_city = $19,
    listing_region = $20,
    listing_country = $21,
    facebook_place_id = $22,
    listing_approx_lat = $23,
    listing_approx_lon = $24,
    seller_id = $25,
    listed_at = $26,
    listed_at_text = $27,
    listed_at_precision = $28,
    first_observed_at = $29,
    last_observed_at = $30,
    detail_observed_at = $31,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $32
RETURNING id, origin, owner_id, facebook_listing_id, cover_photo_fbid, title, description, condition, category_path, facebook_category_id, price_minor, price_currency, price_formatted, previous_price_minor, price_changed_at, availability, availability_raw, sold_not_before, sold_not_after, delivery_types, listing_location_text, listing_city, listing_region, listing_country, facebook_place_id, listing_approx_lat, listing_approx_lon, seller_id, listed_at, listed_at_text, listed_at_precision, first_observed_at, last_observed_at, detail_observed_at, moderation_state, deleted_at, created_at, updated_at, price_observed_at, availability_observed_at
`

type UpdateListingFromObservationParams struct {
	Title                  *string
	Description            *string
	Condition              *string
	CategoryPath           []string
	FacebookCategoryID     *string
	PriceMinor             *int64
	PriceCurrency          *string
	PriceFormatted         *string
	PreviousPriceMinor     *int64
	PriceChangedAt         pgtype.Timestamptz
	PriceObservedAt        pgtype.Timestamptz
	Availability           ListingAvailability
	AvailabilityRaw        *string
	AvailabilityObservedAt pgtype.Timestamptz
	SoldNotBefore          pgtype.Timestamptz
	SoldNotAfter           pgtype.Timestamptz
	DeliveryTypes          []string
	ListingLocationText    *string
	ListingCity            *string
	ListingRegion          *string
	ListingCountry         *string
	FacebookPlaceID        *string
	ListingApproxLat       *float64
	ListingApproxLon       *float64
	SellerID               *uuid.UUID
	ListedAt               pgtype.Timestamptz
	ListedAtText           *string
	ListedAtPrecision      *ListedAtPrecision
	FirstObservedAt        pgtype.Timestamptz
	LastObservedAt         pgtype.Timestamptz
	DetailObservedAt       pgtype.Timestamptz
	ID                     uuid.UUID
}

// Every mergeable column, written once. The decisions are made in Go — which
// source outranks which for a field, whether a value is richer than the one
// already stored — because they are conditional per field group and a SQL
// expression that encoded them would be unreadable and untestable.
func (q *Queries) UpdateListingFromObservation(ctx context.Context, arg UpdateListingFromObservationParams) (Listing, error) {
	row := q.db.QueryRow(ctx, updateListingFromObservation,
		arg.Title,
		arg.Description,
		arg.Condition,
		arg.CategoryPath,
		arg.FacebookCategoryID,
		arg.PriceMinor,
		arg.PriceCurrency,
		arg.PriceFormatted,
		arg.PreviousPriceMinor,
		arg.PriceChangedAt,
		arg.PriceObservedAt,
		arg.Availability,
		arg.AvailabilityRaw,
		arg.AvailabilityObservedAt,
		arg.SoldNotBefore,
		arg.SoldNotAfter,
		arg.DeliveryTypes,
		arg.ListingLocationText,
		arg.ListingCity,
		arg.ListingRegion,
		arg.ListingCountry,
		arg.FacebookPlaceID,
		arg.ListingApproxLat,
		arg.ListingApproxLon,
		arg.SellerID,
		arg.ListedAt,
		arg.ListedAtText,
		arg.ListedAtPrecision,
		arg.FirstObservedAt,
		arg.LastObservedAt,
		arg.DetailObservedAt,
		arg.ID,
	)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.Origin,
		&i.OwnerID,
		&i.FacebookListingID,
		&i.CoverPhotoFbid,
		&i.Title,
		&i.Description,
		&i.Condition,
		&i.CategoryPath,
		&i.FacebookCategoryID,
		&i.PriceMinor,
		&i.PriceCurrency,
		&i.PriceFormatted,
		&i.PreviousPriceMinor,
		&i.PriceChangedAt,
		&i.Availability,
		&i.AvailabilityRaw,
		&i.SoldNotBefore,
		&i.SoldNotAfter,
		&i.DeliveryTypes,
		&i.ListingLocationText,
		&i.ListingCity,
		&i.ListingRegion,
		&i.ListingCountry,
		&i.FacebookPlaceID,
		&i.ListingApproxLat,
		&i.ListingApproxLon,
		&i.SellerID,
		&i.ListedAt,
		&i.ListedAtText,
		&i.ListedAtPrecision,
		&i.FirstObservedAt,
		&i.LastObservedAt,
		&i.DetailObservedAt,
		&i.ModerationState,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PriceObservedAt,
		&i.AvailabilityObservedAt,
	)
	return i, err
}

const updateSellerFields = `-- name: UpdateSellerFields :one
UPDATE sellers
SET display_name = COALESCE($1, display_name),
    rating = COALESCE($2, rating),
    joined_text = COALESCE($3, joined_text),
    joined_year = COALESCE($4, joined_year),
    rating_count = COALESCE($5, rating_count),
    highly_rated = COALESCE($6, highly_rated),
    last_observed_at = GREATEST(last_observed_at, $7),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $8
RETURNING id, display_name, rating, joined_text, joined_year, rating_count, highly_rated, first_observed_at, last_observed_at, created_at, updated_at, facebook_profile_id
`

type UpdateSellerFieldsParams struct {
	DisplayName *string
	Rating      *float32
	JoinedText  *string
	JoinedYear  *int32
	RatingCount *int32
	HighlyRated *bool
	ObservedAt  pgtype.Timestamptz
	ID          uuid.UUID
}

// Fills gaps on a seller we already have. COALESCE in this order so a capture
// that could not see the section leaves what is known alone.
func (q *Queries) UpdateSellerFields(ctx context.Context, arg UpdateSellerFieldsParams) (Seller, error) {
	row := q.db.QueryRow(ctx, updateSellerFields,
		arg.DisplayName,
		arg.Rating,
		arg.JoinedText,
		arg.JoinedYear,
		arg.RatingCount,
		arg.HighlyRated,
		arg.ObservedAt,
		arg.ID,
	)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Rating,
		&i.JoinedText,
		&i.JoinedYear,
		&i.RatingCount,
		&i.HighlyRated,
		&i.FirstObservedAt,
		&i.LastObservedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FacebookProfileID,
	)
	return i, err
}

const upsertListingMedia = `-- name: UpsertListingMedia :exec
INSERT INTO listing_media (listing_id, facebook_photo_id, position, last_source_url, last_source_url_at, first_observed_at, last_observed_at)
VALUES ($1, $2, $3, $4, $5, $5, $5)
ON CONFLICT (listing_id, facebook_photo_id) WHERE facebook_photo_id IS NOT NULL
DO UPDATE
SET position = COALESCE(EXCLUDED.position, listing_media.position),
    last_source_url = COALESCE(EXCLUDED.last_source_url, listing_media.last_source_url),
    last_source_url_at = GREATEST(listing_media.last_source_url_at, EXCLUDED.last_source_url_at),
    last_observed_at = GREATEST(listing_media.last_observed_at, EXCLUDED.last_observed_at)
`

type UpsertListingMediaParams struct {
	ListingID       uuid.UUID
	FacebookPhotoID *string
	Position        *int32
	LastSourceUrl   *string
	LastSourceUrlAt pgtype.Timestamptz
}

// An fbcdn URL is an expiring locator, so the same photo id arriving with a new
// URL refreshes the locator and nothing else. A new photo id inserts.
func (q *Queries) UpsertListingMedia(ctx context.Context, arg UpsertListingMediaParams) error {
	_, err := q.db.Exec(ctx, upsertListingMedia,
		arg.ListingID,
		arg.FacebookPhotoID,
		arg.Position,
		arg.LastSourceUrl,
		arg.LastSourceUrlAt,
	)
	return err
}

const upsertSeller = `-- name: UpsertSeller :one
INSERT INTO sellers (facebook_profile_id, display_name, rating, joined_text, joined_year,
                     rating_count, highly_rated, first_observed_at, last_observed_at)
VALUES ($1, $2, $3,
        $4, $5, $6,
        $7, $8, $8)
ON CONFLICT (facebook_profile_id) WHERE facebook_profile_id IS NOT NULL DO UPDATE
SET display_name = COALESCE(EXCLUDED.display_name, sellers.display_name),
    rating = COALESCE(EXCLUDED.rating, sellers.rating),
    joined_text = COALESCE(EXCLUDED.joined_text, sellers.joined_text),
    joined_year = COALESCE(EXCLUDED.joined_year, sellers.joined_year),
    rating_count = COALESCE(EXCLUDED.rating_count, sellers.rating_count),
    highly_rated = COALESCE(EXCLUDED.highly_rated, sellers.highly_rated),
    last_observed_at = GREATEST(sellers.last_observed_at, EXCLUDED.last_observed_at),
    updated_at = CURRENT_TIMESTAMP
RETURNING id, display_name, rating, joined_text, joined_year, rating_count, highly_rated, first_observed_at, last_observed_at, created_at, updated_at, facebook_profile_id
`

type UpsertSellerParams struct {
	FacebookProfileID *string
	DisplayName       *string
	Rating            *float32
	JoinedText        *string
	JoinedYear        *int32
	RatingCount       *int32
	HighlyRated       *bool
	ObservedAt        pgtype.Timestamptz
}

// The exact profile id is Facebook's stable seller identity. It is intentionally
// stored even though it may require a signed-in surface to observe; see the
// documented data-minimization preference and exception.
//
// COALESCE in that order fills gaps without erasing: a capture that could not
// see the seller section passes NULL and leaves what is already known alone.
func (q *Queries) UpsertSeller(ctx context.Context, arg UpsertSellerParams) (Seller, error) {
	row := q.db.QueryRow(ctx, upsertSeller,
		arg.FacebookProfileID,
		arg.DisplayName,
		arg.Rating,
		arg.JoinedText,
		arg.JoinedYear,
		arg.RatingCount,
		arg.HighlyRated,
		arg.ObservedAt,
	)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Rating,
		&i.JoinedText,
		&i.JoinedYear,
		&i.RatingCount,
		&i.HighlyRated,
		&i.FirstObservedAt,
		&i.LastObservedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FacebookProfileID,
	)
	return i, err
}
