// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pricecheck.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addPriceCheckPhoto = `-- name: AddPriceCheckPhoto :exec
INSERT INTO price_check_photos (
    price_check_id,
    ordinal,
    sha256,
    bytes,
    width,
    height
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
`

type AddPriceCheckPhotoParams struct {
	PriceCheckID uuid.UUID
	Ordinal      int16
	Sha256       []byte
	Bytes        int32
	Width        int32
	Height       int32
}

// One row per photo, shape only — see migration 00007. Called in a loop rather
// than as a batch because there are at most three of them, and a failure to
// record photo metadata must not lose the price check it belongs to.
func (q *Queries) AddPriceCheckPhoto(ctx context.Context, arg AddPriceCheckPhotoParams) error {
	_, err := q.db.Exec(ctx, addPriceCheckPhoto,
		arg.PriceCheckID,
		arg.Ordinal,
		arg.Sha256,
		arg.Bytes,
		arg.Width,
		arg.Height,
	)
	return err
}

const completePriceCheck = `-- name: CompletePriceCheck :one
UPDATE price_checks
SET search_query_used = $1::text,
    comps_found = $2::int,
    sold_found = $3::int,
    recommended_price_minor = $4,
    median_price_minor = $5,
    currency_symbol = $6,
    completed_at = CURRENT_TIMESTAMP
WHERE id = $7
  AND user_id = $8
RETURNING id, user_id, device_id, description, identified_name, search_queries, search_query_used, comps_found, sold_found, recommended_price_minor, median_price_minor, currency_symbol, helpful, helpful_at, price_copied, price_copied_at, created_at, completed_at, listing_title, listing_description, copied_price_minor, copied_listing_title, copied_listing_description
`

type CompletePriceCheckParams struct {
	SearchQueryUsed       string
	CompsFound            int32
	SoldFound             int32
	RecommendedPriceMinor *int64
	MedianPriceMinor      *int64
	CurrencySymbol        *string
	ID                    uuid.UUID
	UserID                uuid.UUID
}

// The end of a successful run: what the market held, and what the device
// therefore recommended. `completed_at` is set here and nowhere else, so
// "finished" is a single fact rather than something inferred from whichever
// column happens to be non-null.
//
// Every number here is the client's word. The search runs in a WKWebView
// against the user's own Facebook session, so the server cannot check a single
// one of them — which was already true of the counts and is now true of the
// price as well, since the device computes it.
func (q *Queries) CompletePriceCheck(ctx context.Context, arg CompletePriceCheckParams) (PriceCheck, error) {
	row := q.db.QueryRow(ctx, completePriceCheck,
		arg.SearchQueryUsed,
		arg.CompsFound,
		arg.SoldFound,
		arg.RecommendedPriceMinor,
		arg.MedianPriceMinor,
		arg.CurrencySymbol,
		arg.ID,
		arg.UserID,
	)
	var i PriceCheck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.Description,
		&i.IdentifiedName,
		&i.SearchQueries,
		&i.SearchQueryUsed,
		&i.CompsFound,
		&i.SoldFound,
		&i.RecommendedPriceMinor,
		&i.MedianPriceMinor,
		&i.CurrencySymbol,
		&i.Helpful,
		&i.HelpfulAt,
		&i.PriceCopied,
		&i.PriceCopiedAt,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ListingTitle,
		&i.ListingDescription,
		&i.CopiedPriceMinor,
		&i.CopiedListingTitle,
		&i.CopiedListingDescription,
	)
	return i, err
}

const countLLMRunsForUser = `-- name: CountLLMRunsForUser :one
SELECT count(*)
FROM llm_runs
WHERE user_id = $1
  AND created_at > CURRENT_TIMESTAMP - $2::interval
`

type CountLLMRunsForUserParams struct {
	UserID uuid.UUID
	Window pgtype.Interval
}

// The ceiling. Counts calls rather than money, because there is no rate table
// yet — and calls are the right unit for the failure this actually guards
// against early on, which is a client stuck in a retry loop rather than a large
// bill. It becomes a cost ceiling later without moving the call site.
//
// Failed attempts count. A provider erroring after it has read the request has
// usually still charged for it, and a loop that only fails is the exact case
// this exists to stop.
func (q *Queries) CountLLMRunsForUser(ctx context.Context, arg CountLLMRunsForUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLLMRunsForUser, arg.UserID, arg.Window)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPriceCheck = `-- name: CreatePriceCheck :one

INSERT INTO price_checks (
    user_id,
    device_id,
    description
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, user_id, device_id, description, identified_name, search_queries, search_query_used, comps_found, sold_found, recommended_price_minor, median_price_minor, currency_symbol, helpful, helpful_at, price_copied, price_copied_at, created_at, completed_at, listing_title, listing_description, copied_price_minor, copied_listing_title, copied_listing_description
`

type CreatePriceCheckParams struct {
	UserID      uuid.UUID
	DeviceID    *uuid.UUID
	Description string
}

// Every mutation below matches on `user_id` as well as `id`, and returns the
// row. That is the authorization check, not a belt-and-braces addition to one:
// a caller who names someone else's price check gets no rows back, which the
// handler turns into NotFound. Doing it as a separate SELECT first would be two
// queries and a race.
// Written before the model is called, so a run that fails at the first call is
// still a row. The identify call is the expensive part and the part most likely
// to break; a table that only records successes cannot show that.
func (q *Queries) CreatePriceCheck(ctx context.Context, arg CreatePriceCheckParams) (PriceCheck, error) {
	row := q.db.QueryRow(ctx, createPriceCheck, arg.UserID, arg.DeviceID, arg.Description)
	var i PriceCheck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.Description,
		&i.IdentifiedName,
		&i.SearchQueries,
		&i.SearchQueryUsed,
		&i.CompsFound,
		&i.SoldFound,
		&i.RecommendedPriceMinor,
		&i.MedianPriceMinor,
		&i.CurrencySymbol,
		&i.Helpful,
		&i.HelpfulAt,
		&i.PriceCopied,
		&i.PriceCopiedAt,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ListingTitle,
		&i.ListingDescription,
		&i.CopiedPriceMinor,
		&i.CopiedListingTitle,
		&i.CopiedListingDescription,
	)
	return i, err
}

const deletePriceChecksForUser = `-- name: DeletePriceChecksForUser :exec
DELETE FROM price_checks
WHERE user_id = $1
`

// Everything this user ever asked us to price, gone.
//
// Called from DeleteAccount, and it has to be a DELETE rather than something
// that rides `users`: the account is **soft**-deleted, so the CASCADE on
// `price_checks.user_id` never fires. Migration 00004 said as much — the
// cascade only runs on a hard purge, and there isn't one — which was fine while
// the table held numbers and is not fine now that it holds descriptions the
// seller typed, listings a model wrote about their belongings, and hashes of
// their photos.
//
// Two follow-on effects, both wanted:
//
// `price_check_photos` goes with it, ON DELETE CASCADE (migration 00007). It is
// the shape of the photo and nothing else, but it is the shape of *their*
// photo.
//
// `llm_runs` does not. Its `price_check_id` is ON DELETE SET NULL by design, so
// the spend record survives the thing it was spent on — migration 00004 argued
// for that before this query existed, and it still holds: those rows are token
// counts and latencies, carrying nothing about the item, and a bill that
// rewrites itself when somebody leaves is not a bill.
func (q *Queries) DeletePriceChecksForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePriceChecksForUser, userID)
	return err
}

const getPriceCheck = `-- name: GetPriceCheck :one
SELECT id, user_id, device_id, description, identified_name, search_queries, search_query_used, comps_found, sold_found, recommended_price_minor, median_price_minor, currency_symbol, helpful, helpful_at, price_copied, price_copied_at, created_at, completed_at, listing_title, listing_description, copied_price_minor, copied_listing_title, copied_listing_description
FROM price_checks
WHERE id = $1
  AND user_id = $2
`

type GetPriceCheckParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetPriceCheck(ctx context.Context, arg GetPriceCheckParams) (PriceCheck, error) {
	row := q.db.QueryRow(ctx, getPriceCheck, arg.ID, arg.UserID)
	var i PriceCheck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.Description,
		&i.IdentifiedName,
		&i.SearchQueries,
		&i.SearchQueryUsed,
		&i.CompsFound,
		&i.SoldFound,
		&i.RecommendedPriceMinor,
		&i.MedianPriceMinor,
		&i.CurrencySymbol,
		&i.Helpful,
		&i.HelpfulAt,
		&i.PriceCopied,
		&i.PriceCopiedAt,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ListingTitle,
		&i.ListingDescription,
		&i.CopiedPriceMinor,
		&i.CopiedListingTitle,
		&i.CopiedListingDescription,
	)
	return i, err
}

const listPriceChecks = `-- name: ListPriceChecks :many
SELECT id, user_id, device_id, description, identified_name, search_queries, search_query_used, comps_found, sold_found, recommended_price_minor, median_price_minor, currency_symbol, helpful, helpful_at, price_copied, price_copied_at, created_at, completed_at, listing_title, listing_description, copied_price_minor, copied_listing_title, copied_listing_description
FROM price_checks
WHERE user_id = $1
  AND identified_name IS NOT NULL
ORDER BY created_at DESC
LIMIT $2
`

type ListPriceChecksParams struct {
	UserID uuid.UUID
	Limit  int32
}

// Recent runs for one user, newest first.
//
// Served entirely by `price_checks_user_id_idx (user_id, created_at DESC)`,
// which is why the ordering here is `created_at` and not `id` — the ids are
// uuidv7 and would sort the same way, but only one of the two is indexed.
//
// `identified_name IS NOT NULL` is the whole filter, and it is about what a
// person can recognise rather than about success. A row without one died in the
// model call, so it holds a description and nothing else; a row with one has a
// name, and usually a listing, even when the market came back empty. The
// unnamed ones are still in the table and still counted — they are just not
// something to hand back as "you checked this".
func (q *Queries) ListPriceChecks(ctx context.Context, arg ListPriceChecksParams) ([]PriceCheck, error) {
	rows, err := q.db.Query(ctx, listPriceChecks, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PriceCheck
	for rows.Next() {
		var i PriceCheck
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceID,
			&i.Description,
			&i.IdentifiedName,
			&i.SearchQueries,
			&i.SearchQueryUsed,
			&i.CompsFound,
			&i.SoldFound,
			&i.RecommendedPriceMinor,
			&i.MedianPriceMinor,
			&i.CurrencySymbol,
			&i.Helpful,
			&i.HelpfulAt,
			&i.PriceCopied,
			&i.PriceCopiedAt,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.ListingTitle,
			&i.ListingDescription,
			&i.CopiedPriceMinor,
			&i.CopiedListingTitle,
			&i.CopiedListingDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordLLMRun = `-- name: RecordLLMRun :one
INSERT INTO llm_runs (
    price_check_id,
    user_id,
    stage,
    attempt,
    provider,
    model,
    input_tokens,
    output_tokens,
    thought_tokens,
    cached_input_tokens,
    latency_ms,
    status,
    error_code
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
)
RETURNING id, price_check_id, user_id, stage, attempt, provider, model, input_tokens, output_tokens, cached_input_tokens, latency_ms, status, error_code, created_at, thought_tokens
`

type RecordLLMRunParams struct {
	PriceCheckID      *uuid.UUID
	UserID            uuid.UUID
	Stage             LlmRunStage
	Attempt           int32
	Provider          string
	Model             string
	InputTokens       *int32
	OutputTokens      *int32
	ThoughtTokens     *int32
	CachedInputTokens *int32
	LatencyMs         int32
	Status            LlmRunStatus
	ErrorCode         *string
}

// One row per call, including the ones that failed. Recorded after the call
// returns rather than around it: a row here is a statement that a request was
// served or refused, and a call that never left the process is a log line.
func (q *Queries) RecordLLMRun(ctx context.Context, arg RecordLLMRunParams) (LlmRun, error) {
	row := q.db.QueryRow(ctx, recordLLMRun,
		arg.PriceCheckID,
		arg.UserID,
		arg.Stage,
		arg.Attempt,
		arg.Provider,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.ThoughtTokens,
		arg.CachedInputTokens,
		arg.LatencyMs,
		arg.Status,
		arg.ErrorCode,
	)
	var i LlmRun
	err := row.Scan(
		&i.ID,
		&i.PriceCheckID,
		&i.UserID,
		&i.Stage,
		&i.Attempt,
		&i.Provider,
		&i.Model,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CachedInputTokens,
		&i.LatencyMs,
		&i.Status,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.ThoughtTokens,
	)
	return i, err
}

const recordPriceCheckCopy = `-- name: RecordPriceCheckCopy :one
UPDATE price_checks
SET price_copied = price_copied OR $1::bigint IS NOT NULL,
    price_copied_at = CASE
        WHEN $1::bigint IS NOT NULL
        THEN COALESCE(price_copied_at, CURRENT_TIMESTAMP)
        ELSE price_copied_at
    END,
    copied_price_minor = COALESCE($1::bigint, copied_price_minor),
    copied_listing_title = COALESCE($2, copied_listing_title),
    copied_listing_description = COALESCE($3, copied_listing_description)
WHERE id = $4
  AND user_id = $5
RETURNING id, user_id, device_id, description, identified_name, search_queries, search_query_used, comps_found, sold_found, recommended_price_minor, median_price_minor, currency_symbol, helpful, helpful_at, price_copied, price_copied_at, created_at, completed_at, listing_title, listing_description, copied_price_minor, copied_listing_title, copied_listing_description
`

type RecordPriceCheckCopyParams struct {
	CopiedPriceMinor         *int64
	CopiedListingTitle       *string
	CopiedListingDescription *string
	ID                       uuid.UUID
	UserID                   uuid.UUID
}

// One copy, of whatever was copied.
//
// Three rules in six lines, and each is deliberate:
//
// `price_copied` only goes true when a price came with the call. The flag has
// always meant "took the number", and a title copy is not that — letting it be
// set by any copy would quietly redefine every chart built on it.
//
// `price_copied_at` keeps the **first** value, because the question it answers
// is how long somebody took to act, and copying the same number again an hour
// later has not changed that.
//
// The three value columns take the **latest**, because somebody who copies,
// rewrites the title and copies again has changed their mind about exactly
// what these measure. COALESCE on the argument rather than the column, so a
// call carrying one field leaves the other two alone instead of blanking them.
//
// The `::bigint` casts are load-bearing rather than decoration. The first time
// this argument appears it is inside `IS NOT NULL`, which is a boolean context,
// and sqlc types the parameter from that first sighting — generating a `*bool`
// for a column holding money. Naming the type on every use pins it.
func (q *Queries) RecordPriceCheckCopy(ctx context.Context, arg RecordPriceCheckCopyParams) (PriceCheck, error) {
	row := q.db.QueryRow(ctx, recordPriceCheckCopy,
		arg.CopiedPriceMinor,
		arg.CopiedListingTitle,
		arg.CopiedListingDescription,
		arg.ID,
		arg.UserID,
	)
	var i PriceCheck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.Description,
		&i.IdentifiedName,
		&i.SearchQueries,
		&i.SearchQueryUsed,
		&i.CompsFound,
		&i.SoldFound,
		&i.RecommendedPriceMinor,
		&i.MedianPriceMinor,
		&i.CurrencySymbol,
		&i.Helpful,
		&i.HelpfulAt,
		&i.PriceCopied,
		&i.PriceCopiedAt,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ListingTitle,
		&i.ListingDescription,
		&i.CopiedPriceMinor,
		&i.CopiedListingTitle,
		&i.CopiedListingDescription,
	)
	return i, err
}

const setPriceCheckHelpful = `-- name: SetPriceCheckHelpful :one
UPDATE price_checks
SET helpful = $1,
    helpful_at = CURRENT_TIMESTAMP
WHERE id = $2
  AND user_id = $3
RETURNING id, user_id, device_id, description, identified_name, search_queries, search_query_used, comps_found, sold_found, recommended_price_minor, median_price_minor, currency_symbol, helpful, helpful_at, price_copied, price_copied_at, created_at, completed_at, listing_title, listing_description, copied_price_minor, copied_listing_title, copied_listing_description
`

type SetPriceCheckHelpfulParams struct {
	Helpful *bool
	ID      uuid.UUID
	UserID  uuid.UUID
}

// Overwrites, so changing the answer works — someone who taps "No" and then
// reconsiders should not be stuck with the first tap, and the alternative is a
// dead control that silently ignores them.
//
// `helpful_at` follows the current answer rather than recording the first, since
// the question it supports is "how long after the run did they judge it", and
// the judgement that counts is the one they left.
func (q *Queries) SetPriceCheckHelpful(ctx context.Context, arg SetPriceCheckHelpfulParams) (PriceCheck, error) {
	row := q.db.QueryRow(ctx, setPriceCheckHelpful, arg.Helpful, arg.ID, arg.UserID)
	var i PriceCheck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.Description,
		&i.IdentifiedName,
		&i.SearchQueries,
		&i.SearchQueryUsed,
		&i.CompsFound,
		&i.SoldFound,
		&i.RecommendedPriceMinor,
		&i.MedianPriceMinor,
		&i.CurrencySymbol,
		&i.Helpful,
		&i.HelpfulAt,
		&i.PriceCopied,
		&i.PriceCopiedAt,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ListingTitle,
		&i.ListingDescription,
		&i.CopiedPriceMinor,
		&i.CopiedListingTitle,
		&i.CopiedListingDescription,
	)
	return i, err
}

const setPriceCheckIdentification = `-- name: SetPriceCheckIdentification :one
UPDATE price_checks
SET identified_name = $1::text,
    search_queries = $2::text[],
    listing_title = $3::text,
    listing_description = $4::text
WHERE id = $5
  AND user_id = $6
RETURNING id, user_id, device_id, description, identified_name, search_queries, search_query_used, comps_found, sold_found, recommended_price_minor, median_price_minor, currency_symbol, helpful, helpful_at, price_copied, price_copied_at, created_at, completed_at, listing_title, listing_description, copied_price_minor, copied_listing_title, copied_listing_description
`

type SetPriceCheckIdentificationParams struct {
	IdentifiedName     string
	SearchQueries      []string
	ListingTitle       string
	ListingDescription string
	ID                 uuid.UUID
	UserID             uuid.UUID
}

// Everything the model produced, written where it is produced.
//
// Stored even though all of it is about to be handed straight back to the
// client: these are the columns that answer "we searched for the wrong thing"
// and "what did it actually write" months later, and the client's own copy is
// gone the moment the app is backgrounded.
//
// The listing lands here rather than at completion because this is the call
// that made it. A run that identifies an item and then finds no market still
// wrote a title and a description, and losing them because the search came back
// empty would be discarding the half that worked.
func (q *Queries) SetPriceCheckIdentification(ctx context.Context, arg SetPriceCheckIdentificationParams) (PriceCheck, error) {
	row := q.db.QueryRow(ctx, setPriceCheckIdentification,
		arg.IdentifiedName,
		arg.SearchQueries,
		arg.ListingTitle,
		arg.ListingDescription,
		arg.ID,
		arg.UserID,
	)
	var i PriceCheck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.Description,
		&i.IdentifiedName,
		&i.SearchQueries,
		&i.SearchQueryUsed,
		&i.CompsFound,
		&i.SoldFound,
		&i.RecommendedPriceMinor,
		&i.MedianPriceMinor,
		&i.CurrencySymbol,
		&i.Helpful,
		&i.HelpfulAt,
		&i.PriceCopied,
		&i.PriceCopiedAt,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ListingTitle,
		&i.ListingDescription,
		&i.CopiedPriceMinor,
		&i.CopiedListingTitle,
		&i.CopiedListingDescription,
	)
	return i, err
}

const sumLLMTokensForUser = `-- name: SumLLMTokensForUser :one
SELECT
    coalesce(sum(input_tokens), 0)::bigint AS input_tokens,
    coalesce(sum(output_tokens), 0)::bigint AS output_tokens,
    coalesce(sum(thought_tokens), 0)::bigint AS thought_tokens,
    coalesce(sum(cached_input_tokens), 0)::bigint AS cached_input_tokens
FROM llm_runs
WHERE user_id = $1
  AND created_at > CURRENT_TIMESTAMP - $2::interval
`

type SumLLMTokensForUserParams struct {
	UserID uuid.UUID
	Window pgtype.Interval
}

type SumLLMTokensForUserRow struct {
	InputTokens       int64
	OutputTokens      int64
	ThoughtTokens     int64
	CachedInputTokens int64
}

// Same window, by tokens. Not wired to anything yet — it is here because it is
// the query the ceiling turns into once a rate table exists, and writing it
// beside the count is how the two stay honest about counting the same rows.
func (q *Queries) SumLLMTokensForUser(ctx context.Context, arg SumLLMTokensForUserParams) (SumLLMTokensForUserRow, error) {
	row := q.db.QueryRow(ctx, sumLLMTokensForUser, arg.UserID, arg.Window)
	var i SumLLMTokensForUserRow
	err := row.Scan(
		&i.InputTokens,
		&i.OutputTokens,
		&i.ThoughtTokens,
		&i.CachedInputTokens,
	)
	return i, err
}
