// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkActiveSession = `-- name: CheckActiveSession :one
SELECT s.id
FROM user_sessions s
JOIN users u ON u.id = s.user_id
WHERE s.id = $1
  AND s.user_id = $2
  AND s.revoked_at IS NULL
  AND u.deleted_at IS NULL
`

type CheckActiveSessionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Called on every authenticated RPC. Returns the session id or no rows; the
// interceptor treats no-rows as unauthenticated so a revoked session stops
// working immediately rather than at access-token expiry.
func (q *Queries) CheckActiveSession(ctx context.Context, arg CheckActiveSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, checkActiveSession, arg.ID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO user_sessions (
    user_id,
    refresh_token_hash,
    refresh_token_expires_at,
    device_platform
)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, refresh_token_hash, refresh_token_expires_at, device_platform, created_at, updated_at, last_used_at, revoked_at, device_id
`

type CreateSessionParams struct {
	UserID                uuid.UUID
	RefreshTokenHash      string
	RefreshTokenExpiresAt pgtype.Timestamptz
	DevicePlatform        DevicePlatform
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.RefreshTokenExpiresAt,
		arg.DevicePlatform,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.RefreshTokenExpiresAt,
		&i.DevicePlatform,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.DeviceID,
	)
	return i, err
}

const getSessionByRefreshTokenHash = `-- name: GetSessionByRefreshTokenHash :one
SELECT s.id, s.user_id, s.refresh_token_hash, s.refresh_token_expires_at, s.device_platform, s.created_at, s.updated_at, s.last_used_at, s.revoked_at, s.device_id
FROM user_sessions s
JOIN users u ON u.id = s.user_id
WHERE s.refresh_token_hash = $1
  AND s.revoked_at IS NULL
  AND s.refresh_token_expires_at > CURRENT_TIMESTAMP
  AND u.deleted_at IS NULL
`

func (q *Queries) GetSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (UserSession, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshTokenHash, refreshTokenHash)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.RefreshTokenExpiresAt,
		&i.DevicePlatform,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.DeviceID,
	)
	return i, err
}

const revokeAllSessionsForUser = `-- name: RevokeAllSessionsForUser :exec
UPDATE user_sessions
SET revoked_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE user_id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeAllSessionsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllSessionsForUser, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE user_sessions
SET revoked_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND user_id = $2
  AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.Exec(ctx, revokeSession, arg.ID, arg.UserID)
	return err
}

const rotateRefreshToken = `-- name: RotateRefreshToken :one
UPDATE user_sessions
SET refresh_token_hash = $2,
    refresh_token_expires_at = $3,
    last_used_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE refresh_token_hash = $1
  AND revoked_at IS NULL
RETURNING id, user_id, refresh_token_hash, refresh_token_expires_at, device_platform, created_at, updated_at, last_used_at, revoked_at, device_id
`

type RotateRefreshTokenParams struct {
	RefreshTokenHash      string
	RefreshTokenHash_2    string
	RefreshTokenExpiresAt pgtype.Timestamptz
}

// Rotation is a conditional update on the *old* hash, which makes it the
// concurrency control: two clients racing a refresh with the same token both
// run this, and only the first matches a row. The loser gets no rows and is
// told to re-authenticate rather than both being handed live sessions.
func (q *Queries) RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, rotateRefreshToken, arg.RefreshTokenHash, arg.RefreshTokenHash_2, arg.RefreshTokenExpiresAt)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.RefreshTokenExpiresAt,
		&i.DevicePlatform,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.DeviceID,
	)
	return i, err
}
