// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const clearUserDisplayName = `-- name: ClearUserDisplayName :one
UPDATE users
SET display_name = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, display_name, time_zone, onboarding_completed_at, created_at, updated_at, deleted_at
`

func (q *Queries) ClearUserDisplayName(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, clearUserDisplayName, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.TimeZone,
		&i.OnboardingCompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createAuthMethod = `-- name: CreateAuthMethod :one
INSERT INTO user_auth_methods (user_id, auth_service, subject)
VALUES ($1, $2, $3)
RETURNING user_id, auth_service, subject, created_at, last_used_at
`

type CreateAuthMethodParams struct {
	UserID      uuid.UUID
	AuthService AuthService
	Subject     string
}

func (q *Queries) CreateAuthMethod(ctx context.Context, arg CreateAuthMethodParams) (UserAuthMethod, error) {
	row := q.db.QueryRow(ctx, createAuthMethod, arg.UserID, arg.AuthService, arg.Subject)
	var i UserAuthMethod
	err := row.Scan(
		&i.UserID,
		&i.AuthService,
		&i.Subject,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (time_zone)
VALUES ($1)
RETURNING id, display_name, time_zone, onboarding_completed_at, created_at, updated_at, deleted_at
`

func (q *Queries) CreateUser(ctx context.Context, timeZone *string) (User, error) {
	row := q.db.QueryRow(ctx, createUser, timeZone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.TimeZone,
		&i.OnboardingCompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteAuthMethodBySubject = `-- name: DeleteAuthMethodBySubject :exec
DELETE FROM user_auth_methods
WHERE auth_service = $1
  AND subject = $2
`

type DeleteAuthMethodBySubjectParams struct {
	AuthService AuthService
	Subject     string
}

// Releases a number whose user row is gone, so signing up again works instead
// of hitting the primary key.
func (q *Queries) DeleteAuthMethodBySubject(ctx context.Context, arg DeleteAuthMethodBySubjectParams) error {
	_, err := q.db.Exec(ctx, deleteAuthMethodBySubject, arg.AuthService, arg.Subject)
	return err
}

const deleteAuthMethodsForUser = `-- name: DeleteAuthMethodsForUser :exec
DELETE FROM user_auth_methods
WHERE user_id = $1
`

func (q *Queries) DeleteAuthMethodsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAuthMethodsForUser, userID)
	return err
}

const getAuthMethod = `-- name: GetAuthMethod :one
SELECT user_id, auth_service, subject, created_at, last_used_at
FROM user_auth_methods
WHERE auth_service = $1
  AND subject = $2
`

type GetAuthMethodParams struct {
	AuthService AuthService
	Subject     string
}

func (q *Queries) GetAuthMethod(ctx context.Context, arg GetAuthMethodParams) (UserAuthMethod, error) {
	row := q.db.QueryRow(ctx, getAuthMethod, arg.AuthService, arg.Subject)
	var i UserAuthMethod
	err := row.Scan(
		&i.UserID,
		&i.AuthService,
		&i.Subject,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getPhoneNumberForUser = `-- name: GetPhoneNumberForUser :one
SELECT subject
FROM user_auth_methods
WHERE user_id = $1
  AND auth_service = 'PHONE'
`

func (q *Queries) GetPhoneNumberForUser(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getPhoneNumberForUser, userID)
	var subject string
	err := row.Scan(&subject)
	return subject, err
}

const getUser = `-- name: GetUser :one
SELECT id, display_name, time_zone, onboarding_completed_at, created_at, updated_at, deleted_at
FROM users
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.TimeZone,
		&i.OnboardingCompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET deleted_at = CURRENT_TIMESTAMP,
    -- The phone number is the account. Nulling the profile here without
    -- releasing the auth method would leave the number permanently unusable for
    -- a new signup, so DeleteAccount removes the auth-method row in the same
    -- transaction.
    display_name = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const touchAuthMethod = `-- name: TouchAuthMethod :exec
UPDATE user_auth_methods
SET last_used_at = CURRENT_TIMESTAMP
WHERE auth_service = $1
  AND subject = $2
`

type TouchAuthMethodParams struct {
	AuthService AuthService
	Subject     string
}

func (q *Queries) TouchAuthMethod(ctx context.Context, arg TouchAuthMethodParams) error {
	_, err := q.db.Exec(ctx, touchAuthMethod, arg.AuthService, arg.Subject)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    display_name = COALESCE($2, display_name),
    time_zone = COALESCE($3, time_zone),
    -- Latch: once completed, it stays completed at its original timestamp.
    onboarding_completed_at = CASE
        WHEN $4::boolean IS TRUE
            THEN COALESCE(onboarding_completed_at, CURRENT_TIMESTAMP)
        ELSE onboarding_completed_at
    END,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, display_name, time_zone, onboarding_completed_at, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	ID                     uuid.UUID
	DisplayName            *string
	TimeZone               *string
	MarkOnboardingComplete *bool
}

// Partial update: a NULL argument leaves the column alone. Callers that want to
// clear display_name pass the empty string, which the service maps to NULL
// before it gets here.
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.DisplayName,
		arg.TimeZone,
		arg.MarkOnboardingComplete,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.TimeZone,
		&i.OnboardingCompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
