// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: openmarket/api/v1/listing.proto

package apiv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FacebookMarketplaceBrowserVariant int32

const (
	FacebookMarketplaceBrowserVariant_FACEBOOK_MARKETPLACE_BROWSER_VARIANT_UNSPECIFIED FacebookMarketplaceBrowserVariant = 0
	FacebookMarketplaceBrowserVariant_FACEBOOK_MARKETPLACE_BROWSER_VARIANT_DESKTOP     FacebookMarketplaceBrowserVariant = 1
	FacebookMarketplaceBrowserVariant_FACEBOOK_MARKETPLACE_BROWSER_VARIANT_MOBILE      FacebookMarketplaceBrowserVariant = 2
)

// Enum value maps for FacebookMarketplaceBrowserVariant.
var (
	FacebookMarketplaceBrowserVariant_name = map[int32]string{
		0: "FACEBOOK_MARKETPLACE_BROWSER_VARIANT_UNSPECIFIED",
		1: "FACEBOOK_MARKETPLACE_BROWSER_VARIANT_DESKTOP",
		2: "FACEBOOK_MARKETPLACE_BROWSER_VARIANT_MOBILE",
	}
	FacebookMarketplaceBrowserVariant_value = map[string]int32{
		"FACEBOOK_MARKETPLACE_BROWSER_VARIANT_UNSPECIFIED": 0,
		"FACEBOOK_MARKETPLACE_BROWSER_VARIANT_DESKTOP":     1,
		"FACEBOOK_MARKETPLACE_BROWSER_VARIANT_MOBILE":      2,
	}
)

func (x FacebookMarketplaceBrowserVariant) Enum() *FacebookMarketplaceBrowserVariant {
	p := new(FacebookMarketplaceBrowserVariant)
	*p = x
	return p
}

func (x FacebookMarketplaceBrowserVariant) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FacebookMarketplaceBrowserVariant) Descriptor() protoreflect.EnumDescriptor {
	return file_openmarket_api_v1_listing_proto_enumTypes[0].Descriptor()
}

func (FacebookMarketplaceBrowserVariant) Type() protoreflect.EnumType {
	return &file_openmarket_api_v1_listing_proto_enumTypes[0]
}

func (x FacebookMarketplaceBrowserVariant) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FacebookMarketplaceBrowserVariant.Descriptor instead.
func (FacebookMarketplaceBrowserVariant) EnumDescriptor() ([]byte, []int) {
	return file_openmarket_api_v1_listing_proto_rawDescGZIP(), []int{0}
}

type FacebookMarketplacePageRoute int32

const (
	FacebookMarketplacePageRoute_FACEBOOK_MARKETPLACE_PAGE_ROUTE_UNSPECIFIED    FacebookMarketplacePageRoute = 0
	FacebookMarketplacePageRoute_FACEBOOK_MARKETPLACE_PAGE_ROUTE_SEARCH         FacebookMarketplacePageRoute = 1
	FacebookMarketplacePageRoute_FACEBOOK_MARKETPLACE_PAGE_ROUTE_DISCOVER       FacebookMarketplacePageRoute = 2
	FacebookMarketplacePageRoute_FACEBOOK_MARKETPLACE_PAGE_ROUTE_ITEM           FacebookMarketplacePageRoute = 3
	FacebookMarketplacePageRoute_FACEBOOK_MARKETPLACE_PAGE_ROUTE_SELLER_PROFILE FacebookMarketplacePageRoute = 4
)

// Enum value maps for FacebookMarketplacePageRoute.
var (
	FacebookMarketplacePageRoute_name = map[int32]string{
		0: "FACEBOOK_MARKETPLACE_PAGE_ROUTE_UNSPECIFIED",
		1: "FACEBOOK_MARKETPLACE_PAGE_ROUTE_SEARCH",
		2: "FACEBOOK_MARKETPLACE_PAGE_ROUTE_DISCOVER",
		3: "FACEBOOK_MARKETPLACE_PAGE_ROUTE_ITEM",
		4: "FACEBOOK_MARKETPLACE_PAGE_ROUTE_SELLER_PROFILE",
	}
	FacebookMarketplacePageRoute_value = map[string]int32{
		"FACEBOOK_MARKETPLACE_PAGE_ROUTE_UNSPECIFIED":    0,
		"FACEBOOK_MARKETPLACE_PAGE_ROUTE_SEARCH":         1,
		"FACEBOOK_MARKETPLACE_PAGE_ROUTE_DISCOVER":       2,
		"FACEBOOK_MARKETPLACE_PAGE_ROUTE_ITEM":           3,
		"FACEBOOK_MARKETPLACE_PAGE_ROUTE_SELLER_PROFILE": 4,
	}
)

func (x FacebookMarketplacePageRoute) Enum() *FacebookMarketplacePageRoute {
	p := new(FacebookMarketplacePageRoute)
	*p = x
	return p
}

func (x FacebookMarketplacePageRoute) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FacebookMarketplacePageRoute) Descriptor() protoreflect.EnumDescriptor {
	return file_openmarket_api_v1_listing_proto_enumTypes[1].Descriptor()
}

func (FacebookMarketplacePageRoute) Type() protoreflect.EnumType {
	return &file_openmarket_api_v1_listing_proto_enumTypes[1]
}

func (x FacebookMarketplacePageRoute) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FacebookMarketplacePageRoute.Descriptor instead.
func (FacebookMarketplacePageRoute) EnumDescriptor() ([]byte, []int) {
	return file_openmarket_api_v1_listing_proto_rawDescGZIP(), []int{1}
}

type FacebookMarketplaceExtractionMethod int32

const (
	FacebookMarketplaceExtractionMethod_FACEBOOK_MARKETPLACE_EXTRACTION_METHOD_UNSPECIFIED FacebookMarketplaceExtractionMethod = 0
	// Structured MarketplaceSearch data embedded in the first desktop page.
	FacebookMarketplaceExtractionMethod_FACEBOOK_MARKETPLACE_EXTRACTION_METHOD_EMBEDDED_GRAPHQL FacebookMarketplaceExtractionMethod = 1
	// Rendered text, attributes, links, and images in the page DOM.
	FacebookMarketplaceExtractionMethod_FACEBOOK_MARKETPLACE_EXTRACTION_METHOD_RENDERED_DOM FacebookMarketplaceExtractionMethod = 2
	// One observation combined fields from both structured data and the DOM.
	// Current item-detail extraction does this.
	FacebookMarketplaceExtractionMethod_FACEBOOK_MARKETPLACE_EXTRACTION_METHOD_HYBRID FacebookMarketplaceExtractionMethod = 3
)

// Enum value maps for FacebookMarketplaceExtractionMethod.
var (
	FacebookMarketplaceExtractionMethod_name = map[int32]string{
		0: "FACEBOOK_MARKETPLACE_EXTRACTION_METHOD_UNSPECIFIED",
		1: "FACEBOOK_MARKETPLACE_EXTRACTION_METHOD_EMBEDDED_GRAPHQL",
		2: "FACEBOOK_MARKETPLACE_EXTRACTION_METHOD_RENDERED_DOM",
		3: "FACEBOOK_MARKETPLACE_EXTRACTION_METHOD_HYBRID",
	}
	FacebookMarketplaceExtractionMethod_value = map[string]int32{
		"FACEBOOK_MARKETPLACE_EXTRACTION_METHOD_UNSPECIFIED":      0,
		"FACEBOOK_MARKETPLACE_EXTRACTION_METHOD_EMBEDDED_GRAPHQL": 1,
		"FACEBOOK_MARKETPLACE_EXTRACTION_METHOD_RENDERED_DOM":     2,
		"FACEBOOK_MARKETPLACE_EXTRACTION_METHOD_HYBRID":           3,
	}
)

func (x FacebookMarketplaceExtractionMethod) Enum() *FacebookMarketplaceExtractionMethod {
	p := new(FacebookMarketplaceExtractionMethod)
	*p = x
	return p
}

func (x FacebookMarketplaceExtractionMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FacebookMarketplaceExtractionMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_openmarket_api_v1_listing_proto_enumTypes[2].Descriptor()
}

func (FacebookMarketplaceExtractionMethod) Type() protoreflect.EnumType {
	return &file_openmarket_api_v1_listing_proto_enumTypes[2]
}

func (x FacebookMarketplaceExtractionMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FacebookMarketplaceExtractionMethod.Descriptor instead.
func (FacebookMarketplaceExtractionMethod) EnumDescriptor() ([]byte, []int) {
	return file_openmarket_api_v1_listing_proto_rawDescGZIP(), []int{2}
}

type FacebookAuthenticationState int32

const (
	FacebookAuthenticationState_FACEBOOK_AUTHENTICATION_STATE_UNSPECIFIED FacebookAuthenticationState = 0
	FacebookAuthenticationState_FACEBOOK_AUTHENTICATION_STATE_SIGNED_OUT  FacebookAuthenticationState = 1
	FacebookAuthenticationState_FACEBOOK_AUTHENTICATION_STATE_SIGNED_IN   FacebookAuthenticationState = 2
)

// Enum value maps for FacebookAuthenticationState.
var (
	FacebookAuthenticationState_name = map[int32]string{
		0: "FACEBOOK_AUTHENTICATION_STATE_UNSPECIFIED",
		1: "FACEBOOK_AUTHENTICATION_STATE_SIGNED_OUT",
		2: "FACEBOOK_AUTHENTICATION_STATE_SIGNED_IN",
	}
	FacebookAuthenticationState_value = map[string]int32{
		"FACEBOOK_AUTHENTICATION_STATE_UNSPECIFIED": 0,
		"FACEBOOK_AUTHENTICATION_STATE_SIGNED_OUT":  1,
		"FACEBOOK_AUTHENTICATION_STATE_SIGNED_IN":   2,
	}
)

func (x FacebookAuthenticationState) Enum() *FacebookAuthenticationState {
	p := new(FacebookAuthenticationState)
	*p = x
	return p
}

func (x FacebookAuthenticationState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FacebookAuthenticationState) Descriptor() protoreflect.EnumDescriptor {
	return file_openmarket_api_v1_listing_proto_enumTypes[3].Descriptor()
}

func (FacebookAuthenticationState) Type() protoreflect.EnumType {
	return &file_openmarket_api_v1_listing_proto_enumTypes[3]
}

func (x FacebookAuthenticationState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FacebookAuthenticationState.Descriptor instead.
func (FacebookAuthenticationState) EnumDescriptor() ([]byte, []int) {
	return file_openmarket_api_v1_listing_proto_rawDescGZIP(), []int{3}
}

type FacebookMarketplaceSellerSectionStatus int32

const (
	FacebookMarketplaceSellerSectionStatus_FACEBOOK_MARKETPLACE_SELLER_SECTION_STATUS_UNSPECIFIED FacebookMarketplaceSellerSectionStatus = 0
	// The capture context cannot expose seller identity (currently signed-out
	// desktop item pages). This is unknown, not evidence that no seller exists.
	FacebookMarketplaceSellerSectionStatus_FACEBOOK_MARKETPLACE_SELLER_SECTION_STATUS_UNAVAILABLE FacebookMarketplaceSellerSectionStatus = 1
	// The page was capable of exposing the section but extraction did not
	// observe it. Keep this distinct from an observed section with empty fields.
	FacebookMarketplaceSellerSectionStatus_FACEBOOK_MARKETPLACE_SELLER_SECTION_STATUS_NOT_OBSERVED FacebookMarketplaceSellerSectionStatus = 2
	FacebookMarketplaceSellerSectionStatus_FACEBOOK_MARKETPLACE_SELLER_SECTION_STATUS_OBSERVED     FacebookMarketplaceSellerSectionStatus = 3
)

// Enum value maps for FacebookMarketplaceSellerSectionStatus.
var (
	FacebookMarketplaceSellerSectionStatus_name = map[int32]string{
		0: "FACEBOOK_MARKETPLACE_SELLER_SECTION_STATUS_UNSPECIFIED",
		1: "FACEBOOK_MARKETPLACE_SELLER_SECTION_STATUS_UNAVAILABLE",
		2: "FACEBOOK_MARKETPLACE_SELLER_SECTION_STATUS_NOT_OBSERVED",
		3: "FACEBOOK_MARKETPLACE_SELLER_SECTION_STATUS_OBSERVED",
	}
	FacebookMarketplaceSellerSectionStatus_value = map[string]int32{
		"FACEBOOK_MARKETPLACE_SELLER_SECTION_STATUS_UNSPECIFIED":  0,
		"FACEBOOK_MARKETPLACE_SELLER_SECTION_STATUS_UNAVAILABLE":  1,
		"FACEBOOK_MARKETPLACE_SELLER_SECTION_STATUS_NOT_OBSERVED": 2,
		"FACEBOOK_MARKETPLACE_SELLER_SECTION_STATUS_OBSERVED":     3,
	}
)

func (x FacebookMarketplaceSellerSectionStatus) Enum() *FacebookMarketplaceSellerSectionStatus {
	p := new(FacebookMarketplaceSellerSectionStatus)
	*p = x
	return p
}

func (x FacebookMarketplaceSellerSectionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FacebookMarketplaceSellerSectionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_openmarket_api_v1_listing_proto_enumTypes[4].Descriptor()
}

func (FacebookMarketplaceSellerSectionStatus) Type() protoreflect.EnumType {
	return &file_openmarket_api_v1_listing_proto_enumTypes[4]
}

func (x FacebookMarketplaceSellerSectionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FacebookMarketplaceSellerSectionStatus.Descriptor instead.
func (FacebookMarketplaceSellerSectionStatus) EnumDescriptor() ([]byte, []int) {
	return file_openmarket_api_v1_listing_proto_rawDescGZIP(), []int{4}
}

type FacebookMarketplaceObservationContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Facebook browser variant that was parsed, not the observer's hardware.
	// A phone requesting the desktop site records DESKTOP here.
	BrowserVariant              FacebookMarketplaceBrowserVariant   `protobuf:"varint,1,opt,name=browser_variant,json=browserVariant,proto3,enum=openmarket.api.v1.FacebookMarketplaceBrowserVariant" json:"browser_variant,omitempty"`
	PageRoute                   FacebookMarketplacePageRoute        `protobuf:"varint,2,opt,name=page_route,json=pageRoute,proto3,enum=openmarket.api.v1.FacebookMarketplacePageRoute" json:"page_route,omitempty"`
	ExtractionMethod            FacebookMarketplaceExtractionMethod `protobuf:"varint,3,opt,name=extraction_method,json=extractionMethod,proto3,enum=openmarket.api.v1.FacebookMarketplaceExtractionMethod" json:"extraction_method,omitempty"`
	FacebookAuthenticationState FacebookAuthenticationState         `protobuf:"varint,4,opt,name=facebook_authentication_state,json=facebookAuthenticationState,proto3,enum=openmarket.api.v1.FacebookAuthenticationState" json:"facebook_authentication_state,omitempty"`
	ObservedAt                  *timestamppb.Timestamp              `protobuf:"bytes,5,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *FacebookMarketplaceObservationContext) Reset() {
	*x = FacebookMarketplaceObservationContext{}
	mi := &file_openmarket_api_v1_listing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FacebookMarketplaceObservationContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FacebookMarketplaceObservationContext) ProtoMessage() {}

func (x *FacebookMarketplaceObservationContext) ProtoReflect() protoreflect.Message {
	mi := &file_openmarket_api_v1_listing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FacebookMarketplaceObservationContext.ProtoReflect.Descriptor instead.
func (*FacebookMarketplaceObservationContext) Descriptor() ([]byte, []int) {
	return file_openmarket_api_v1_listing_proto_rawDescGZIP(), []int{0}
}

func (x *FacebookMarketplaceObservationContext) GetBrowserVariant() FacebookMarketplaceBrowserVariant {
	if x != nil {
		return x.BrowserVariant
	}
	return FacebookMarketplaceBrowserVariant_FACEBOOK_MARKETPLACE_BROWSER_VARIANT_UNSPECIFIED
}

func (x *FacebookMarketplaceObservationContext) GetPageRoute() FacebookMarketplacePageRoute {
	if x != nil {
		return x.PageRoute
	}
	return FacebookMarketplacePageRoute_FACEBOOK_MARKETPLACE_PAGE_ROUTE_UNSPECIFIED
}

func (x *FacebookMarketplaceObservationContext) GetExtractionMethod() FacebookMarketplaceExtractionMethod {
	if x != nil {
		return x.ExtractionMethod
	}
	return FacebookMarketplaceExtractionMethod_FACEBOOK_MARKETPLACE_EXTRACTION_METHOD_UNSPECIFIED
}

func (x *FacebookMarketplaceObservationContext) GetFacebookAuthenticationState() FacebookAuthenticationState {
	if x != nil {
		return x.FacebookAuthenticationState
	}
	return FacebookAuthenticationState_FACEBOOK_AUTHENTICATION_STATE_UNSPECIFIED
}

func (x *FacebookMarketplaceObservationContext) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

// At least one Facebook key must be present. Desktop cards expose listing_id;
// mobile cards may only expose the cover-photo filename FBID until opened.
type FacebookListingKey struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FacebookListingId *string                `protobuf:"bytes,1,opt,name=facebook_listing_id,json=facebookListingId,proto3,oneof" json:"facebook_listing_id,omitempty"`
	// The durable numeric segment parsed from the fbcdn filename. This is not
	// primary_listing_photo.id; measured values differ.
	CoverPhotoFbid *string `protobuf:"bytes,2,opt,name=cover_photo_fbid,json=coverPhotoFbid,proto3,oneof" json:"cover_photo_fbid,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FacebookListingKey) Reset() {
	*x = FacebookListingKey{}
	mi := &file_openmarket_api_v1_listing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FacebookListingKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FacebookListingKey) ProtoMessage() {}

func (x *FacebookListingKey) ProtoReflect() protoreflect.Message {
	mi := &file_openmarket_api_v1_listing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FacebookListingKey.ProtoReflect.Descriptor instead.
func (*FacebookListingKey) Descriptor() ([]byte, []int) {
	return file_openmarket_api_v1_listing_proto_rawDescGZIP(), []int{1}
}

func (x *FacebookListingKey) GetFacebookListingId() string {
	if x != nil && x.FacebookListingId != nil {
		return *x.FacebookListingId
	}
	return ""
}

func (x *FacebookListingKey) GetCoverPhotoFbid() string {
	if x != nil && x.CoverPhotoFbid != nil {
		return *x.CoverPhotoFbid
	}
	return ""
}

type FacebookMarketplacePriceObservation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Facebook's decimal string, in major units (for example "40.00"). Keep the
	// source value: converting to minor units requires knowing the currency's
	// exponent, which a rendered card does not always reveal.
	AmountDecimal           *string `protobuf:"bytes,1,opt,name=amount_decimal,json=amountDecimal,proto3,oneof" json:"amount_decimal,omitempty"`
	FormattedAmount         *string `protobuf:"bytes,2,opt,name=formatted_amount,json=formattedAmount,proto3,oneof" json:"formatted_amount,omitempty"`
	PreviousAmountDecimal   *string `protobuf:"bytes,3,opt,name=previous_amount_decimal,json=previousAmountDecimal,proto3,oneof" json:"previous_amount_decimal,omitempty"`
	PreviousFormattedAmount *string `protobuf:"bytes,4,opt,name=previous_formatted_amount,json=previousFormattedAmount,proto3,oneof" json:"previous_formatted_amount,omitempty"`
	CurrencyCode            *string `protobuf:"bytes,5,opt,name=currency_code,json=currencyCode,proto3,oneof" json:"currency_code,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *FacebookMarketplacePriceObservation) Reset() {
	*x = FacebookMarketplacePriceObservation{}
	mi := &file_openmarket_api_v1_listing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FacebookMarketplacePriceObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FacebookMarketplacePriceObservation) ProtoMessage() {}

func (x *FacebookMarketplacePriceObservation) ProtoReflect() protoreflect.Message {
	mi := &file_openmarket_api_v1_listing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FacebookMarketplacePriceObservation.ProtoReflect.Descriptor instead.
func (*FacebookMarketplacePriceObservation) Descriptor() ([]byte, []int) {
	return file_openmarket_api_v1_listing_proto_rawDescGZIP(), []int{2}
}

func (x *FacebookMarketplacePriceObservation) GetAmountDecimal() string {
	if x != nil && x.AmountDecimal != nil {
		return *x.AmountDecimal
	}
	return ""
}

func (x *FacebookMarketplacePriceObservation) GetFormattedAmount() string {
	if x != nil && x.FormattedAmount != nil {
		return *x.FormattedAmount
	}
	return ""
}

func (x *FacebookMarketplacePriceObservation) GetPreviousAmountDecimal() string {
	if x != nil && x.PreviousAmountDecimal != nil {
		return *x.PreviousAmountDecimal
	}
	return ""
}

func (x *FacebookMarketplacePriceObservation) GetPreviousFormattedAmount() string {
	if x != nil && x.PreviousFormattedAmount != nil {
		return *x.PreviousFormattedAmount
	}
	return ""
}

func (x *FacebookMarketplacePriceObservation) GetCurrencyCode() string {
	if x != nil && x.CurrencyCode != nil {
		return *x.CurrencyCode
	}
	return ""
}

type FacebookMarketplacePlaceObservation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DisplayText     *string                `protobuf:"bytes,1,opt,name=display_text,json=displayText,proto3,oneof" json:"display_text,omitempty"`
	City            *string                `protobuf:"bytes,2,opt,name=city,proto3,oneof" json:"city,omitempty"`
	Region          *string                `protobuf:"bytes,3,opt,name=region,proto3,oneof" json:"region,omitempty"`
	Country         *string                `protobuf:"bytes,4,opt,name=country,proto3,oneof" json:"country,omitempty"`
	FacebookPlaceId *string                `protobuf:"bytes,5,opt,name=facebook_place_id,json=facebookPlaceId,proto3,oneof" json:"facebook_place_id,omitempty"`
	// Facebook's published, approximate listing point. Never reinterpret this as
	// the seller's home or business location.
	Latitude      *float64 `protobuf:"fixed64,6,opt,name=latitude,proto3,oneof" json:"latitude,omitempty"`
	Longitude     *float64 `protobuf:"fixed64,7,opt,name=longitude,proto3,oneof" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FacebookMarketplacePlaceObservation) Reset() {
	*x = FacebookMarketplacePlaceObservation{}
	mi := &file_openmarket_api_v1_listing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FacebookMarketplacePlaceObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FacebookMarketplacePlaceObservation) ProtoMessage() {}

func (x *FacebookMarketplacePlaceObservation) ProtoReflect() protoreflect.Message {
	mi := &file_openmarket_api_v1_listing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FacebookMarketplacePlaceObservation.ProtoReflect.Descriptor instead.
func (*FacebookMarketplacePlaceObservation) Descriptor() ([]byte, []int) {
	return file_openmarket_api_v1_listing_proto_rawDescGZIP(), []int{3}
}

func (x *FacebookMarketplacePlaceObservation) GetDisplayText() string {
	if x != nil && x.DisplayText != nil {
		return *x.DisplayText
	}
	return ""
}

func (x *FacebookMarketplacePlaceObservation) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *FacebookMarketplacePlaceObservation) GetRegion() string {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	return ""
}

func (x *FacebookMarketplacePlaceObservation) GetCountry() string {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return ""
}

func (x *FacebookMarketplacePlaceObservation) GetFacebookPlaceId() string {
	if x != nil && x.FacebookPlaceId != nil {
		return *x.FacebookPlaceId
	}
	return ""
}

func (x *FacebookMarketplacePlaceObservation) GetLatitude() float64 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *FacebookMarketplacePlaceObservation) GetLongitude() float64 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

type FacebookMarketplaceMediaObservation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FacebookPhotoId *string                `protobuf:"bytes,1,opt,name=facebook_photo_id,json=facebookPhotoId,proto3,oneof" json:"facebook_photo_id,omitempty"`
	Url             *string                `protobuf:"bytes,2,opt,name=url,proto3,oneof" json:"url,omitempty"`
	Position        *int32                 `protobuf:"varint,3,opt,name=position,proto3,oneof" json:"position,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FacebookMarketplaceMediaObservation) Reset() {
	*x = FacebookMarketplaceMediaObservation{}
	mi := &file_openmarket_api_v1_listing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FacebookMarketplaceMediaObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FacebookMarketplaceMediaObservation) ProtoMessage() {}

func (x *FacebookMarketplaceMediaObservation) ProtoReflect() protoreflect.Message {
	mi := &file_openmarket_api_v1_listing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FacebookMarketplaceMediaObservation.ProtoReflect.Descriptor instead.
func (*FacebookMarketplaceMediaObservation) Descriptor() ([]byte, []int) {
	return file_openmarket_api_v1_listing_proto_rawDescGZIP(), []int{4}
}

func (x *FacebookMarketplaceMediaObservation) GetFacebookPhotoId() string {
	if x != nil && x.FacebookPhotoId != nil {
		return *x.FacebookPhotoId
	}
	return ""
}

func (x *FacebookMarketplaceMediaObservation) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *FacebookMarketplaceMediaObservation) GetPosition() int32 {
	if x != nil && x.Position != nil {
		return *x.Position
	}
	return 0
}

type FacebookMarketplaceSellerObservation struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	SectionStatus FacebookMarketplaceSellerSectionStatus `protobuf:"varint,1,opt,name=section_status,json=sectionStatus,proto3,enum=openmarket.api.v1.FacebookMarketplaceSellerSectionStatus" json:"section_status,omitempty"`
	// Numeric id from /marketplace/profile/<id>. Stable on signed-in desktop item
	// pages and preferable to clustering on name plus listing coordinates.
	FacebookProfileId *string  `protobuf:"bytes,2,opt,name=facebook_profile_id,json=facebookProfileId,proto3,oneof" json:"facebook_profile_id,omitempty"`
	DisplayName       *string  `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	JoinedText        *string  `protobuf:"bytes,4,opt,name=joined_text,json=joinedText,proto3,oneof" json:"joined_text,omitempty"`
	JoinedYear        *int32   `protobuf:"varint,5,opt,name=joined_year,json=joinedYear,proto3,oneof" json:"joined_year,omitempty"`
	Rating            *float64 `protobuf:"fixed64,6,opt,name=rating,proto3,oneof" json:"rating,omitempty"`
	RatingCount       *int32   `protobuf:"varint,7,opt,name=rating_count,json=ratingCount,proto3,oneof" json:"rating_count,omitempty"`
	// Facebook's rendered "Highly rated on Marketplace" designation. This is
	// observed from Facebook, not derived from rating and rating_count. The
	// threshold behind Facebook's designation is not published.
	HighlyRated *bool `protobuf:"varint,8,opt,name=highly_rated,json=highlyRated,proto3,oneof" json:"highly_rated,omitempty"`
	// Populate only from text explicitly associated with the seller or from the
	// seller profile page. The item's listing_location is not seller_location.
	SellerLocation *FacebookMarketplacePlaceObservation `protobuf:"bytes,9,opt,name=seller_location,json=sellerLocation,proto3" json:"seller_location,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FacebookMarketplaceSellerObservation) Reset() {
	*x = FacebookMarketplaceSellerObservation{}
	mi := &file_openmarket_api_v1_listing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FacebookMarketplaceSellerObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FacebookMarketplaceSellerObservation) ProtoMessage() {}

func (x *FacebookMarketplaceSellerObservation) ProtoReflect() protoreflect.Message {
	mi := &file_openmarket_api_v1_listing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FacebookMarketplaceSellerObservation.ProtoReflect.Descriptor instead.
func (*FacebookMarketplaceSellerObservation) Descriptor() ([]byte, []int) {
	return file_openmarket_api_v1_listing_proto_rawDescGZIP(), []int{5}
}

func (x *FacebookMarketplaceSellerObservation) GetSectionStatus() FacebookMarketplaceSellerSectionStatus {
	if x != nil {
		return x.SectionStatus
	}
	return FacebookMarketplaceSellerSectionStatus_FACEBOOK_MARKETPLACE_SELLER_SECTION_STATUS_UNSPECIFIED
}

func (x *FacebookMarketplaceSellerObservation) GetFacebookProfileId() string {
	if x != nil && x.FacebookProfileId != nil {
		return *x.FacebookProfileId
	}
	return ""
}

func (x *FacebookMarketplaceSellerObservation) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *FacebookMarketplaceSellerObservation) GetJoinedText() string {
	if x != nil && x.JoinedText != nil {
		return *x.JoinedText
	}
	return ""
}

func (x *FacebookMarketplaceSellerObservation) GetJoinedYear() int32 {
	if x != nil && x.JoinedYear != nil {
		return *x.JoinedYear
	}
	return 0
}

func (x *FacebookMarketplaceSellerObservation) GetRating() float64 {
	if x != nil && x.Rating != nil {
		return *x.Rating
	}
	return 0
}

func (x *FacebookMarketplaceSellerObservation) GetRatingCount() int32 {
	if x != nil && x.RatingCount != nil {
		return *x.RatingCount
	}
	return 0
}

func (x *FacebookMarketplaceSellerObservation) GetHighlyRated() bool {
	if x != nil && x.HighlyRated != nil {
		return *x.HighlyRated
	}
	return false
}

func (x *FacebookMarketplaceSellerObservation) GetSellerLocation() *FacebookMarketplacePlaceObservation {
	if x != nil {
		return x.SellerLocation
	}
	return nil
}

// Facebook publishes these as three independent booleans. Keep the source
// facts together and derive one canonical availability value on the server;
// is_live is not that value because it has been observed true on sold cards.
type FacebookMarketplaceAvailabilityObservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sold          *bool                  `protobuf:"varint,1,opt,name=sold,proto3,oneof" json:"sold,omitempty"`
	Live          *bool                  `protobuf:"varint,2,opt,name=live,proto3,oneof" json:"live,omitempty"`
	Pending       *bool                  `protobuf:"varint,3,opt,name=pending,proto3,oneof" json:"pending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FacebookMarketplaceAvailabilityObservation) Reset() {
	*x = FacebookMarketplaceAvailabilityObservation{}
	mi := &file_openmarket_api_v1_listing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FacebookMarketplaceAvailabilityObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FacebookMarketplaceAvailabilityObservation) ProtoMessage() {}

func (x *FacebookMarketplaceAvailabilityObservation) ProtoReflect() protoreflect.Message {
	mi := &file_openmarket_api_v1_listing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FacebookMarketplaceAvailabilityObservation.ProtoReflect.Descriptor instead.
func (*FacebookMarketplaceAvailabilityObservation) Descriptor() ([]byte, []int) {
	return file_openmarket_api_v1_listing_proto_rawDescGZIP(), []int{6}
}

func (x *FacebookMarketplaceAvailabilityObservation) GetSold() bool {
	if x != nil && x.Sold != nil {
		return *x.Sold
	}
	return false
}

func (x *FacebookMarketplaceAvailabilityObservation) GetLive() bool {
	if x != nil && x.Live != nil {
		return *x.Live
	}
	return false
}

func (x *FacebookMarketplaceAvailabilityObservation) GetPending() bool {
	if x != nil && x.Pending != nil {
		return *x.Pending
	}
	return false
}

// One listing as a search/discover surface observed it. The first desktop
// search page normally uses EMBEDDED_GRAPHQL and can carry listed_at; cards
// inserted by infinite scroll use RENDERED_DOM and cannot.
type FacebookMarketplaceSearchListingObservation struct {
	state           protoimpl.MessageState                 `protogen:"open.v1"`
	Context         *FacebookMarketplaceObservationContext `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Key             *FacebookListingKey                    `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Title           *string                                `protobuf:"bytes,3,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Price           *FacebookMarketplacePriceObservation   `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	ListingLocation *FacebookMarketplacePlaceObservation   `protobuf:"bytes,5,opt,name=listing_location,json=listingLocation,proto3" json:"listing_location,omitempty"`
	Condition       *string                                `protobuf:"bytes,6,opt,name=condition,proto3,oneof" json:"condition,omitempty"`
	PrimaryPhoto    *FacebookMarketplaceMediaObservation   `protobuf:"bytes,7,opt,name=primary_photo,json=primaryPhoto,proto3" json:"primary_photo,omitempty"`
	// Exact Facebook creation_time, named for its domain meaning rather than the
	// source JSON spelling. Database row creation remains created_at.
	ListedAt             *timestamppb.Timestamp                      `protobuf:"bytes,8,opt,name=listed_at,json=listedAt,proto3" json:"listed_at,omitempty"`
	DeliveryTypes        []string                                    `protobuf:"bytes,9,rep,name=delivery_types,json=deliveryTypes,proto3" json:"delivery_types,omitempty"`
	Availability         *FacebookMarketplaceAvailabilityObservation `protobuf:"bytes,10,opt,name=availability,proto3" json:"availability,omitempty"`
	FacebookCategoryId   *string                                     `protobuf:"bytes,13,opt,name=facebook_category_id,json=facebookCategoryId,proto3,oneof" json:"facebook_category_id,omitempty"`
	CreatedWithSellerApp *bool                                       `protobuf:"varint,14,opt,name=created_with_seller_app,json=createdWithSellerApp,proto3,oneof" json:"created_with_seller_app,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *FacebookMarketplaceSearchListingObservation) Reset() {
	*x = FacebookMarketplaceSearchListingObservation{}
	mi := &file_openmarket_api_v1_listing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FacebookMarketplaceSearchListingObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FacebookMarketplaceSearchListingObservation) ProtoMessage() {}

func (x *FacebookMarketplaceSearchListingObservation) ProtoReflect() protoreflect.Message {
	mi := &file_openmarket_api_v1_listing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FacebookMarketplaceSearchListingObservation.ProtoReflect.Descriptor instead.
func (*FacebookMarketplaceSearchListingObservation) Descriptor() ([]byte, []int) {
	return file_openmarket_api_v1_listing_proto_rawDescGZIP(), []int{7}
}

func (x *FacebookMarketplaceSearchListingObservation) GetContext() *FacebookMarketplaceObservationContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *FacebookMarketplaceSearchListingObservation) GetKey() *FacebookListingKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *FacebookMarketplaceSearchListingObservation) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *FacebookMarketplaceSearchListingObservation) GetPrice() *FacebookMarketplacePriceObservation {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *FacebookMarketplaceSearchListingObservation) GetListingLocation() *FacebookMarketplacePlaceObservation {
	if x != nil {
		return x.ListingLocation
	}
	return nil
}

func (x *FacebookMarketplaceSearchListingObservation) GetCondition() string {
	if x != nil && x.Condition != nil {
		return *x.Condition
	}
	return ""
}

func (x *FacebookMarketplaceSearchListingObservation) GetPrimaryPhoto() *FacebookMarketplaceMediaObservation {
	if x != nil {
		return x.PrimaryPhoto
	}
	return nil
}

func (x *FacebookMarketplaceSearchListingObservation) GetListedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ListedAt
	}
	return nil
}

func (x *FacebookMarketplaceSearchListingObservation) GetDeliveryTypes() []string {
	if x != nil {
		return x.DeliveryTypes
	}
	return nil
}

func (x *FacebookMarketplaceSearchListingObservation) GetAvailability() *FacebookMarketplaceAvailabilityObservation {
	if x != nil {
		return x.Availability
	}
	return nil
}

func (x *FacebookMarketplaceSearchListingObservation) GetFacebookCategoryId() string {
	if x != nil && x.FacebookCategoryId != nil {
		return *x.FacebookCategoryId
	}
	return ""
}

func (x *FacebookMarketplaceSearchListingObservation) GetCreatedWithSellerApp() bool {
	if x != nil && x.CreatedWithSellerApp != nil {
		return *x.CreatedWithSellerApp
	}
	return false
}

// One listing as its item page observed it. Seller presence is interpreted
// together with context.facebook_authentication_state and
// seller.section_status.
type FacebookMarketplaceListingDetailObservation struct {
	state           protoimpl.MessageState                 `protogen:"open.v1"`
	Context         *FacebookMarketplaceObservationContext `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Key             *FacebookListingKey                    `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Title           *string                                `protobuf:"bytes,3,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description     *string                                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Price           *FacebookMarketplacePriceObservation   `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	ListingLocation *FacebookMarketplacePlaceObservation   `protobuf:"bytes,6,opt,name=listing_location,json=listingLocation,proto3" json:"listing_location,omitempty"`
	Condition       *string                                `protobuf:"bytes,7,opt,name=condition,proto3,oneof" json:"condition,omitempty"`
	Media           []*FacebookMarketplaceMediaObservation `protobuf:"bytes,8,rep,name=media,proto3" json:"media,omitempty"`
	// Coarse rendered value such as "Listed 3 weeks ago". Do not convert this to
	// an exact instant without also storing the derivation precision.
	ListedAtText  *string                                     `protobuf:"bytes,9,opt,name=listed_at_text,json=listedAtText,proto3,oneof" json:"listed_at_text,omitempty"`
	DeliveryTypes []string                                    `protobuf:"bytes,10,rep,name=delivery_types,json=deliveryTypes,proto3" json:"delivery_types,omitempty"`
	Availability  *FacebookMarketplaceAvailabilityObservation `protobuf:"bytes,11,opt,name=availability,proto3" json:"availability,omitempty"`
	Seller        *FacebookMarketplaceSellerObservation       `protobuf:"bytes,14,opt,name=seller,proto3" json:"seller,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FacebookMarketplaceListingDetailObservation) Reset() {
	*x = FacebookMarketplaceListingDetailObservation{}
	mi := &file_openmarket_api_v1_listing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FacebookMarketplaceListingDetailObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FacebookMarketplaceListingDetailObservation) ProtoMessage() {}

func (x *FacebookMarketplaceListingDetailObservation) ProtoReflect() protoreflect.Message {
	mi := &file_openmarket_api_v1_listing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FacebookMarketplaceListingDetailObservation.ProtoReflect.Descriptor instead.
func (*FacebookMarketplaceListingDetailObservation) Descriptor() ([]byte, []int) {
	return file_openmarket_api_v1_listing_proto_rawDescGZIP(), []int{8}
}

func (x *FacebookMarketplaceListingDetailObservation) GetContext() *FacebookMarketplaceObservationContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *FacebookMarketplaceListingDetailObservation) GetKey() *FacebookListingKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *FacebookMarketplaceListingDetailObservation) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *FacebookMarketplaceListingDetailObservation) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *FacebookMarketplaceListingDetailObservation) GetPrice() *FacebookMarketplacePriceObservation {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *FacebookMarketplaceListingDetailObservation) GetListingLocation() *FacebookMarketplacePlaceObservation {
	if x != nil {
		return x.ListingLocation
	}
	return nil
}

func (x *FacebookMarketplaceListingDetailObservation) GetCondition() string {
	if x != nil && x.Condition != nil {
		return *x.Condition
	}
	return ""
}

func (x *FacebookMarketplaceListingDetailObservation) GetMedia() []*FacebookMarketplaceMediaObservation {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *FacebookMarketplaceListingDetailObservation) GetListedAtText() string {
	if x != nil && x.ListedAtText != nil {
		return *x.ListedAtText
	}
	return ""
}

func (x *FacebookMarketplaceListingDetailObservation) GetDeliveryTypes() []string {
	if x != nil {
		return x.DeliveryTypes
	}
	return nil
}

func (x *FacebookMarketplaceListingDetailObservation) GetAvailability() *FacebookMarketplaceAvailabilityObservation {
	if x != nil {
		return x.Availability
	}
	return nil
}

func (x *FacebookMarketplaceListingDetailObservation) GetSeller() *FacebookMarketplaceSellerObservation {
	if x != nil {
		return x.Seller
	}
	return nil
}

type FacebookMarketplaceListingObservation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Observation:
	//
	//	*FacebookMarketplaceListingObservation_Search
	//	*FacebookMarketplaceListingObservation_Detail
	Observation   isFacebookMarketplaceListingObservation_Observation `protobuf_oneof:"observation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FacebookMarketplaceListingObservation) Reset() {
	*x = FacebookMarketplaceListingObservation{}
	mi := &file_openmarket_api_v1_listing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FacebookMarketplaceListingObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FacebookMarketplaceListingObservation) ProtoMessage() {}

func (x *FacebookMarketplaceListingObservation) ProtoReflect() protoreflect.Message {
	mi := &file_openmarket_api_v1_listing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FacebookMarketplaceListingObservation.ProtoReflect.Descriptor instead.
func (*FacebookMarketplaceListingObservation) Descriptor() ([]byte, []int) {
	return file_openmarket_api_v1_listing_proto_rawDescGZIP(), []int{9}
}

func (x *FacebookMarketplaceListingObservation) GetObservation() isFacebookMarketplaceListingObservation_Observation {
	if x != nil {
		return x.Observation
	}
	return nil
}

func (x *FacebookMarketplaceListingObservation) GetSearch() *FacebookMarketplaceSearchListingObservation {
	if x != nil {
		if x, ok := x.Observation.(*FacebookMarketplaceListingObservation_Search); ok {
			return x.Search
		}
	}
	return nil
}

func (x *FacebookMarketplaceListingObservation) GetDetail() *FacebookMarketplaceListingDetailObservation {
	if x != nil {
		if x, ok := x.Observation.(*FacebookMarketplaceListingObservation_Detail); ok {
			return x.Detail
		}
	}
	return nil
}

type isFacebookMarketplaceListingObservation_Observation interface {
	isFacebookMarketplaceListingObservation_Observation()
}

type FacebookMarketplaceListingObservation_Search struct {
	Search *FacebookMarketplaceSearchListingObservation `protobuf:"bytes,1,opt,name=search,proto3,oneof"`
}

type FacebookMarketplaceListingObservation_Detail struct {
	Detail *FacebookMarketplaceListingDetailObservation `protobuf:"bytes,2,opt,name=detail,proto3,oneof"`
}

func (*FacebookMarketplaceListingObservation_Search) isFacebookMarketplaceListingObservation_Observation() {
}

func (*FacebookMarketplaceListingObservation_Detail) isFacebookMarketplaceListingObservation_Observation() {
}

var File_openmarket_api_v1_listing_proto protoreflect.FileDescriptor

const file_openmarket_api_v1_listing_proto_rawDesc = "" +
	"\n" +
	"\x1fopenmarket/api/v1/listing.proto\x12\x11openmarket.api.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9c\x04\n" +
	"%FacebookMarketplaceObservationContext\x12g\n" +
	"\x0fbrowser_variant\x18\x01 \x01(\x0e24.openmarket.api.v1.FacebookMarketplaceBrowserVariantB\b\xbaH\x05\x82\x01\x02\x10\x01R\x0ebrowserVariant\x12X\n" +
	"\n" +
	"page_route\x18\x02 \x01(\x0e2/.openmarket.api.v1.FacebookMarketplacePageRouteB\b\xbaH\x05\x82\x01\x02\x10\x01R\tpageRoute\x12m\n" +
	"\x11extraction_method\x18\x03 \x01(\x0e26.openmarket.api.v1.FacebookMarketplaceExtractionMethodB\b\xbaH\x05\x82\x01\x02\x10\x01R\x10extractionMethod\x12|\n" +
	"\x1dfacebook_authentication_state\x18\x04 \x01(\x0e2..openmarket.api.v1.FacebookAuthenticationStateB\b\xbaH\x05\x82\x01\x02\x10\x01R\x1bfacebookAuthenticationState\x12C\n" +
	"\vobserved_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"observedAt\"\xee\x02\n" +
	"\x12FacebookListingKey\x12G\n" +
	"\x13facebook_listing_id\x18\x01 \x01(\tB\x12\xbaH\x0fr\r2\v^[0-9]{8,}$H\x00R\x11facebookListingId\x88\x01\x01\x12A\n" +
	"\x10cover_photo_fbid\x18\x02 \x01(\tB\x12\xbaH\x0fr\r2\v^[0-9]{8,}$H\x01R\x0ecoverPhotoFbid\x88\x01\x01:\x9e\x01\xbaH\x9a\x01\x1a\x97\x01\n" +
	"#facebook_listing_key.needs_identity\x123facebook_listing_id or cover_photo_fbid is required\x1a;has(this.facebook_listing_id) || has(this.cover_photo_fbid)B\x16\n" +
	"\x14_facebook_listing_idB\x13\n" +
	"\x11_cover_photo_fbid\"\xa7\x03\n" +
	"#FacebookMarketplacePriceObservation\x12*\n" +
	"\x0eamount_decimal\x18\x01 \x01(\tH\x00R\ramountDecimal\x88\x01\x01\x12.\n" +
	"\x10formatted_amount\x18\x02 \x01(\tH\x01R\x0fformattedAmount\x88\x01\x01\x12;\n" +
	"\x17previous_amount_decimal\x18\x03 \x01(\tH\x02R\x15previousAmountDecimal\x88\x01\x01\x12?\n" +
	"\x19previous_formatted_amount\x18\x04 \x01(\tH\x03R\x17previousFormattedAmount\x88\x01\x01\x122\n" +
	"\rcurrency_code\x18\x05 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x03H\x04R\fcurrencyCode\x88\x01\x01B\x11\n" +
	"\x0f_amount_decimalB\x13\n" +
	"\x11_formatted_amountB\x1a\n" +
	"\x18_previous_amount_decimalB\x1c\n" +
	"\x1a_previous_formatted_amountB\x10\n" +
	"\x0e_currency_code\"\x8d\x03\n" +
	"#FacebookMarketplacePlaceObservation\x12&\n" +
	"\fdisplay_text\x18\x01 \x01(\tH\x00R\vdisplayText\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\x02 \x01(\tH\x01R\x04city\x88\x01\x01\x12\x1b\n" +
	"\x06region\x18\x03 \x01(\tH\x02R\x06region\x88\x01\x01\x12\x1d\n" +
	"\acountry\x18\x04 \x01(\tH\x03R\acountry\x88\x01\x01\x12C\n" +
	"\x11facebook_place_id\x18\x05 \x01(\tB\x12\xbaH\x0fr\r2\v^[0-9]{8,}$H\x04R\x0ffacebookPlaceId\x88\x01\x01\x12\x1f\n" +
	"\blatitude\x18\x06 \x01(\x01H\x05R\blatitude\x88\x01\x01\x12!\n" +
	"\tlongitude\x18\a \x01(\x01H\x06R\tlongitude\x88\x01\x01B\x0f\n" +
	"\r_display_textB\a\n" +
	"\x05_cityB\t\n" +
	"\a_regionB\n" +
	"\n" +
	"\b_countryB\x14\n" +
	"\x12_facebook_place_idB\v\n" +
	"\t_latitudeB\f\n" +
	"\n" +
	"_longitude\"\xc2\x01\n" +
	"#FacebookMarketplaceMediaObservation\x12/\n" +
	"\x11facebook_photo_id\x18\x01 \x01(\tH\x00R\x0ffacebookPhotoId\x88\x01\x01\x12\x15\n" +
	"\x03url\x18\x02 \x01(\tH\x01R\x03url\x88\x01\x01\x12(\n" +
	"\bposition\x18\x03 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00H\x02R\bposition\x88\x01\x01B\x14\n" +
	"\x12_facebook_photo_idB\x06\n" +
	"\x04_urlB\v\n" +
	"\t_position\"\xc2\x05\n" +
	"$FacebookMarketplaceSellerObservation\x12j\n" +
	"\x0esection_status\x18\x01 \x01(\x0e29.openmarket.api.v1.FacebookMarketplaceSellerSectionStatusB\b\xbaH\x05\x82\x01\x02\x10\x01R\rsectionStatus\x12G\n" +
	"\x13facebook_profile_id\x18\x02 \x01(\tB\x12\xbaH\x0fr\r2\v^[0-9]{8,}$H\x00R\x11facebookProfileId\x88\x01\x01\x12&\n" +
	"\fdisplay_name\x18\x03 \x01(\tH\x01R\vdisplayName\x88\x01\x01\x12$\n" +
	"\vjoined_text\x18\x04 \x01(\tH\x02R\n" +
	"joinedText\x88\x01\x01\x121\n" +
	"\vjoined_year\x18\x05 \x01(\x05B\v\xbaH\b\x1a\x06\x18\x98\x11(\xd4\x0fH\x03R\n" +
	"joinedYear\x88\x01\x01\x124\n" +
	"\x06rating\x18\x06 \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x00\x14@)\x00\x00\x00\x00\x00\x00\x00\x00H\x04R\x06rating\x88\x01\x01\x12/\n" +
	"\frating_count\x18\a \x01(\x05B\a\xbaH\x04\x1a\x02(\x00H\x05R\vratingCount\x88\x01\x01\x12&\n" +
	"\fhighly_rated\x18\b \x01(\bH\x06R\vhighlyRated\x88\x01\x01\x12_\n" +
	"\x0fseller_location\x18\t \x01(\v26.openmarket.api.v1.FacebookMarketplacePlaceObservationR\x0esellerLocationB\x16\n" +
	"\x14_facebook_profile_idB\x0f\n" +
	"\r_display_nameB\x0e\n" +
	"\f_joined_textB\x0e\n" +
	"\f_joined_yearB\t\n" +
	"\a_ratingB\x0f\n" +
	"\r_rating_countB\x0f\n" +
	"\r_highly_rated\"\x9b\x01\n" +
	"*FacebookMarketplaceAvailabilityObservation\x12\x17\n" +
	"\x04sold\x18\x01 \x01(\bH\x00R\x04sold\x88\x01\x01\x12\x17\n" +
	"\x04live\x18\x02 \x01(\bH\x01R\x04live\x88\x01\x01\x12\x1d\n" +
	"\apending\x18\x03 \x01(\bH\x02R\apending\x88\x01\x01B\a\n" +
	"\x05_soldB\a\n" +
	"\x05_liveB\n" +
	"\n" +
	"\b_pending\"\xb4\a\n" +
	"+FacebookMarketplaceSearchListingObservation\x12Z\n" +
	"\acontext\x18\x01 \x01(\v28.openmarket.api.v1.FacebookMarketplaceObservationContextB\x06\xbaH\x03\xc8\x01\x01R\acontext\x12?\n" +
	"\x03key\x18\x02 \x01(\v2%.openmarket.api.v1.FacebookListingKeyB\x06\xbaH\x03\xc8\x01\x01R\x03key\x12\x19\n" +
	"\x05title\x18\x03 \x01(\tH\x00R\x05title\x88\x01\x01\x12L\n" +
	"\x05price\x18\x04 \x01(\v26.openmarket.api.v1.FacebookMarketplacePriceObservationR\x05price\x12a\n" +
	"\x10listing_location\x18\x05 \x01(\v26.openmarket.api.v1.FacebookMarketplacePlaceObservationR\x0flistingLocation\x12!\n" +
	"\tcondition\x18\x06 \x01(\tH\x01R\tcondition\x88\x01\x01\x12[\n" +
	"\rprimary_photo\x18\a \x01(\v26.openmarket.api.v1.FacebookMarketplaceMediaObservationR\fprimaryPhoto\x127\n" +
	"\tlisted_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\blistedAt\x12%\n" +
	"\x0edelivery_types\x18\t \x03(\tR\rdeliveryTypes\x12a\n" +
	"\favailability\x18\n" +
	" \x01(\v2=.openmarket.api.v1.FacebookMarketplaceAvailabilityObservationR\favailability\x125\n" +
	"\x14facebook_category_id\x18\r \x01(\tH\x02R\x12facebookCategoryId\x88\x01\x01\x12:\n" +
	"\x17created_with_seller_app\x18\x0e \x01(\bH\x03R\x14createdWithSellerApp\x88\x01\x01B\b\n" +
	"\x06_titleB\f\n" +
	"\n" +
	"_conditionB\x17\n" +
	"\x15_facebook_category_idB\x1a\n" +
	"\x18_created_with_seller_appJ\x04\b\v\x10\fJ\x04\b\f\x10\rR\x04liveR\apending\"\x8a\a\n" +
	"+FacebookMarketplaceListingDetailObservation\x12Z\n" +
	"\acontext\x18\x01 \x01(\v28.openmarket.api.v1.FacebookMarketplaceObservationContextB\x06\xbaH\x03\xc8\x01\x01R\acontext\x12?\n" +
	"\x03key\x18\x02 \x01(\v2%.openmarket.api.v1.FacebookListingKeyB\x06\xbaH\x03\xc8\x01\x01R\x03key\x12\x19\n" +
	"\x05title\x18\x03 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01\x12L\n" +
	"\x05price\x18\x05 \x01(\v26.openmarket.api.v1.FacebookMarketplacePriceObservationR\x05price\x12a\n" +
	"\x10listing_location\x18\x06 \x01(\v26.openmarket.api.v1.FacebookMarketplacePlaceObservationR\x0flistingLocation\x12!\n" +
	"\tcondition\x18\a \x01(\tH\x02R\tcondition\x88\x01\x01\x12L\n" +
	"\x05media\x18\b \x03(\v26.openmarket.api.v1.FacebookMarketplaceMediaObservationR\x05media\x12)\n" +
	"\x0elisted_at_text\x18\t \x01(\tH\x03R\flistedAtText\x88\x01\x01\x12%\n" +
	"\x0edelivery_types\x18\n" +
	" \x03(\tR\rdeliveryTypes\x12a\n" +
	"\favailability\x18\v \x01(\v2=.openmarket.api.v1.FacebookMarketplaceAvailabilityObservationR\favailability\x12O\n" +
	"\x06seller\x18\x0e \x01(\v27.openmarket.api.v1.FacebookMarketplaceSellerObservationR\x06sellerB\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\f\n" +
	"\n" +
	"_conditionB\x11\n" +
	"\x0f_listed_at_textJ\x04\b\f\x10\rJ\x04\b\r\x10\x0eR\x04liveR\apending\"\xea\x01\n" +
	"%FacebookMarketplaceListingObservation\x12X\n" +
	"\x06search\x18\x01 \x01(\v2>.openmarket.api.v1.FacebookMarketplaceSearchListingObservationH\x00R\x06search\x12X\n" +
	"\x06detail\x18\x02 \x01(\v2>.openmarket.api.v1.FacebookMarketplaceListingDetailObservationH\x00R\x06detailB\r\n" +
	"\vobservation*\xbc\x01\n" +
	"!FacebookMarketplaceBrowserVariant\x124\n" +
	"0FACEBOOK_MARKETPLACE_BROWSER_VARIANT_UNSPECIFIED\x10\x00\x120\n" +
	",FACEBOOK_MARKETPLACE_BROWSER_VARIANT_DESKTOP\x10\x01\x12/\n" +
	"+FACEBOOK_MARKETPLACE_BROWSER_VARIANT_MOBILE\x10\x02*\x87\x02\n" +
	"\x1cFacebookMarketplacePageRoute\x12/\n" +
	"+FACEBOOK_MARKETPLACE_PAGE_ROUTE_UNSPECIFIED\x10\x00\x12*\n" +
	"&FACEBOOK_MARKETPLACE_PAGE_ROUTE_SEARCH\x10\x01\x12,\n" +
	"(FACEBOOK_MARKETPLACE_PAGE_ROUTE_DISCOVER\x10\x02\x12(\n" +
	"$FACEBOOK_MARKETPLACE_PAGE_ROUTE_ITEM\x10\x03\x122\n" +
	".FACEBOOK_MARKETPLACE_PAGE_ROUTE_SELLER_PROFILE\x10\x04*\x86\x02\n" +
	"#FacebookMarketplaceExtractionMethod\x126\n" +
	"2FACEBOOK_MARKETPLACE_EXTRACTION_METHOD_UNSPECIFIED\x10\x00\x12;\n" +
	"7FACEBOOK_MARKETPLACE_EXTRACTION_METHOD_EMBEDDED_GRAPHQL\x10\x01\x127\n" +
	"3FACEBOOK_MARKETPLACE_EXTRACTION_METHOD_RENDERED_DOM\x10\x02\x121\n" +
	"-FACEBOOK_MARKETPLACE_EXTRACTION_METHOD_HYBRID\x10\x03*\xa7\x01\n" +
	"\x1bFacebookAuthenticationState\x12-\n" +
	")FACEBOOK_AUTHENTICATION_STATE_UNSPECIFIED\x10\x00\x12,\n" +
	"(FACEBOOK_AUTHENTICATION_STATE_SIGNED_OUT\x10\x01\x12+\n" +
	"'FACEBOOK_AUTHENTICATION_STATE_SIGNED_IN\x10\x02*\x96\x02\n" +
	"&FacebookMarketplaceSellerSectionStatus\x12:\n" +
	"6FACEBOOK_MARKETPLACE_SELLER_SECTION_STATUS_UNSPECIFIED\x10\x00\x12:\n" +
	"6FACEBOOK_MARKETPLACE_SELLER_SECTION_STATUS_UNAVAILABLE\x10\x01\x12;\n" +
	"7FACEBOOK_MARKETPLACE_SELLER_SECTION_STATUS_NOT_OBSERVED\x10\x02\x127\n" +
	"3FACEBOOK_MARKETPLACE_SELLER_SECTION_STATUS_OBSERVED\x10\x03B\xcc\x01\n" +
	"\x15com.openmarket.api.v1B\fListingProtoP\x01Z?frens.lol/openmarket/backend/pkg/protos/openmarket/api/v1;apiv1\xa2\x02\x03OAX\xaa\x02\x11Openmarket.Api.V1\xca\x02\x11Openmarket\\Api\\V1\xe2\x02\x1dOpenmarket\\Api\\V1\\GPBMetadata\xea\x02\x13Openmarket::Api::V1b\x06proto3"

var (
	file_openmarket_api_v1_listing_proto_rawDescOnce sync.Once
	file_openmarket_api_v1_listing_proto_rawDescData []byte
)

func file_openmarket_api_v1_listing_proto_rawDescGZIP() []byte {
	file_openmarket_api_v1_listing_proto_rawDescOnce.Do(func() {
		file_openmarket_api_v1_listing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openmarket_api_v1_listing_proto_rawDesc), len(file_openmarket_api_v1_listing_proto_rawDesc)))
	})
	return file_openmarket_api_v1_listing_proto_rawDescData
}

var file_openmarket_api_v1_listing_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_openmarket_api_v1_listing_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_openmarket_api_v1_listing_proto_goTypes = []any{
	(FacebookMarketplaceBrowserVariant)(0),              // 0: openmarket.api.v1.FacebookMarketplaceBrowserVariant
	(FacebookMarketplacePageRoute)(0),                   // 1: openmarket.api.v1.FacebookMarketplacePageRoute
	(FacebookMarketplaceExtractionMethod)(0),            // 2: openmarket.api.v1.FacebookMarketplaceExtractionMethod
	(FacebookAuthenticationState)(0),                    // 3: openmarket.api.v1.FacebookAuthenticationState
	(FacebookMarketplaceSellerSectionStatus)(0),         // 4: openmarket.api.v1.FacebookMarketplaceSellerSectionStatus
	(*FacebookMarketplaceObservationContext)(nil),       // 5: openmarket.api.v1.FacebookMarketplaceObservationContext
	(*FacebookListingKey)(nil),                          // 6: openmarket.api.v1.FacebookListingKey
	(*FacebookMarketplacePriceObservation)(nil),         // 7: openmarket.api.v1.FacebookMarketplacePriceObservation
	(*FacebookMarketplacePlaceObservation)(nil),         // 8: openmarket.api.v1.FacebookMarketplacePlaceObservation
	(*FacebookMarketplaceMediaObservation)(nil),         // 9: openmarket.api.v1.FacebookMarketplaceMediaObservation
	(*FacebookMarketplaceSellerObservation)(nil),        // 10: openmarket.api.v1.FacebookMarketplaceSellerObservation
	(*FacebookMarketplaceAvailabilityObservation)(nil),  // 11: openmarket.api.v1.FacebookMarketplaceAvailabilityObservation
	(*FacebookMarketplaceSearchListingObservation)(nil), // 12: openmarket.api.v1.FacebookMarketplaceSearchListingObservation
	(*FacebookMarketplaceListingDetailObservation)(nil), // 13: openmarket.api.v1.FacebookMarketplaceListingDetailObservation
	(*FacebookMarketplaceListingObservation)(nil),       // 14: openmarket.api.v1.FacebookMarketplaceListingObservation
	(*timestamppb.Timestamp)(nil),                       // 15: google.protobuf.Timestamp
}
var file_openmarket_api_v1_listing_proto_depIdxs = []int32{
	0,  // 0: openmarket.api.v1.FacebookMarketplaceObservationContext.browser_variant:type_name -> openmarket.api.v1.FacebookMarketplaceBrowserVariant
	1,  // 1: openmarket.api.v1.FacebookMarketplaceObservationContext.page_route:type_name -> openmarket.api.v1.FacebookMarketplacePageRoute
	2,  // 2: openmarket.api.v1.FacebookMarketplaceObservationContext.extraction_method:type_name -> openmarket.api.v1.FacebookMarketplaceExtractionMethod
	3,  // 3: openmarket.api.v1.FacebookMarketplaceObservationContext.facebook_authentication_state:type_name -> openmarket.api.v1.FacebookAuthenticationState
	15, // 4: openmarket.api.v1.FacebookMarketplaceObservationContext.observed_at:type_name -> google.protobuf.Timestamp
	4,  // 5: openmarket.api.v1.FacebookMarketplaceSellerObservation.section_status:type_name -> openmarket.api.v1.FacebookMarketplaceSellerSectionStatus
	8,  // 6: openmarket.api.v1.FacebookMarketplaceSellerObservation.seller_location:type_name -> openmarket.api.v1.FacebookMarketplacePlaceObservation
	5,  // 7: openmarket.api.v1.FacebookMarketplaceSearchListingObservation.context:type_name -> openmarket.api.v1.FacebookMarketplaceObservationContext
	6,  // 8: openmarket.api.v1.FacebookMarketplaceSearchListingObservation.key:type_name -> openmarket.api.v1.FacebookListingKey
	7,  // 9: openmarket.api.v1.FacebookMarketplaceSearchListingObservation.price:type_name -> openmarket.api.v1.FacebookMarketplacePriceObservation
	8,  // 10: openmarket.api.v1.FacebookMarketplaceSearchListingObservation.listing_location:type_name -> openmarket.api.v1.FacebookMarketplacePlaceObservation
	9,  // 11: openmarket.api.v1.FacebookMarketplaceSearchListingObservation.primary_photo:type_name -> openmarket.api.v1.FacebookMarketplaceMediaObservation
	15, // 12: openmarket.api.v1.FacebookMarketplaceSearchListingObservation.listed_at:type_name -> google.protobuf.Timestamp
	11, // 13: openmarket.api.v1.FacebookMarketplaceSearchListingObservation.availability:type_name -> openmarket.api.v1.FacebookMarketplaceAvailabilityObservation
	5,  // 14: openmarket.api.v1.FacebookMarketplaceListingDetailObservation.context:type_name -> openmarket.api.v1.FacebookMarketplaceObservationContext
	6,  // 15: openmarket.api.v1.FacebookMarketplaceListingDetailObservation.key:type_name -> openmarket.api.v1.FacebookListingKey
	7,  // 16: openmarket.api.v1.FacebookMarketplaceListingDetailObservation.price:type_name -> openmarket.api.v1.FacebookMarketplacePriceObservation
	8,  // 17: openmarket.api.v1.FacebookMarketplaceListingDetailObservation.listing_location:type_name -> openmarket.api.v1.FacebookMarketplacePlaceObservation
	9,  // 18: openmarket.api.v1.FacebookMarketplaceListingDetailObservation.media:type_name -> openmarket.api.v1.FacebookMarketplaceMediaObservation
	11, // 19: openmarket.api.v1.FacebookMarketplaceListingDetailObservation.availability:type_name -> openmarket.api.v1.FacebookMarketplaceAvailabilityObservation
	10, // 20: openmarket.api.v1.FacebookMarketplaceListingDetailObservation.seller:type_name -> openmarket.api.v1.FacebookMarketplaceSellerObservation
	12, // 21: openmarket.api.v1.FacebookMarketplaceListingObservation.search:type_name -> openmarket.api.v1.FacebookMarketplaceSearchListingObservation
	13, // 22: openmarket.api.v1.FacebookMarketplaceListingObservation.detail:type_name -> openmarket.api.v1.FacebookMarketplaceListingDetailObservation
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_openmarket_api_v1_listing_proto_init() }
func file_openmarket_api_v1_listing_proto_init() {
	if File_openmarket_api_v1_listing_proto != nil {
		return
	}
	file_openmarket_api_v1_listing_proto_msgTypes[1].OneofWrappers = []any{}
	file_openmarket_api_v1_listing_proto_msgTypes[2].OneofWrappers = []any{}
	file_openmarket_api_v1_listing_proto_msgTypes[3].OneofWrappers = []any{}
	file_openmarket_api_v1_listing_proto_msgTypes[4].OneofWrappers = []any{}
	file_openmarket_api_v1_listing_proto_msgTypes[5].OneofWrappers = []any{}
	file_openmarket_api_v1_listing_proto_msgTypes[6].OneofWrappers = []any{}
	file_openmarket_api_v1_listing_proto_msgTypes[7].OneofWrappers = []any{}
	file_openmarket_api_v1_listing_proto_msgTypes[8].OneofWrappers = []any{}
	file_openmarket_api_v1_listing_proto_msgTypes[9].OneofWrappers = []any{
		(*FacebookMarketplaceListingObservation_Search)(nil),
		(*FacebookMarketplaceListingObservation_Detail)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openmarket_api_v1_listing_proto_rawDesc), len(file_openmarket_api_v1_listing_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openmarket_api_v1_listing_proto_goTypes,
		DependencyIndexes: file_openmarket_api_v1_listing_proto_depIdxs,
		EnumInfos:         file_openmarket_api_v1_listing_proto_enumTypes,
		MessageInfos:      file_openmarket_api_v1_listing_proto_msgTypes,
	}.Build()
	File_openmarket_api_v1_listing_proto = out.File
	file_openmarket_api_v1_listing_proto_goTypes = nil
	file_openmarket_api_v1_listing_proto_depIdxs = nil
}
