// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: openmarket/api/v1/observation_service.proto

package apiv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Why one observation in the batch was refused. A refusal is per card: a field
// that is present and does not parse fails the whole card rather than being
// nulled, because a null is indistinguishable from "this surface did not tell
// us" (docs/ingest-attribution.md §3.1).
type ObservationRejectionReason int32

const (
	ObservationRejectionReason_OBSERVATION_REJECTION_REASON_UNSPECIFIED ObservationRejectionReason = 0
	// A field arrived in a shape the parser does not model.
	ObservationRejectionReason_OBSERVATION_REJECTION_REASON_MALFORMED_FIELD ObservationRejectionReason = 1
	// Well-formed and outside its envelope: a 1970 timestamp, a price of ten
	// million, a coordinate in the wrong hemisphere (§3.2).
	ObservationRejectionReason_OBSERVATION_REJECTION_REASON_IMPLAUSIBLE_VALUE ObservationRejectionReason = 2
	// Two fields of one observation contradict each other, such as sold and
	// pending both true.
	ObservationRejectionReason_OBSERVATION_REJECTION_REASON_CONTRADICTORY_FIELDS ObservationRejectionReason = 3
	// The same key appeared twice in one batch, or every card in the batch shares
	// one key. Both are extractor collisions rather than real duplicates.
	ObservationRejectionReason_OBSERVATION_REJECTION_REASON_KEY_COLLISION ObservationRejectionReason = 4
	// The observation's shape does not match the batch's route: a detail
	// observation in a search batch, or the reverse.
	ObservationRejectionReason_OBSERVATION_REJECTION_REASON_ROUTE_MISMATCH ObservationRejectionReason = 5
	// The key resolves to a native listing, which no Facebook observation may
	// touch (docs/data-model.md §3).
	ObservationRejectionReason_OBSERVATION_REJECTION_REASON_ORIGIN_CONFLICT ObservationRejectionReason = 6
	// One alias claims a listing another alias has already claimed.
	ObservationRejectionReason_OBSERVATION_REJECTION_REASON_ALIAS_CONFLICT ObservationRejectionReason = 7
	// Nothing was wrong with this card. The circuit breaker is open for the
	// surface it came from, so the whole batch was stored for diagnosis instead
	// of merged (§3.3).
	ObservationRejectionReason_OBSERVATION_REJECTION_REASON_SOURCE_SUSPENDED ObservationRejectionReason = 8
)

// Enum value maps for ObservationRejectionReason.
var (
	ObservationRejectionReason_name = map[int32]string{
		0: "OBSERVATION_REJECTION_REASON_UNSPECIFIED",
		1: "OBSERVATION_REJECTION_REASON_MALFORMED_FIELD",
		2: "OBSERVATION_REJECTION_REASON_IMPLAUSIBLE_VALUE",
		3: "OBSERVATION_REJECTION_REASON_CONTRADICTORY_FIELDS",
		4: "OBSERVATION_REJECTION_REASON_KEY_COLLISION",
		5: "OBSERVATION_REJECTION_REASON_ROUTE_MISMATCH",
		6: "OBSERVATION_REJECTION_REASON_ORIGIN_CONFLICT",
		7: "OBSERVATION_REJECTION_REASON_ALIAS_CONFLICT",
		8: "OBSERVATION_REJECTION_REASON_SOURCE_SUSPENDED",
	}
	ObservationRejectionReason_value = map[string]int32{
		"OBSERVATION_REJECTION_REASON_UNSPECIFIED":          0,
		"OBSERVATION_REJECTION_REASON_MALFORMED_FIELD":      1,
		"OBSERVATION_REJECTION_REASON_IMPLAUSIBLE_VALUE":    2,
		"OBSERVATION_REJECTION_REASON_CONTRADICTORY_FIELDS": 3,
		"OBSERVATION_REJECTION_REASON_KEY_COLLISION":        4,
		"OBSERVATION_REJECTION_REASON_ROUTE_MISMATCH":       5,
		"OBSERVATION_REJECTION_REASON_ORIGIN_CONFLICT":      6,
		"OBSERVATION_REJECTION_REASON_ALIAS_CONFLICT":       7,
		"OBSERVATION_REJECTION_REASON_SOURCE_SUSPENDED":     8,
	}
)

func (x ObservationRejectionReason) Enum() *ObservationRejectionReason {
	p := new(ObservationRejectionReason)
	*p = x
	return p
}

func (x ObservationRejectionReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObservationRejectionReason) Descriptor() protoreflect.EnumDescriptor {
	return file_openmarket_api_v1_observation_service_proto_enumTypes[0].Descriptor()
}

func (ObservationRejectionReason) Type() protoreflect.EnumType {
	return &file_openmarket_api_v1_observation_service_proto_enumTypes[0]
}

func (x ObservationRejectionReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObservationRejectionReason.Descriptor instead.
func (ObservationRejectionReason) EnumDescriptor() ([]byte, []int) {
	return file_openmarket_api_v1_observation_service_proto_rawDescGZIP(), []int{0}
}

// What the client's extractor saw, as distinct from what it managed to parse.
//
// Without this, an extractor that drops every card on a page and a page with
// nothing on it produce the identical server-side record. That is the failure
// this whole ingest path is built to make loud, so the counts travel with the
// batch even though nothing merges them into a listing.
type ClientExtractionCounts struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Candidate cards the extractor found before parsing. Never fewer than the
	// number of observations in the request.
	CardsSeen int32 `protobuf:"varint,1,opt,name=cards_seen,json=cardsSeen,proto3" json:"cards_seen,omitempty"`
	// Deduplicated reason tokens for what the client dropped, in the vocabulary
	// its own logs use (docs/parsing-conventions.md §1). Free-form on purpose:
	// an unrecognised reason is still legible, where an enum would collapse it.
	DropReasons   []string `protobuf:"bytes,2,rep,name=drop_reasons,json=dropReasons,proto3" json:"drop_reasons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientExtractionCounts) Reset() {
	*x = ClientExtractionCounts{}
	mi := &file_openmarket_api_v1_observation_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientExtractionCounts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientExtractionCounts) ProtoMessage() {}

func (x *ClientExtractionCounts) ProtoReflect() protoreflect.Message {
	mi := &file_openmarket_api_v1_observation_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientExtractionCounts.ProtoReflect.Descriptor instead.
func (*ClientExtractionCounts) Descriptor() ([]byte, []int) {
	return file_openmarket_api_v1_observation_service_proto_rawDescGZIP(), []int{0}
}

func (x *ClientExtractionCounts) GetCardsSeen() int32 {
	if x != nil {
		return x.CardsSeen
	}
	return 0
}

func (x *ClientExtractionCounts) GetDropReasons() []string {
	if x != nil {
		return x.DropReasons
	}
	return nil
}

type SubmitObservationsRequest struct {
	state   protoimpl.MessageState                 `protogen:"open.v1"`
	Context *FacebookMarketplaceObservationContext `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	// Identifies the parser, not the app. Debug builds pin the app build to 1
	// (docs/data-model.md §2), so the app version alone cannot attribute a
	// regression to the code that caused it.
	ExtractorRevision string                  `protobuf:"bytes,3,opt,name=extractor_revision,json=extractorRevision,proto3" json:"extractor_revision,omitempty"`
	Counts            *ClientExtractionCounts `protobuf:"bytes,4,opt,name=counts,proto3" json:"counts,omitempty"`
	// Hash of the sorted set of key paths the extractor saw in a structured
	// payload, values excluded. A fingerprint nobody has seen before, arriving
	// across many devices at once, is Facebook shipping a change — and it fires
	// whether or not anything failed to parse (docs/ingest-attribution.md §3.4).
	ShapeFingerprint []byte                                   `protobuf:"bytes,5,opt,name=shape_fingerprint,json=shapeFingerprint,proto3,oneof" json:"shape_fingerprint,omitempty"`
	Observations     []*FacebookMarketplaceListingObservation `protobuf:"bytes,6,rep,name=observations,proto3" json:"observations,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubmitObservationsRequest) Reset() {
	*x = SubmitObservationsRequest{}
	mi := &file_openmarket_api_v1_observation_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitObservationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitObservationsRequest) ProtoMessage() {}

func (x *SubmitObservationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openmarket_api_v1_observation_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitObservationsRequest.ProtoReflect.Descriptor instead.
func (*SubmitObservationsRequest) Descriptor() ([]byte, []int) {
	return file_openmarket_api_v1_observation_service_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitObservationsRequest) GetContext() *FacebookMarketplaceObservationContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *SubmitObservationsRequest) GetExtractorRevision() string {
	if x != nil {
		return x.ExtractorRevision
	}
	return ""
}

func (x *SubmitObservationsRequest) GetCounts() *ClientExtractionCounts {
	if x != nil {
		return x.Counts
	}
	return nil
}

func (x *SubmitObservationsRequest) GetShapeFingerprint() []byte {
	if x != nil {
		return x.ShapeFingerprint
	}
	return nil
}

func (x *SubmitObservationsRequest) GetObservations() []*FacebookMarketplaceListingObservation {
	if x != nil {
		return x.Observations
	}
	return nil
}

type ObservationRejection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Index into the request's observations, so the client can name the card in
	// its own log without the server echoing any of its content back.
	Index  int32                      `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Reason ObservationRejectionReason `protobuf:"varint,2,opt,name=reason,proto3,enum=openmarket.api.v1.ObservationRejectionReason" json:"reason,omitempty"`
	// Dotted path of the field that failed, empty when the whole observation did.
	FieldPath     string `protobuf:"bytes,3,opt,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObservationRejection) Reset() {
	*x = ObservationRejection{}
	mi := &file_openmarket_api_v1_observation_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObservationRejection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObservationRejection) ProtoMessage() {}

func (x *ObservationRejection) ProtoReflect() protoreflect.Message {
	mi := &file_openmarket_api_v1_observation_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObservationRejection.ProtoReflect.Descriptor instead.
func (*ObservationRejection) Descriptor() ([]byte, []int) {
	return file_openmarket_api_v1_observation_service_proto_rawDescGZIP(), []int{2}
}

func (x *ObservationRejection) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ObservationRejection) GetReason() ObservationRejectionReason {
	if x != nil {
		return x.Reason
	}
	return ObservationRejectionReason_OBSERVATION_REJECTION_REASON_UNSPECIFIED
}

func (x *ObservationRejection) GetFieldPath() string {
	if x != nil {
		return x.FieldPath
	}
	return ""
}

type SubmitObservationsResponse struct {
	state       protoimpl.MessageState  `protogen:"open.v1"`
	BatchId     string                  `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Accepted    int32                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Quarantined int32                   `protobuf:"varint,3,opt,name=quarantined,proto3" json:"quarantined,omitempty"`
	Rejections  []*ObservationRejection `protobuf:"bytes,4,rep,name=rejections,proto3" json:"rejections,omitempty"`
	// The circuit breaker is open for this browser variant, page route,
	// extraction method and extractor revision: the combination's quarantine rate
	// crossed its threshold, so nothing from it is reaching canonical rows
	// (docs/ingest-attribution.md §3.3). The batch was stored for diagnosis and
	// the client should stop submitting from this surface until it updates.
	SourceSuspended bool `protobuf:"varint,5,opt,name=source_suspended,json=sourceSuspended,proto3" json:"source_suspended,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubmitObservationsResponse) Reset() {
	*x = SubmitObservationsResponse{}
	mi := &file_openmarket_api_v1_observation_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitObservationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitObservationsResponse) ProtoMessage() {}

func (x *SubmitObservationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openmarket_api_v1_observation_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitObservationsResponse.ProtoReflect.Descriptor instead.
func (*SubmitObservationsResponse) Descriptor() ([]byte, []int) {
	return file_openmarket_api_v1_observation_service_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitObservationsResponse) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *SubmitObservationsResponse) GetAccepted() int32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *SubmitObservationsResponse) GetQuarantined() int32 {
	if x != nil {
		return x.Quarantined
	}
	return 0
}

func (x *SubmitObservationsResponse) GetRejections() []*ObservationRejection {
	if x != nil {
		return x.Rejections
	}
	return nil
}

func (x *SubmitObservationsResponse) GetSourceSuspended() bool {
	if x != nil {
		return x.SourceSuspended
	}
	return false
}

var File_openmarket_api_v1_observation_service_proto protoreflect.FileDescriptor

const file_openmarket_api_v1_observation_service_proto_rawDesc = "" +
	"\n" +
	"+openmarket/api/v1/observation_service.proto\x12\x11openmarket.api.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fopenmarket/api/v1/listing.proto\"s\n" +
	"\x16ClientExtractionCounts\x12&\n" +
	"\n" +
	"cards_seen\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\tcardsSeen\x121\n" +
	"\fdrop_reasons\x18\x02 \x03(\tB\x0e\xbaH\v\x92\x01\b\x10\x10\"\x04r\x02\x18@R\vdropReasons\"\xc2\x03\n" +
	"\x19SubmitObservationsRequest\x12Z\n" +
	"\acontext\x18\x01 \x01(\v28.openmarket.api.v1.FacebookMarketplaceObservationContextB\x06\xbaH\x03\xc8\x01\x01R\acontext\x128\n" +
	"\x12extractor_revision\x18\x03 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18@R\x11extractorRevision\x12I\n" +
	"\x06counts\x18\x04 \x01(\v2).openmarket.api.v1.ClientExtractionCountsB\x06\xbaH\x03\xc8\x01\x01R\x06counts\x129\n" +
	"\x11shape_fingerprint\x18\x05 \x01(\fB\a\xbaH\x04z\x02h H\x00R\x10shapeFingerprint\x88\x01\x01\x12f\n" +
	"\fobservations\x18\x06 \x03(\v28.openmarket.api.v1.FacebookMarketplaceListingObservationB\b\xbaH\x05\x92\x01\x02\x10dR\fobservationsB\x14\n" +
	"\x12_shape_fingerprintJ\x04\b\x02\x10\x03R\x05query\"\x92\x01\n" +
	"\x14ObservationRejection\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12E\n" +
	"\x06reason\x18\x02 \x01(\x0e2-.openmarket.api.v1.ObservationRejectionReasonR\x06reason\x12\x1d\n" +
	"\n" +
	"field_path\x18\x03 \x01(\tR\tfieldPath\"\xe9\x01\n" +
	"\x1aSubmitObservationsResponse\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\x05R\baccepted\x12 \n" +
	"\vquarantined\x18\x03 \x01(\x05R\vquarantined\x12G\n" +
	"\n" +
	"rejections\x18\x04 \x03(\v2'.openmarket.api.v1.ObservationRejectionR\n" +
	"rejections\x12)\n" +
	"\x10source_suspended\x18\x05 \x01(\bR\x0fsourceSuspended*\xde\x03\n" +
	"\x1aObservationRejectionReason\x12,\n" +
	"(OBSERVATION_REJECTION_REASON_UNSPECIFIED\x10\x00\x120\n" +
	",OBSERVATION_REJECTION_REASON_MALFORMED_FIELD\x10\x01\x122\n" +
	".OBSERVATION_REJECTION_REASON_IMPLAUSIBLE_VALUE\x10\x02\x125\n" +
	"1OBSERVATION_REJECTION_REASON_CONTRADICTORY_FIELDS\x10\x03\x12.\n" +
	"*OBSERVATION_REJECTION_REASON_KEY_COLLISION\x10\x04\x12/\n" +
	"+OBSERVATION_REJECTION_REASON_ROUTE_MISMATCH\x10\x05\x120\n" +
	",OBSERVATION_REJECTION_REASON_ORIGIN_CONFLICT\x10\x06\x12/\n" +
	"+OBSERVATION_REJECTION_REASON_ALIAS_CONFLICT\x10\a\x121\n" +
	"-OBSERVATION_REJECTION_REASON_SOURCE_SUSPENDED\x10\b2\x89\x01\n" +
	"\x12ObservationService\x12s\n" +
	"\x12SubmitObservations\x12,.openmarket.api.v1.SubmitObservationsRequest\x1a-.openmarket.api.v1.SubmitObservationsResponse\"\x00B\xd7\x01\n" +
	"\x15com.openmarket.api.v1B\x17ObservationServiceProtoP\x01Z?frens.lol/openmarket/backend/pkg/protos/openmarket/api/v1;apiv1\xa2\x02\x03OAX\xaa\x02\x11Openmarket.Api.V1\xca\x02\x11Openmarket\\Api\\V1\xe2\x02\x1dOpenmarket\\Api\\V1\\GPBMetadata\xea\x02\x13Openmarket::Api::V1b\x06proto3"

var (
	file_openmarket_api_v1_observation_service_proto_rawDescOnce sync.Once
	file_openmarket_api_v1_observation_service_proto_rawDescData []byte
)

func file_openmarket_api_v1_observation_service_proto_rawDescGZIP() []byte {
	file_openmarket_api_v1_observation_service_proto_rawDescOnce.Do(func() {
		file_openmarket_api_v1_observation_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openmarket_api_v1_observation_service_proto_rawDesc), len(file_openmarket_api_v1_observation_service_proto_rawDesc)))
	})
	return file_openmarket_api_v1_observation_service_proto_rawDescData
}

var file_openmarket_api_v1_observation_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_openmarket_api_v1_observation_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_openmarket_api_v1_observation_service_proto_goTypes = []any{
	(ObservationRejectionReason)(0),               // 0: openmarket.api.v1.ObservationRejectionReason
	(*ClientExtractionCounts)(nil),                // 1: openmarket.api.v1.ClientExtractionCounts
	(*SubmitObservationsRequest)(nil),             // 2: openmarket.api.v1.SubmitObservationsRequest
	(*ObservationRejection)(nil),                  // 3: openmarket.api.v1.ObservationRejection
	(*SubmitObservationsResponse)(nil),            // 4: openmarket.api.v1.SubmitObservationsResponse
	(*FacebookMarketplaceObservationContext)(nil), // 5: openmarket.api.v1.FacebookMarketplaceObservationContext
	(*FacebookMarketplaceListingObservation)(nil), // 6: openmarket.api.v1.FacebookMarketplaceListingObservation
}
var file_openmarket_api_v1_observation_service_proto_depIdxs = []int32{
	5, // 0: openmarket.api.v1.SubmitObservationsRequest.context:type_name -> openmarket.api.v1.FacebookMarketplaceObservationContext
	1, // 1: openmarket.api.v1.SubmitObservationsRequest.counts:type_name -> openmarket.api.v1.ClientExtractionCounts
	6, // 2: openmarket.api.v1.SubmitObservationsRequest.observations:type_name -> openmarket.api.v1.FacebookMarketplaceListingObservation
	0, // 3: openmarket.api.v1.ObservationRejection.reason:type_name -> openmarket.api.v1.ObservationRejectionReason
	3, // 4: openmarket.api.v1.SubmitObservationsResponse.rejections:type_name -> openmarket.api.v1.ObservationRejection
	2, // 5: openmarket.api.v1.ObservationService.SubmitObservations:input_type -> openmarket.api.v1.SubmitObservationsRequest
	4, // 6: openmarket.api.v1.ObservationService.SubmitObservations:output_type -> openmarket.api.v1.SubmitObservationsResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_openmarket_api_v1_observation_service_proto_init() }
func file_openmarket_api_v1_observation_service_proto_init() {
	if File_openmarket_api_v1_observation_service_proto != nil {
		return
	}
	file_openmarket_api_v1_listing_proto_init()
	file_openmarket_api_v1_observation_service_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openmarket_api_v1_observation_service_proto_rawDesc), len(file_openmarket_api_v1_observation_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_openmarket_api_v1_observation_service_proto_goTypes,
		DependencyIndexes: file_openmarket_api_v1_observation_service_proto_depIdxs,
		EnumInfos:         file_openmarket_api_v1_observation_service_proto_enumTypes,
		MessageInfos:      file_openmarket_api_v1_observation_service_proto_msgTypes,
	}.Build()
	File_openmarket_api_v1_observation_service_proto = out.File
	file_openmarket_api_v1_observation_service_proto_goTypes = nil
	file_openmarket_api_v1_observation_service_proto_depIdxs = nil
}
