// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: openmarket/api/v1/pricing_service.proto

package apiv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Facebook's own condition values, so a guess here can be handed straight to
// the search filter later (`SearchQuery.Condition`).
type ItemCondition int32

const (
	ItemCondition_ITEM_CONDITION_UNSPECIFIED   ItemCondition = 0
	ItemCondition_ITEM_CONDITION_NEW           ItemCondition = 1
	ItemCondition_ITEM_CONDITION_USED_LIKE_NEW ItemCondition = 2
	ItemCondition_ITEM_CONDITION_USED_GOOD     ItemCondition = 3
	ItemCondition_ITEM_CONDITION_USED_FAIR     ItemCondition = 4
)

// Enum value maps for ItemCondition.
var (
	ItemCondition_name = map[int32]string{
		0: "ITEM_CONDITION_UNSPECIFIED",
		1: "ITEM_CONDITION_NEW",
		2: "ITEM_CONDITION_USED_LIKE_NEW",
		3: "ITEM_CONDITION_USED_GOOD",
		4: "ITEM_CONDITION_USED_FAIR",
	}
	ItemCondition_value = map[string]int32{
		"ITEM_CONDITION_UNSPECIFIED":   0,
		"ITEM_CONDITION_NEW":           1,
		"ITEM_CONDITION_USED_LIKE_NEW": 2,
		"ITEM_CONDITION_USED_GOOD":     3,
		"ITEM_CONDITION_USED_FAIR":     4,
	}
)

func (x ItemCondition) Enum() *ItemCondition {
	p := new(ItemCondition)
	*p = x
	return p
}

func (x ItemCondition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemCondition) Descriptor() protoreflect.EnumDescriptor {
	return file_openmarket_api_v1_pricing_service_proto_enumTypes[0].Descriptor()
}

func (ItemCondition) Type() protoreflect.EnumType {
	return &file_openmarket_api_v1_pricing_service_proto_enumTypes[0]
}

func (x ItemCondition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemCondition.Descriptor instead.
func (ItemCondition) EnumDescriptor() ([]byte, []int) {
	return file_openmarket_api_v1_pricing_service_proto_rawDescGZIP(), []int{0}
}

// What the seller is holding, as the model reads it.
type IdentifyItemRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The item, in the seller's words. Not a query — people describe what they
	// are selling, and `SearchTerm` exists because that is never phrased as one.
	//
	// No `min_len`: an empty description is a valid request when a photo carries
	// it. The three-character floor lives in the rule above, where it only
	// applies to the case that needs it.
	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// JPEG, downscaled by the client before it is sent.
	//
	// **Repeated, capped at one.** One photo is all the app offers today and all
	// the server will accept — but a seller with a scratched tabletop and an
	// intact drawer front obviously wants to send both, and raising this cap
	// later must not cost an App Store release. `repeated` now makes that a
	// one-line change to `max_items`; `optional bytes photo` now would make it a
	// new field number and a compatibility shim.
	//
	// When the cap does rise, the prompt has to say the photos are the same item
	// from different angles. Left implicit, a model describes them as separate
	// items — the same class of failure as taking the identity from the comps.
	//
	// Optional, as long as there are words: an empty list runs on the description
	// alone, which is roughly what the tool did before it could see anything.
	// That keeps a failed or skipped photo pick a degradation rather than a dead
	// end. See the message rule above for the one combination that is refused.
	Photos        [][]byte `protobuf:"bytes,2,rep,name=photos,proto3" json:"photos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentifyItemRequest) Reset() {
	*x = IdentifyItemRequest{}
	mi := &file_openmarket_api_v1_pricing_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentifyItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentifyItemRequest) ProtoMessage() {}

func (x *IdentifyItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openmarket_api_v1_pricing_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentifyItemRequest.ProtoReflect.Descriptor instead.
func (*IdentifyItemRequest) Descriptor() ([]byte, []int) {
	return file_openmarket_api_v1_pricing_service_proto_rawDescGZIP(), []int{0}
}

func (x *IdentifyItemRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *IdentifyItemRequest) GetPhotos() [][]byte {
	if x != nil {
		return x.Photos
	}
	return nil
}

type IdentifyItemResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Threads the whole run together: the client carries it into PriceItem, into
	// feedback, and into the copy report. Issued here because the row is written
	// here — a run that dies before it finds a market is still a row worth having.
	PriceCheckId string `protobuf:"bytes,1,opt,name=price_check_id,json=priceCheckId,proto3" json:"price_check_id,omitempty"`
	// What the thing is, in as few words as identify it. Shown in the transcript,
	// because a price guide is only as good as what it thought it was pricing,
	// and the user is the one who can see it is wrong.
	IdentifiedName string `protobuf:"bytes,2,opt,name=identified_name,json=identifiedName,proto3" json:"identified_name,omitempty"`
	// What to search Facebook for. One or two — the second is a fallback phrasing,
	// not a second item.
	//
	// Two is the cap because each one costs up to two page loads (active and
	// sold), and `RequestPacer` is a shared actor: a third query spends the
	// browse tab's request budget to hedge a query that was probably fine.
	SearchQueries []string `protobuf:"bytes,3,rep,name=search_queries,json=searchQueries,proto3" json:"search_queries,omitempty"`
	// A guess from the photo, and only ever a guess. Never used to narrow the
	// comparable search — condition words narrow the search without narrowing the
	// market, which is why `SearchTerm` strips them.
	Condition ItemCondition `protobuf:"varint,4,opt,name=condition,proto3,enum=openmarket.api.v1.ItemCondition" json:"condition,omitempty"`
	// Distinguishing facts the model could see or was told: "six drawers",
	// "original box", "left armrest torn". Feeds the listing description, and
	// exists so that description is built from observations rather than invented
	// — a small model asked for richer prose wrote "a few minor scratches on the
	// frame" about a bike whose seller mentioned none.
	KeyAttributes []string `protobuf:"bytes,5,rep,name=key_attributes,json=keyAttributes,proto3" json:"key_attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentifyItemResponse) Reset() {
	*x = IdentifyItemResponse{}
	mi := &file_openmarket_api_v1_pricing_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentifyItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentifyItemResponse) ProtoMessage() {}

func (x *IdentifyItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openmarket_api_v1_pricing_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentifyItemResponse.ProtoReflect.Descriptor instead.
func (*IdentifyItemResponse) Descriptor() ([]byte, []int) {
	return file_openmarket_api_v1_pricing_service_proto_rawDescGZIP(), []int{1}
}

func (x *IdentifyItemResponse) GetPriceCheckId() string {
	if x != nil {
		return x.PriceCheckId
	}
	return ""
}

func (x *IdentifyItemResponse) GetIdentifiedName() string {
	if x != nil {
		return x.IdentifiedName
	}
	return ""
}

func (x *IdentifyItemResponse) GetSearchQueries() []string {
	if x != nil {
		return x.SearchQueries
	}
	return nil
}

func (x *IdentifyItemResponse) GetCondition() ItemCondition {
	if x != nil {
		return x.Condition
	}
	return ItemCondition_ITEM_CONDITION_UNSPECIFIED
}

func (x *IdentifyItemResponse) GetKeyAttributes() []string {
	if x != nil {
		return x.KeyAttributes
	}
	return nil
}

// One comparable, as the phone read it off a card.
type Comparable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Title string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// Minor units. Absent when the card had no price we could read, which is
	// ordinary — and different from zero, which means Free. Free items are
	// excluded from the arithmetic upstream (seven of twelve sold couches in San
	// Francisco were free), but they are still sent, because "most of these went
	// for nothing" is a fact about the market.
	PriceMinor *int64 `protobuf:"varint,2,opt,name=price_minor,json=priceMinor,proto3,oneof" json:"price_minor,omitempty"`
	// Seller-marked. Means "no longer for sale", never "sold for this".
	IsSold bool `protobuf:"varint,3,opt,name=is_sold,json=isSold,proto3" json:"is_sold,omitempty"`
	// How long it had been listed. On a sold card this is the useful one: it is
	// an upper bound on how long it took to sell, because Facebook publishes no
	// sale date — `creation_time` is the only time field on a listing.
	DaysListed    *int32  `protobuf:"varint,4,opt,name=days_listed,json=daysListed,proto3,oneof" json:"days_listed,omitempty"`
	City          *string `protobuf:"bytes,5,opt,name=city,proto3,oneof" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comparable) Reset() {
	*x = Comparable{}
	mi := &file_openmarket_api_v1_pricing_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comparable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comparable) ProtoMessage() {}

func (x *Comparable) ProtoReflect() protoreflect.Message {
	mi := &file_openmarket_api_v1_pricing_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comparable.ProtoReflect.Descriptor instead.
func (*Comparable) Descriptor() ([]byte, []int) {
	return file_openmarket_api_v1_pricing_service_proto_rawDescGZIP(), []int{2}
}

func (x *Comparable) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Comparable) GetPriceMinor() int64 {
	if x != nil && x.PriceMinor != nil {
		return *x.PriceMinor
	}
	return 0
}

func (x *Comparable) GetIsSold() bool {
	if x != nil {
		return x.IsSold
	}
	return false
}

func (x *Comparable) GetDaysListed() int32 {
	if x != nil && x.DaysListed != nil {
		return *x.DaysListed
	}
	return 0
}

func (x *Comparable) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

// The market reduced to numbers, computed by `PriceGuide` on the device.
//
// **Sent because the model must not derive them.** Asked to justify its own
// figure against fourteen prices it had just been shown, the on-device model
// wrote "you are asking CA$20 more than the median price of CA$80" — the median
// was CA$77 and the gap was CA$33, two wrong numbers in one confident sentence,
// printed under the one figure a person acts on. Arithmetic about a sample
// belongs to whoever computed the sample.
type MarketStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// How many comparables carried a usable price. Not the number sent: a guide
	// built from four of fifteen cards is a different claim from one built from
	// all fifteen.
	PricedCount  int32 `protobuf:"varint,1,opt,name=priced_count,json=pricedCount,proto3" json:"priced_count,omitempty"`
	MedianMinor  int64 `protobuf:"varint,2,opt,name=median_minor,json=medianMinor,proto3" json:"median_minor,omitempty"`
	LowestMinor  int64 `protobuf:"varint,3,opt,name=lowest_minor,json=lowestMinor,proto3" json:"lowest_minor,omitempty"`
	HighestMinor int64 `protobuf:"varint,4,opt,name=highest_minor,json=highestMinor,proto3" json:"highest_minor,omitempty"`
	// The interquartile band. Absent below four samples, where quartiles of three
	// numbers are just the three numbers.
	LowerQuartileMinor *int64 `protobuf:"varint,5,opt,name=lower_quartile_minor,json=lowerQuartileMinor,proto3,oneof" json:"lower_quartile_minor,omitempty"`
	UpperQuartileMinor *int64 `protobuf:"varint,6,opt,name=upper_quartile_minor,json=upperQuartileMinor,proto3,oneof" json:"upper_quartile_minor,omitempty"`
	// The symbol the cards were written in — "$", "CA$", "£" — voted on across
	// the sample. Not an ISO code, because nothing here learns one. A price
	// rendered "$80" beside a strip of CA$ comparables is wrong by about a third.
	CurrencySymbol string `protobuf:"bytes,7,opt,name=currency_symbol,json=currencySymbol,proto3" json:"currency_symbol,omitempty"`
	// What sold, and how fast. Empty is an ordinary outcome, not a failure.
	//
	// This half can support "this price worked" and can never support "this price
	// is too high" — it is filtered on having sold, so the things that failed to
	// sell at a price are exactly the ones missing. The prompt has to say so, or
	// a model handed sold prices treats them as a target.
	SoldCount        int32  `protobuf:"varint,8,opt,name=sold_count,json=soldCount,proto3" json:"sold_count,omitempty"`
	MedianDaysToSell *int32 `protobuf:"varint,9,opt,name=median_days_to_sell,json=medianDaysToSell,proto3,oneof" json:"median_days_to_sell,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MarketStats) Reset() {
	*x = MarketStats{}
	mi := &file_openmarket_api_v1_pricing_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketStats) ProtoMessage() {}

func (x *MarketStats) ProtoReflect() protoreflect.Message {
	mi := &file_openmarket_api_v1_pricing_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketStats.ProtoReflect.Descriptor instead.
func (*MarketStats) Descriptor() ([]byte, []int) {
	return file_openmarket_api_v1_pricing_service_proto_rawDescGZIP(), []int{3}
}

func (x *MarketStats) GetPricedCount() int32 {
	if x != nil {
		return x.PricedCount
	}
	return 0
}

func (x *MarketStats) GetMedianMinor() int64 {
	if x != nil {
		return x.MedianMinor
	}
	return 0
}

func (x *MarketStats) GetLowestMinor() int64 {
	if x != nil {
		return x.LowestMinor
	}
	return 0
}

func (x *MarketStats) GetHighestMinor() int64 {
	if x != nil {
		return x.HighestMinor
	}
	return 0
}

func (x *MarketStats) GetLowerQuartileMinor() int64 {
	if x != nil && x.LowerQuartileMinor != nil {
		return *x.LowerQuartileMinor
	}
	return 0
}

func (x *MarketStats) GetUpperQuartileMinor() int64 {
	if x != nil && x.UpperQuartileMinor != nil {
		return *x.UpperQuartileMinor
	}
	return 0
}

func (x *MarketStats) GetCurrencySymbol() string {
	if x != nil {
		return x.CurrencySymbol
	}
	return ""
}

func (x *MarketStats) GetSoldCount() int32 {
	if x != nil {
		return x.SoldCount
	}
	return 0
}

func (x *MarketStats) GetMedianDaysToSell() int32 {
	if x != nil && x.MedianDaysToSell != nil {
		return *x.MedianDaysToSell
	}
	return 0
}

type PriceItemRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	PriceCheckId string                 `protobuf:"bytes,1,opt,name=price_check_id,json=priceCheckId,proto3" json:"price_check_id,omitempty"`
	// Which of the returned queries actually produced this market. Recorded so a
	// bad identification and a bad market are distinguishable afterwards.
	SearchQueryUsed string `protobuf:"bytes,2,opt,name=search_query_used,json=searchQueryUsed,proto3" json:"search_query_used,omitempty"`
	// Capped well above the ~15 a search page returns, so the ceiling is a bound
	// on abuse rather than a limit the feature can reach.
	Comparables []*Comparable `protobuf:"bytes,3,rep,name=comparables,proto3" json:"comparables,omitempty"`
	Stats       *MarketStats  `protobuf:"bytes,4,opt,name=stats,proto3" json:"stats,omitempty"`
	// Where, in the words the user sees — "San Francisco Bay Area". Context for
	// the listing copy, not a filter.
	MarketName    string `protobuf:"bytes,5,opt,name=market_name,json=marketName,proto3" json:"market_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceItemRequest) Reset() {
	*x = PriceItemRequest{}
	mi := &file_openmarket_api_v1_pricing_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceItemRequest) ProtoMessage() {}

func (x *PriceItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openmarket_api_v1_pricing_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceItemRequest.ProtoReflect.Descriptor instead.
func (*PriceItemRequest) Descriptor() ([]byte, []int) {
	return file_openmarket_api_v1_pricing_service_proto_rawDescGZIP(), []int{4}
}

func (x *PriceItemRequest) GetPriceCheckId() string {
	if x != nil {
		return x.PriceCheckId
	}
	return ""
}

func (x *PriceItemRequest) GetSearchQueryUsed() string {
	if x != nil {
		return x.SearchQueryUsed
	}
	return ""
}

func (x *PriceItemRequest) GetComparables() []*Comparable {
	if x != nil {
		return x.Comparables
	}
	return nil
}

func (x *PriceItemRequest) GetStats() *MarketStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *PriceItemRequest) GetMarketName() string {
	if x != nil {
		return x.MarketName
	}
	return ""
}

type PriceItemResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Minor units, and a judgement rather than a calculation: the model picks a
	// point given the band, the item, and what sold. The client clamps it to the
	// observed range before showing it, because a recommendation outside the
	// evidence is not a bolder opinion about the market, it is a number with
	// nothing behind it.
	RecommendedPriceMinor int64 `protobuf:"varint,1,opt,name=recommended_price_minor,json=recommendedPriceMinor,proto3" json:"recommended_price_minor,omitempty"`
	// A listing title and body, ready to paste into Facebook.
	Title         string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceItemResponse) Reset() {
	*x = PriceItemResponse{}
	mi := &file_openmarket_api_v1_pricing_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceItemResponse) ProtoMessage() {}

func (x *PriceItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openmarket_api_v1_pricing_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceItemResponse.ProtoReflect.Descriptor instead.
func (*PriceItemResponse) Descriptor() ([]byte, []int) {
	return file_openmarket_api_v1_pricing_service_proto_rawDescGZIP(), []int{5}
}

func (x *PriceItemResponse) GetRecommendedPriceMinor() int64 {
	if x != nil {
		return x.RecommendedPriceMinor
	}
	return 0
}

func (x *PriceItemResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PriceItemResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type SubmitPriceCheckFeedbackRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	PriceCheckId string                 `protobuf:"bytes,1,opt,name=price_check_id,json=priceCheckId,proto3" json:"price_check_id,omitempty"`
	// Answered, either way. There is no third value here because the third state
	// is not calling this — which is why the column is nullable and why the screen
	// shows two buttons rather than one checkbox: a checkbox cannot tell "no"
	// from "didn't answer", and those are different findings.
	Helpful       bool `protobuf:"varint,2,opt,name=helpful,proto3" json:"helpful,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitPriceCheckFeedbackRequest) Reset() {
	*x = SubmitPriceCheckFeedbackRequest{}
	mi := &file_openmarket_api_v1_pricing_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitPriceCheckFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitPriceCheckFeedbackRequest) ProtoMessage() {}

func (x *SubmitPriceCheckFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openmarket_api_v1_pricing_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitPriceCheckFeedbackRequest.ProtoReflect.Descriptor instead.
func (*SubmitPriceCheckFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_openmarket_api_v1_pricing_service_proto_rawDescGZIP(), []int{6}
}

func (x *SubmitPriceCheckFeedbackRequest) GetPriceCheckId() string {
	if x != nil {
		return x.PriceCheckId
	}
	return ""
}

func (x *SubmitPriceCheckFeedbackRequest) GetHelpful() bool {
	if x != nil {
		return x.Helpful
	}
	return false
}

type SubmitPriceCheckFeedbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitPriceCheckFeedbackResponse) Reset() {
	*x = SubmitPriceCheckFeedbackResponse{}
	mi := &file_openmarket_api_v1_pricing_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitPriceCheckFeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitPriceCheckFeedbackResponse) ProtoMessage() {}

func (x *SubmitPriceCheckFeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openmarket_api_v1_pricing_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitPriceCheckFeedbackResponse.ProtoReflect.Descriptor instead.
func (*SubmitPriceCheckFeedbackResponse) Descriptor() ([]byte, []int) {
	return file_openmarket_api_v1_pricing_service_proto_rawDescGZIP(), []int{7}
}

type RecordPriceCopiedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PriceCheckId  string                 `protobuf:"bytes,1,opt,name=price_check_id,json=priceCheckId,proto3" json:"price_check_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordPriceCopiedRequest) Reset() {
	*x = RecordPriceCopiedRequest{}
	mi := &file_openmarket_api_v1_pricing_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordPriceCopiedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordPriceCopiedRequest) ProtoMessage() {}

func (x *RecordPriceCopiedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openmarket_api_v1_pricing_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordPriceCopiedRequest.ProtoReflect.Descriptor instead.
func (*RecordPriceCopiedRequest) Descriptor() ([]byte, []int) {
	return file_openmarket_api_v1_pricing_service_proto_rawDescGZIP(), []int{8}
}

func (x *RecordPriceCopiedRequest) GetPriceCheckId() string {
	if x != nil {
		return x.PriceCheckId
	}
	return ""
}

type RecordPriceCopiedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordPriceCopiedResponse) Reset() {
	*x = RecordPriceCopiedResponse{}
	mi := &file_openmarket_api_v1_pricing_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordPriceCopiedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordPriceCopiedResponse) ProtoMessage() {}

func (x *RecordPriceCopiedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openmarket_api_v1_pricing_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordPriceCopiedResponse.ProtoReflect.Descriptor instead.
func (*RecordPriceCopiedResponse) Descriptor() ([]byte, []int) {
	return file_openmarket_api_v1_pricing_service_proto_rawDescGZIP(), []int{9}
}

var File_openmarket_api_v1_pricing_service_proto protoreflect.FileDescriptor

const file_openmarket_api_v1_pricing_service_proto_rawDesc = "" +
	"\n" +
	"'openmarket/api/v1/pricing_service.proto\x12\x11openmarket.api.v1\x1a\x1bbuf/validate/validate.proto\"\x88\x02\n" +
	"\x13IdentifyItemRequest\x12*\n" +
	"\vdescription\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x18\xd0\x0fR\vdescription\x12)\n" +
	"\x06photos\x18\x02 \x03(\fB\x11\xbaH\x0e\x92\x01\v\x10\x01\"\az\x05\x18\x80\x80\x80\x02R\x06photos:\x99\x01\xbaH\x95\x01\x1a\x92\x01\n" +
	"\x1bidentify_item.needs_an_item\x12=send a description of at least 3 characters, a photo, or both\x1a4size(this.description) >= 3 || size(this.photos) > 0\"\xf3\x01\n" +
	"\x14IdentifyItemResponse\x12$\n" +
	"\x0eprice_check_id\x18\x01 \x01(\tR\fpriceCheckId\x12'\n" +
	"\x0fidentified_name\x18\x02 \x01(\tR\x0eidentifiedName\x12%\n" +
	"\x0esearch_queries\x18\x03 \x03(\tR\rsearchQueries\x12>\n" +
	"\tcondition\x18\x04 \x01(\x0e2 .openmarket.api.v1.ItemConditionR\tcondition\x12%\n" +
	"\x0ekey_attributes\x18\x05 \x03(\tR\rkeyAttributes\"\xc9\x01\n" +
	"\n" +
	"Comparable\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12$\n" +
	"\vprice_minor\x18\x02 \x01(\x03H\x00R\n" +
	"priceMinor\x88\x01\x01\x12\x17\n" +
	"\ais_sold\x18\x03 \x01(\bR\x06isSold\x12$\n" +
	"\vdays_listed\x18\x04 \x01(\x05H\x01R\n" +
	"daysListed\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\x05 \x01(\tH\x02R\x04city\x88\x01\x01B\x0e\n" +
	"\f_price_minorB\x0e\n" +
	"\f_days_listedB\a\n" +
	"\x05_city\"\xcf\x03\n" +
	"\vMarketStats\x12!\n" +
	"\fpriced_count\x18\x01 \x01(\x05R\vpricedCount\x12!\n" +
	"\fmedian_minor\x18\x02 \x01(\x03R\vmedianMinor\x12!\n" +
	"\flowest_minor\x18\x03 \x01(\x03R\vlowestMinor\x12#\n" +
	"\rhighest_minor\x18\x04 \x01(\x03R\fhighestMinor\x125\n" +
	"\x14lower_quartile_minor\x18\x05 \x01(\x03H\x00R\x12lowerQuartileMinor\x88\x01\x01\x125\n" +
	"\x14upper_quartile_minor\x18\x06 \x01(\x03H\x01R\x12upperQuartileMinor\x88\x01\x01\x12'\n" +
	"\x0fcurrency_symbol\x18\a \x01(\tR\x0ecurrencySymbol\x12\x1d\n" +
	"\n" +
	"sold_count\x18\b \x01(\x05R\tsoldCount\x122\n" +
	"\x13median_days_to_sell\x18\t \x01(\x05H\x02R\x10medianDaysToSell\x88\x01\x01B\x17\n" +
	"\x15_lower_quartile_minorB\x17\n" +
	"\x15_upper_quartile_minorB\x16\n" +
	"\x14_median_days_to_sell\"\x9b\x02\n" +
	"\x10PriceItemRequest\x121\n" +
	"\x0eprice_check_id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\fpriceCheckId\x12*\n" +
	"\x11search_query_used\x18\x02 \x01(\tR\x0fsearchQueryUsed\x12I\n" +
	"\vcomparables\x18\x03 \x03(\v2\x1d.openmarket.api.v1.ComparableB\b\xbaH\x05\x92\x01\x02\x10dR\vcomparables\x12<\n" +
	"\x05stats\x18\x04 \x01(\v2\x1e.openmarket.api.v1.MarketStatsB\x06\xbaH\x03\xc8\x01\x01R\x05stats\x12\x1f\n" +
	"\vmarket_name\x18\x05 \x01(\tR\n" +
	"marketName\"\x83\x01\n" +
	"\x11PriceItemResponse\x126\n" +
	"\x17recommended_price_minor\x18\x01 \x01(\x03R\x15recommendedPriceMinor\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"n\n" +
	"\x1fSubmitPriceCheckFeedbackRequest\x121\n" +
	"\x0eprice_check_id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\fpriceCheckId\x12\x18\n" +
	"\ahelpful\x18\x02 \x01(\bR\ahelpful\"\"\n" +
	" SubmitPriceCheckFeedbackResponse\"M\n" +
	"\x18RecordPriceCopiedRequest\x121\n" +
	"\x0eprice_check_id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\fpriceCheckId\"\x1b\n" +
	"\x19RecordPriceCopiedResponse*\xa5\x01\n" +
	"\rItemCondition\x12\x1e\n" +
	"\x1aITEM_CONDITION_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ITEM_CONDITION_NEW\x10\x01\x12 \n" +
	"\x1cITEM_CONDITION_USED_LIKE_NEW\x10\x02\x12\x1c\n" +
	"\x18ITEM_CONDITION_USED_GOOD\x10\x03\x12\x1c\n" +
	"\x18ITEM_CONDITION_USED_FAIR\x10\x042\xbf\x03\n" +
	"\x0ePricingService\x12_\n" +
	"\fIdentifyItem\x12&.openmarket.api.v1.IdentifyItemRequest\x1a'.openmarket.api.v1.IdentifyItemResponse\x12V\n" +
	"\tPriceItem\x12#.openmarket.api.v1.PriceItemRequest\x1a$.openmarket.api.v1.PriceItemResponse\x12\x83\x01\n" +
	"\x18SubmitPriceCheckFeedback\x122.openmarket.api.v1.SubmitPriceCheckFeedbackRequest\x1a3.openmarket.api.v1.SubmitPriceCheckFeedbackResponse\x12n\n" +
	"\x11RecordPriceCopied\x12+.openmarket.api.v1.RecordPriceCopiedRequest\x1a,.openmarket.api.v1.RecordPriceCopiedResponseB\xd3\x01\n" +
	"\x15com.openmarket.api.v1B\x13PricingServiceProtoP\x01Z?frens.lol/openmarket/backend/pkg/protos/openmarket/api/v1;apiv1\xa2\x02\x03OAX\xaa\x02\x11Openmarket.Api.V1\xca\x02\x11Openmarket\\Api\\V1\xe2\x02\x1dOpenmarket\\Api\\V1\\GPBMetadata\xea\x02\x13Openmarket::Api::V1b\x06proto3"

var (
	file_openmarket_api_v1_pricing_service_proto_rawDescOnce sync.Once
	file_openmarket_api_v1_pricing_service_proto_rawDescData []byte
)

func file_openmarket_api_v1_pricing_service_proto_rawDescGZIP() []byte {
	file_openmarket_api_v1_pricing_service_proto_rawDescOnce.Do(func() {
		file_openmarket_api_v1_pricing_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openmarket_api_v1_pricing_service_proto_rawDesc), len(file_openmarket_api_v1_pricing_service_proto_rawDesc)))
	})
	return file_openmarket_api_v1_pricing_service_proto_rawDescData
}

var file_openmarket_api_v1_pricing_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_openmarket_api_v1_pricing_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_openmarket_api_v1_pricing_service_proto_goTypes = []any{
	(ItemCondition)(0),                       // 0: openmarket.api.v1.ItemCondition
	(*IdentifyItemRequest)(nil),              // 1: openmarket.api.v1.IdentifyItemRequest
	(*IdentifyItemResponse)(nil),             // 2: openmarket.api.v1.IdentifyItemResponse
	(*Comparable)(nil),                       // 3: openmarket.api.v1.Comparable
	(*MarketStats)(nil),                      // 4: openmarket.api.v1.MarketStats
	(*PriceItemRequest)(nil),                 // 5: openmarket.api.v1.PriceItemRequest
	(*PriceItemResponse)(nil),                // 6: openmarket.api.v1.PriceItemResponse
	(*SubmitPriceCheckFeedbackRequest)(nil),  // 7: openmarket.api.v1.SubmitPriceCheckFeedbackRequest
	(*SubmitPriceCheckFeedbackResponse)(nil), // 8: openmarket.api.v1.SubmitPriceCheckFeedbackResponse
	(*RecordPriceCopiedRequest)(nil),         // 9: openmarket.api.v1.RecordPriceCopiedRequest
	(*RecordPriceCopiedResponse)(nil),        // 10: openmarket.api.v1.RecordPriceCopiedResponse
}
var file_openmarket_api_v1_pricing_service_proto_depIdxs = []int32{
	0,  // 0: openmarket.api.v1.IdentifyItemResponse.condition:type_name -> openmarket.api.v1.ItemCondition
	3,  // 1: openmarket.api.v1.PriceItemRequest.comparables:type_name -> openmarket.api.v1.Comparable
	4,  // 2: openmarket.api.v1.PriceItemRequest.stats:type_name -> openmarket.api.v1.MarketStats
	1,  // 3: openmarket.api.v1.PricingService.IdentifyItem:input_type -> openmarket.api.v1.IdentifyItemRequest
	5,  // 4: openmarket.api.v1.PricingService.PriceItem:input_type -> openmarket.api.v1.PriceItemRequest
	7,  // 5: openmarket.api.v1.PricingService.SubmitPriceCheckFeedback:input_type -> openmarket.api.v1.SubmitPriceCheckFeedbackRequest
	9,  // 6: openmarket.api.v1.PricingService.RecordPriceCopied:input_type -> openmarket.api.v1.RecordPriceCopiedRequest
	2,  // 7: openmarket.api.v1.PricingService.IdentifyItem:output_type -> openmarket.api.v1.IdentifyItemResponse
	6,  // 8: openmarket.api.v1.PricingService.PriceItem:output_type -> openmarket.api.v1.PriceItemResponse
	8,  // 9: openmarket.api.v1.PricingService.SubmitPriceCheckFeedback:output_type -> openmarket.api.v1.SubmitPriceCheckFeedbackResponse
	10, // 10: openmarket.api.v1.PricingService.RecordPriceCopied:output_type -> openmarket.api.v1.RecordPriceCopiedResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_openmarket_api_v1_pricing_service_proto_init() }
func file_openmarket_api_v1_pricing_service_proto_init() {
	if File_openmarket_api_v1_pricing_service_proto != nil {
		return
	}
	file_openmarket_api_v1_pricing_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_openmarket_api_v1_pricing_service_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openmarket_api_v1_pricing_service_proto_rawDesc), len(file_openmarket_api_v1_pricing_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_openmarket_api_v1_pricing_service_proto_goTypes,
		DependencyIndexes: file_openmarket_api_v1_pricing_service_proto_depIdxs,
		EnumInfos:         file_openmarket_api_v1_pricing_service_proto_enumTypes,
		MessageInfos:      file_openmarket_api_v1_pricing_service_proto_msgTypes,
	}.Build()
	File_openmarket_api_v1_pricing_service_proto = out.File
	file_openmarket_api_v1_pricing_service_proto_goTypes = nil
	file_openmarket_api_v1_pricing_service_proto_depIdxs = nil
}
